# ═════════════════════════════════════════════════════════════════
# Django-CFG - Monolithic Docker Compose
# ═════════════════════════════════════════════════════════════════
# All services +100 ports (compared to StockAPIs)

name: djangocfg

services:
  # ─────────────────────────────────────────────────────────────────
  # Infrastructure
  # ─────────────────────────────────────────────────────────────────

  traefik:
    image: traefik:v2.11
    container_name: djangocfg_traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=djangocfg_djangocfg-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websocket.address=:8081"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - "7330:80"         # HTTP (Django-CFG: base 7300 +30)
      - "7331:443"        # HTTPS (+31)
      - "7333:8081"       # WebSocket (+33)
      - "7332:8080"       # Dashboard (+32)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - djangocfg-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"

  postgres:
    image: pgvector/pgvector:pg15
    container_name: djangocfg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
      - ./services/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - djangocfg_django_network

  redis:
    image: redis:7-alpine
    container_name: djangocfg_redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --databases 3
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - djangocfg_django_network

  # ─────────────────────────────────────────────────────────────────
  # Backend Services
  # ─────────────────────────────────────────────────────────────────

  django:
    build:
      context: ../..
      dockerfile: solution/docker/services/django/Dockerfile
    image: djangocfg-django:latest
    container_name: django
    restart: unless-stopped
    env_file:
      - .env
      - .env.secrets
    environment:
      DJANGO_SETTINGS_MODULE: api.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DJANGO_DEBUG}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      REDIS_DRAMATIQ_URL: redis://redis:6379/1
      REDIS_IPC_URL: redis://redis:6379/2
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ../volumes/django/media:/app/media:rw
    ports:
      - "7301:8000"  # Django-CFG: base 7300 (+01 Django API)
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/cfg/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - djangocfg-network
      - djangocfg_django_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django-api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.django-api.entrypoints=web"
      - "traefik.http.routers.django-api.service=django-api"
      - "traefik.http.services.django-api.loadbalancer.server.port=8000"

  django-dramatiq:
    build:
      context: ../..
      dockerfile: solution/docker/services/django/Dockerfile
    image: djangocfg-django:latest
    container_name: django-dramatiq
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: api.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DJANGO_DEBUG}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      REDIS_DRAMATIQ_URL: redis://redis:6379/1
      REDIS_IPC_URL: redis://redis:6379/2
      DRAMATIQ_PROCESSES: ${DRAMATIQ_PROCESSES:-2}
      DRAMATIQ_THREADS: ${DRAMATIQ_THREADS:-4}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DJANGO_CREATE_ADMIN: "false"
    volumes:
      - ../volumes/django/media:/app/media:rw
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      django:
        condition: service_healthy
    command: >
      sh -c "python manage.py rundramatiq
      --processes $${DRAMATIQ_PROCESSES:-2}
      --threads $${DRAMATIQ_THREADS:-4}"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f rundramatiq > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M
    networks:
      - djangocfg-network
      - djangocfg_django_network

  websocket:
    build:
      context: ..
      dockerfile: docker/services/websocket/Dockerfile
    image: djangocfg-websocket:latest
    container_name: websocket
    restart: unless-stopped
    environment:
      WS_HOST: ${WS_HOST}
      WS_PORT: ${WS_PORT}
      HEALTH_PORT: ${HEALTH_PORT}
      REDIS_URL: redis://redis:6379/2
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: HS256
      JWT_EXPIRES_IN: 86400
      ENVIRONMENT: ${ENVIRONMENT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FORMAT: pretty
    ports:
      - "7320:8765"  # WebSocket (Django-CFG: base 7300 +20)
      - "7321:8766"  # Health check (+21)
    volumes:
      - ../volumes/django/logs:/app/logs
    networks:
      - djangocfg-network
      - djangocfg_django_network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8766/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.websocket.rule=Host(`ws.localhost`)"
      - "traefik.http.routers.websocket.entrypoints=web"
      - "traefik.http.services.websocket.loadbalancer.server.port=8765"

  # ─────────────────────────────────────────────────────────────────
  # Frontend Services
  # ─────────────────────────────────────────────────────────────────

  frontend-demo:
    build:
      context: ../projects/frontend
      dockerfile: ../../docker/services/frontend/Dockerfile
      target: demo
      args:
        DJANGO_API_URL: ${DJANGO_API_URL}
        IPC_WS_URL: ${IPC_WS_URL}
    image: djangocfg-frontend:demo
    container_name: frontend-demo
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_SITE_URL: http://demo.localhost:7300
      NEXT_PUBLIC_API_URL: ${DJANGO_API_URL}
      NEXT_PUBLIC_WS_RPC_URL: ${IPC_WS_URL}
    ports:
      - "7310:3000"  # Django-CFG: base 7300 (+10 Frontend Demo)
    depends_on:
      django:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          memory: 1G
    networks:
      - djangocfg-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo.rule=Host(`demo.localhost`)"
      - "traefik.http.routers.demo.entrypoints=web"
      - "traefik.http.routers.demo.service=demo"
      - "traefik.http.services.demo.loadbalancer.server.port=3000"

  frontend-web:
    build:
      context: ..
      dockerfile: docker/services/web/Dockerfile
      args:
        DJANGO_API_URL: ${DJANGO_API_URL}
        DEMO_URL: ${DEMO_URL}
    image: djangocfg-web:latest
    container_name: frontend-web
    restart: unless-stopped
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3001
    ports:
      - "7311:3001"  # Django-CFG: base 7300 (+11 Frontend Web)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          memory: 512M
    networks:
      - djangocfg-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.djangocfg-site.rule=Host(`localhost`) && PathPrefix(`/docs`)"
      - "traefik.http.routers.djangocfg-site.entrypoints=web"
      - "traefik.http.routers.djangocfg-site.service=djangocfg-site"
      - "traefik.http.services.djangocfg-site.loadbalancer.server.port=3001"

# ═════════════════════════════════════════════════════════════════
# Networks
# ═════════════════════════════════════════════════════════════════

networks:
  djangocfg-network:
    driver: bridge
  djangocfg_django_network:
    driver: bridge
    internal: true

# ═════════════════════════════════════════════════════════════════
# Local volumes - no named volumes needed
# ═════════════════════════════════════════════════════════════════
