// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  PaymentsApiKeyCreateCreateData,
  PaymentsApiKeyCreateCreateResponses,
  PaymentsApiKeyValidateCreateData,
  PaymentsApiKeyValidateCreateResponses,
  PaymentsApiKeysListData,
  PaymentsApiKeysListResponses,
  PaymentsApiKeysRetrieveData,
  PaymentsApiKeysRetrieveResponses,
  PaymentsBalancesListData,
  PaymentsBalancesListResponses,
  PaymentsBalancesRetrieveData,
  PaymentsBalancesRetrieveResponses,
  PaymentsBalancesCurrentRetrieveData,
  PaymentsBalancesCurrentRetrieveResponses,
  PaymentsCurrenciesListData,
  PaymentsCurrenciesListResponses,
  PaymentsCurrenciesRetrieveData,
  PaymentsCurrenciesRetrieveResponses,
  PaymentsCurrenciesNetworksRetrieveData,
  PaymentsCurrenciesNetworksRetrieveResponses,
  PaymentsCurrenciesCryptoRetrieveData,
  PaymentsCurrenciesCryptoRetrieveResponses,
  PaymentsCurrenciesFiatRetrieveData,
  PaymentsCurrenciesFiatRetrieveResponses,
  PaymentsCurrenciesRatesRetrieveData,
  PaymentsCurrenciesRatesRetrieveResponses,
  PaymentsCurrenciesSupportedListData,
  PaymentsCurrenciesSupportedListResponses,
  PaymentsCurrencyNetworksListData,
  PaymentsCurrencyNetworksListResponses,
  PaymentsCurrencyNetworksRetrieveData,
  PaymentsCurrencyNetworksRetrieveResponses,
  PaymentsCurrencyNetworksByCurrencyRetrieveData,
  PaymentsCurrencyNetworksByCurrencyRetrieveResponses,
  PaymentsEndpointGroupsListData,
  PaymentsEndpointGroupsListResponses,
  PaymentsEndpointGroupsRetrieveData,
  PaymentsEndpointGroupsRetrieveResponses,
  PaymentsEndpointGroupsPricingRetrieveData,
  PaymentsEndpointGroupsPricingRetrieveResponses,
  PaymentsPaymentCreateCreateData,
  PaymentsPaymentCreateCreateResponses,
  PaymentsPaymentStatusRetrieveData,
  PaymentsPaymentStatusRetrieveResponses,
  PaymentsPaymentsListData,
  PaymentsPaymentsListResponses,
  PaymentsPaymentsRetrieveData,
  PaymentsPaymentsRetrieveResponses,
  PaymentsSubscriptionCreateCreateData,
  PaymentsSubscriptionCreateCreateResponses,
  PaymentsSubscriptionsListData,
  PaymentsSubscriptionsListResponses,
  PaymentsSubscriptionsRetrieveData,
  PaymentsSubscriptionsRetrieveResponses,
  PaymentsSubscriptionsActiveListData,
  PaymentsSubscriptionsActiveListResponses,
  PaymentsTariffEndpointGroupsListData,
  PaymentsTariffEndpointGroupsListResponses,
  PaymentsTariffEndpointGroupsRetrieveData,
  PaymentsTariffEndpointGroupsRetrieveResponses,
  PaymentsTariffEndpointGroupsByEndpointGroupRetrieveData,
  PaymentsTariffEndpointGroupsByEndpointGroupRetrieveResponses,
  PaymentsTariffEndpointGroupsByTariffRetrieveData,
  PaymentsTariffEndpointGroupsByTariffRetrieveResponses,
  PaymentsTariffsListData,
  PaymentsTariffsListResponses,
  PaymentsTariffsRetrieveData,
  PaymentsTariffsRetrieveResponses,
  PaymentsTariffsEndpointGroupsRetrieveData,
  PaymentsTariffsEndpointGroupsRetrieveResponses,
  PaymentsTariffsAvailableListData,
  PaymentsTariffsAvailableListResponses,
  PaymentsTariffsComparisonRetrieveData,
  PaymentsTariffsComparisonRetrieveResponses,
  PaymentsTariffsFreeRetrieveData,
  PaymentsTariffsFreeRetrieveResponses,
  PaymentsTariffsPaidRetrieveData,
  PaymentsTariffsPaidRetrieveResponses,
  PaymentsTransactionsListData,
  PaymentsTransactionsListResponses,
  PaymentsTransactionsRetrieveData,
  PaymentsTransactionsRetrieveResponses,
  PaymentsTransactionsSummaryRetrieveData,
  PaymentsTransactionsSummaryRetrieveResponses,
  PaymentsUsersApiKeysListData,
  PaymentsUsersApiKeysListResponses,
  PaymentsUsersApiKeysCreateData,
  PaymentsUsersApiKeysCreateResponses,
  PaymentsUsersApiKeysDestroyData,
  PaymentsUsersApiKeysDestroyResponses,
  PaymentsUsersApiKeysRetrieveData,
  PaymentsUsersApiKeysRetrieveResponses,
  PaymentsUsersApiKeysPartialUpdateData,
  PaymentsUsersApiKeysPartialUpdateResponses,
  PaymentsUsersApiKeysUpdateData,
  PaymentsUsersApiKeysUpdateResponses,
  PaymentsUsersApiKeysDeactivateCreateData,
  PaymentsUsersApiKeysDeactivateCreateResponses,
  PaymentsUsersApiKeysRegenerateCreateData,
  PaymentsUsersApiKeysRegenerateCreateResponses,
  PaymentsUsersApiKeysUsageStatsRetrieveData,
  PaymentsUsersApiKeysUsageStatsRetrieveResponses,
  PaymentsUsersPaymentsListData,
  PaymentsUsersPaymentsListResponses,
  PaymentsUsersPaymentsCreateData,
  PaymentsUsersPaymentsCreateResponses,
  PaymentsUsersPaymentsDestroyData,
  PaymentsUsersPaymentsDestroyResponses,
  PaymentsUsersPaymentsRetrieveData,
  PaymentsUsersPaymentsRetrieveResponses,
  PaymentsUsersPaymentsPartialUpdateData,
  PaymentsUsersPaymentsPartialUpdateResponses,
  PaymentsUsersPaymentsUpdateData,
  PaymentsUsersPaymentsUpdateResponses,
  PaymentsUsersPaymentsCheckStatusCreateData,
  PaymentsUsersPaymentsCheckStatusCreateResponses,
  PaymentsUsersPaymentsSummaryRetrieveData,
  PaymentsUsersPaymentsSummaryRetrieveResponses,
  PaymentsUsersSubscriptionsListData,
  PaymentsUsersSubscriptionsListResponses,
  PaymentsUsersSubscriptionsCreateData,
  PaymentsUsersSubscriptionsCreateResponses,
  PaymentsUsersSubscriptionsDestroyData,
  PaymentsUsersSubscriptionsDestroyResponses,
  PaymentsUsersSubscriptionsRetrieveData,
  PaymentsUsersSubscriptionsRetrieveResponses,
  PaymentsUsersSubscriptionsPartialUpdateData,
  PaymentsUsersSubscriptionsPartialUpdateResponses,
  PaymentsUsersSubscriptionsUpdateData,
  PaymentsUsersSubscriptionsUpdateResponses,
  PaymentsUsersSubscriptionsCancelCreateData,
  PaymentsUsersSubscriptionsCancelCreateResponses,
  PaymentsUsersSubscriptionsRenewCreateData,
  PaymentsUsersSubscriptionsRenewCreateResponses,
  PaymentsUsersSubscriptionsActiveRetrieveData,
  PaymentsUsersSubscriptionsActiveRetrieveResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Generic view to create API key.
 */
export const paymentsApiKeyCreateCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsApiKeyCreateCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsApiKeyCreateCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/api-key/create/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Validate API key.
 */
export const paymentsApiKeyValidateCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsApiKeyValidateCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsApiKeyValidateCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/api-key/validate/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Global API keys ViewSet: /api-keys/
 */
export const paymentsApiKeysList = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsApiKeysListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsApiKeysListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/api-keys/",
    ...options,
  });
};

/**
 * Global API keys ViewSet: /api-keys/
 */
export const paymentsApiKeysRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<PaymentsApiKeysRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsApiKeysRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/api-keys/{id}/",
    ...options,
  });
};

/**
 * User balance ViewSet - read only.
 */
export const paymentsBalancesList = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsBalancesListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsBalancesListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/balances/",
    ...options,
  });
};

/**
 * User balance ViewSet - read only.
 */
export const paymentsBalancesRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<PaymentsBalancesRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsBalancesRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/balances/{id}/",
    ...options,
  });
};

/**
 * Get current user balance.
 */
export const paymentsBalancesCurrentRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsBalancesCurrentRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsBalancesCurrentRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/balances/current/",
    ...options,
  });
};

/**
 * Currency ViewSet: /currencies/
 */
export const paymentsCurrenciesList = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsCurrenciesListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsCurrenciesListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currencies/",
    ...options,
  });
};

/**
 * Currency ViewSet: /currencies/
 */
export const paymentsCurrenciesRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsCurrenciesRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsCurrenciesRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currencies/{id}/",
    ...options,
  });
};

/**
 * Get networks for specific currency.
 */
export const paymentsCurrenciesNetworksRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsCurrenciesNetworksRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsCurrenciesNetworksRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currencies/{id}/networks/",
    ...options,
  });
};

/**
 * Get only cryptocurrencies.
 */
export const paymentsCurrenciesCryptoRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsCurrenciesCryptoRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsCurrenciesCryptoRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currencies/crypto/",
    ...options,
  });
};

/**
 * Get only fiat currencies.
 */
export const paymentsCurrenciesFiatRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsCurrenciesFiatRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsCurrenciesFiatRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currencies/fiat/",
    ...options,
  });
};

/**
 * Get current exchange rates.
 */
export const paymentsCurrenciesRatesRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsCurrenciesRatesRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsCurrenciesRatesRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currencies/rates/",
    ...options,
  });
};

/**
 * Generic view to list supported currencies.
 */
export const paymentsCurrenciesSupportedList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsCurrenciesSupportedListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsCurrenciesSupportedListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currencies/supported/",
    ...options,
  });
};

/**
 * Currency Network ViewSet: /currency-networks/
 */
export const paymentsCurrencyNetworksList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsCurrencyNetworksListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsCurrencyNetworksListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currency-networks/",
    ...options,
  });
};

/**
 * Currency Network ViewSet: /currency-networks/
 */
export const paymentsCurrencyNetworksRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsCurrencyNetworksRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsCurrencyNetworksRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currency-networks/{id}/",
    ...options,
  });
};

/**
 * Get networks grouped by currency.
 */
export const paymentsCurrencyNetworksByCurrencyRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    PaymentsCurrencyNetworksByCurrencyRetrieveData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsCurrencyNetworksByCurrencyRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/currency-networks/by_currency/",
    ...options,
  });
};

/**
 * Endpoint groups ViewSet: /endpoint-groups/
 */
export const paymentsEndpointGroupsList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsEndpointGroupsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsEndpointGroupsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/endpoint-groups/",
    ...options,
  });
};

/**
 * Endpoint groups ViewSet: /endpoint-groups/
 */
export const paymentsEndpointGroupsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsEndpointGroupsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsEndpointGroupsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/endpoint-groups/{id}/",
    ...options,
  });
};

/**
 * Get pricing for endpoint group.
 */
export const paymentsEndpointGroupsPricingRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsEndpointGroupsPricingRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsEndpointGroupsPricingRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/endpoint-groups/{id}/pricing/",
    ...options,
  });
};

/**
 * Generic view to create payment.
 */
export const paymentsPaymentCreateCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsPaymentCreateCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsPaymentCreateCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/payment/create/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Generic view to check payment status.
 */
export const paymentsPaymentStatusRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsPaymentStatusRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsPaymentStatusRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/payment/status/{internal_payment_id}/",
    ...options,
  });
};

/**
 * Global payment ViewSet: /payments/
 */
export const paymentsPaymentsList = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsPaymentsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsPaymentsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/payments/",
    ...options,
  });
};

/**
 * Global payment ViewSet: /payments/
 */
export const paymentsPaymentsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<PaymentsPaymentsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsPaymentsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/payments/{id}/",
    ...options,
  });
};

/**
 * Generic view to create subscription.
 */
export const paymentsSubscriptionCreateCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsSubscriptionCreateCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsSubscriptionCreateCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/subscription/create/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Global subscription ViewSet: /subscriptions/
 */
export const paymentsSubscriptionsList = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsSubscriptionsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsSubscriptionsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/subscriptions/",
    ...options,
  });
};

/**
 * Global subscription ViewSet: /subscriptions/
 */
export const paymentsSubscriptionsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsSubscriptionsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsSubscriptionsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/subscriptions/{id}/",
    ...options,
  });
};

/**
 * Generic view to list active subscriptions.
 */
export const paymentsSubscriptionsActiveList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsSubscriptionsActiveListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsSubscriptionsActiveListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/subscriptions/active/",
    ...options,
  });
};

/**
 * Tariff Endpoint Group ViewSet: /tariff-endpoint-groups/
 */
export const paymentsTariffEndpointGroupsList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsTariffEndpointGroupsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTariffEndpointGroupsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariff-endpoint-groups/",
    ...options,
  });
};

/**
 * Tariff Endpoint Group ViewSet: /tariff-endpoint-groups/
 */
export const paymentsTariffEndpointGroupsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsTariffEndpointGroupsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsTariffEndpointGroupsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariff-endpoint-groups/{id}/",
    ...options,
  });
};

/**
 * Get tariffs by endpoint group.
 */
export const paymentsTariffEndpointGroupsByEndpointGroupRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    PaymentsTariffEndpointGroupsByEndpointGroupRetrieveData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTariffEndpointGroupsByEndpointGroupRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariff-endpoint-groups/by_endpoint_group/",
    ...options,
  });
};

/**
 * Get endpoint groups by tariff.
 */
export const paymentsTariffEndpointGroupsByTariffRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    PaymentsTariffEndpointGroupsByTariffRetrieveData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTariffEndpointGroupsByTariffRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariff-endpoint-groups/by_tariff/",
    ...options,
  });
};

/**
 * Tariff ViewSet: /tariffs/
 */
export const paymentsTariffsList = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsTariffsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTariffsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariffs/",
    ...options,
  });
};

/**
 * Tariff ViewSet: /tariffs/
 */
export const paymentsTariffsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<PaymentsTariffsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsTariffsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariffs/{id}/",
    ...options,
  });
};

/**
 * Get endpoint groups for tariff.
 */
export const paymentsTariffsEndpointGroupsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsTariffsEndpointGroupsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsTariffsEndpointGroupsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariffs/{id}/endpoint_groups/",
    ...options,
  });
};

/**
 * Generic view to list available tariffs.
 */
export const paymentsTariffsAvailableList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsTariffsAvailableListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTariffsAvailableListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariffs/available/",
    ...options,
  });
};

/**
 * Get tariff comparison data.
 */
export const paymentsTariffsComparisonRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsTariffsComparisonRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTariffsComparisonRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariffs/comparison/",
    ...options,
  });
};

/**
 * Get free tariffs.
 */
export const paymentsTariffsFreeRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsTariffsFreeRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTariffsFreeRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariffs/free/",
    ...options,
  });
};

/**
 * Get paid tariffs.
 */
export const paymentsTariffsPaidRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsTariffsPaidRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTariffsPaidRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/tariffs/paid/",
    ...options,
  });
};

/**
 * Transaction ViewSet - read only.
 */
export const paymentsTransactionsList = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsTransactionsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTransactionsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/transactions/",
    ...options,
  });
};

/**
 * Transaction ViewSet - read only.
 */
export const paymentsTransactionsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsTransactionsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsTransactionsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/transactions/{id}/",
    ...options,
  });
};

/**
 * Get transaction summary.
 */
export const paymentsTransactionsSummaryRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsTransactionsSummaryRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PaymentsTransactionsSummaryRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/transactions/summary/",
    ...options,
  });
};

/**
 * Nested ViewSet for user API keys: /users/{user_id}/api-keys/
 */
export const paymentsUsersApiKeysList = <ThrowOnError extends boolean = false>(
  options: Options<PaymentsUsersApiKeysListData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersApiKeysListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/",
    ...options,
  });
};

/**
 * Nested ViewSet for user API keys: /users/{user_id}/api-keys/
 */
export const paymentsUsersApiKeysCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersApiKeysCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsUsersApiKeysCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Nested ViewSet for user API keys: /users/{user_id}/api-keys/
 */
export const paymentsUsersApiKeysDestroy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersApiKeysDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    PaymentsUsersApiKeysDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/{id}/",
    ...options,
  });
};

/**
 * Nested ViewSet for user API keys: /users/{user_id}/api-keys/
 */
export const paymentsUsersApiKeysRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersApiKeysRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersApiKeysRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/{id}/",
    ...options,
  });
};

/**
 * Nested ViewSet for user API keys: /users/{user_id}/api-keys/
 */
export const paymentsUsersApiKeysPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersApiKeysPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PaymentsUsersApiKeysPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Nested ViewSet for user API keys: /users/{user_id}/api-keys/
 */
export const paymentsUsersApiKeysUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersApiKeysUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PaymentsUsersApiKeysUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Deactivate API key.
 */
export const paymentsUsersApiKeysDeactivateCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersApiKeysDeactivateCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsUsersApiKeysDeactivateCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/{id}/deactivate/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Regenerate API key.
 */
export const paymentsUsersApiKeysRegenerateCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersApiKeysRegenerateCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsUsersApiKeysRegenerateCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/{id}/regenerate/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get usage statistics for API key.
 */
export const paymentsUsersApiKeysUsageStatsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersApiKeysUsageStatsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersApiKeysUsageStatsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/api-keys/{id}/usage_stats/",
    ...options,
  });
};

/**
 * Nested ViewSet for user payments: /users/{user_id}/payments/
 */
export const paymentsUsersPaymentsList = <ThrowOnError extends boolean = false>(
  options: Options<PaymentsUsersPaymentsListData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersPaymentsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/payments/",
    ...options,
  });
};

/**
 * Nested ViewSet for user payments: /users/{user_id}/payments/
 */
export const paymentsUsersPaymentsCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersPaymentsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsUsersPaymentsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/payments/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Nested ViewSet for user payments: /users/{user_id}/payments/
 */
export const paymentsUsersPaymentsDestroy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersPaymentsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    PaymentsUsersPaymentsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/payments/{id}/",
    ...options,
  });
};

/**
 * Nested ViewSet for user payments: /users/{user_id}/payments/
 */
export const paymentsUsersPaymentsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersPaymentsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersPaymentsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/payments/{id}/",
    ...options,
  });
};

/**
 * Nested ViewSet for user payments: /users/{user_id}/payments/
 */
export const paymentsUsersPaymentsPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersPaymentsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PaymentsUsersPaymentsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/payments/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Nested ViewSet for user payments: /users/{user_id}/payments/
 */
export const paymentsUsersPaymentsUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersPaymentsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PaymentsUsersPaymentsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/payments/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Check payment status via provider API.
 */
export const paymentsUsersPaymentsCheckStatusCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersPaymentsCheckStatusCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsUsersPaymentsCheckStatusCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/payments/{id}/check_status/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get payment summary for user.
 */
export const paymentsUsersPaymentsSummaryRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersPaymentsSummaryRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersPaymentsSummaryRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/payments/summary/",
    ...options,
  });
};

/**
 * Nested ViewSet for user subscriptions: /users/{user_id}/subscriptions/
 */
export const paymentsUsersSubscriptionsList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsListData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersSubscriptionsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/",
    ...options,
  });
};

/**
 * Nested ViewSet for user subscriptions: /users/{user_id}/subscriptions/
 */
export const paymentsUsersSubscriptionsCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsUsersSubscriptionsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Nested ViewSet for user subscriptions: /users/{user_id}/subscriptions/
 */
export const paymentsUsersSubscriptionsDestroy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    PaymentsUsersSubscriptionsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/{id}/",
    ...options,
  });
};

/**
 * Nested ViewSet for user subscriptions: /users/{user_id}/subscriptions/
 */
export const paymentsUsersSubscriptionsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersSubscriptionsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/{id}/",
    ...options,
  });
};

/**
 * Nested ViewSet for user subscriptions: /users/{user_id}/subscriptions/
 */
export const paymentsUsersSubscriptionsPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PaymentsUsersSubscriptionsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Nested ViewSet for user subscriptions: /users/{user_id}/subscriptions/
 */
export const paymentsUsersSubscriptionsUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PaymentsUsersSubscriptionsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Cancel subscription.
 */
export const paymentsUsersSubscriptionsCancelCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsCancelCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsUsersSubscriptionsCancelCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/{id}/cancel/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Renew subscription.
 */
export const paymentsUsersSubscriptionsRenewCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsRenewCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PaymentsUsersSubscriptionsRenewCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/{id}/renew/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get active subscriptions for user.
 */
export const paymentsUsersSubscriptionsActiveRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsUsersSubscriptionsActiveRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PaymentsUsersSubscriptionsActiveRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/payments/users/{user_id}/subscriptions/active/",
    ...options,
  });
};
