// This file is auto-generated by @hey-api/openapi-ts

/**
 * Serializer for shop categories.
 */
export type CategoryReadable = {
  readonly id: number;
  name: string;
  readonly slug: string;
  description?: string;
  image?: string | null;
  parent?: number | null;
  meta_title?: string;
  meta_description?: string;
  readonly products_count: number;
  readonly children: string;
  is_active?: boolean;
  sort_order?: number;
  readonly created_at: string;
  readonly updated_at: string;
};

/**
 * Serializer for shop categories.
 */
export type CategoryWritable = {
  name: string;
  description?: string;
  image?: string | null;
  parent?: number | null;
  meta_title?: string;
  meta_description?: string;
  is_active?: boolean;
  sort_order?: number;
};

/**
 * Serializer for order detail view.
 */
export type OrderDetailReadable = {
  readonly id: number;
  order_number: string;
  readonly customer: string;
  /**
   * * `pending` - Pending
   * * `processing` - Processing
   * * `shipped` - Shipped
   * * `delivered` - Delivered
   * * `cancelled` - Cancelled
   * * `refunded` - Refunded
   */
  status?:
    | "pending"
    | "processing"
    | "shipped"
    | "delivered"
    | "cancelled"
    | "refunded";
  subtotal?: string;
  tax_amount?: string;
  shipping_amount?: string;
  discount_amount?: string;
  total_amount?: string;
  billing_address: string;
  shipping_address: string;
  customer_notes?: string;
  admin_notes?: string;
  readonly items: Array<OrderItemReadable>;
  readonly created_at: string;
  readonly updated_at: string;
  shipped_at?: string | null;
  delivered_at?: string | null;
};

/**
 * Serializer for order detail view.
 */
export type OrderDetailWritable = {
  order_number: string;
  /**
   * * `pending` - Pending
   * * `processing` - Processing
   * * `shipped` - Shipped
   * * `delivered` - Delivered
   * * `cancelled` - Cancelled
   * * `refunded` - Refunded
   */
  status?:
    | "pending"
    | "processing"
    | "shipped"
    | "delivered"
    | "cancelled"
    | "refunded";
  subtotal?: string;
  tax_amount?: string;
  shipping_amount?: string;
  discount_amount?: string;
  total_amount?: string;
  billing_address: string;
  shipping_address: string;
  customer_notes?: string;
  admin_notes?: string;
  shipped_at?: string | null;
  delivered_at?: string | null;
};

/**
 * Serializer for order items.
 */
export type OrderItemReadable = {
  readonly id: number;
  product: ProductListReadable;
  quantity?: number;
  unit_price: string;
  readonly total_price: string;
  readonly product_name: string;
  readonly product_sku: string;
  readonly created_at: string;
};

/**
 * Serializer for order items.
 */
export type OrderItemWritable = {
  product: ProductListWritable;
  quantity?: number;
  unit_price: string;
};

/**
 * Serializer for order list view.
 */
export type OrderListReadable = {
  readonly id: number;
  order_number: string;
  readonly customer: string;
  /**
   * * `pending` - Pending
   * * `processing` - Processing
   * * `shipped` - Shipped
   * * `delivered` - Delivered
   * * `cancelled` - Cancelled
   * * `refunded` - Refunded
   */
  status?:
    | "pending"
    | "processing"
    | "shipped"
    | "delivered"
    | "cancelled"
    | "refunded";
  subtotal?: string;
  total_amount?: string;
  readonly items_count: string;
  readonly created_at: string;
  readonly updated_at: string;
};

/**
 * Serializer for order list view.
 */
export type OrderListWritable = {
  order_number: string;
  /**
   * * `pending` - Pending
   * * `processing` - Processing
   * * `shipped` - Shipped
   * * `delivered` - Delivered
   * * `cancelled` - Cancelled
   * * `refunded` - Refunded
   */
  status?:
    | "pending"
    | "processing"
    | "shipped"
    | "delivered"
    | "cancelled"
    | "refunded";
  subtotal?: string;
  total_amount?: string;
};

export type PaginatedCategoryListReadable = {
  /**
   * Total number of items across all pages
   */
  count: number;
  /**
   * Current page number (1-based)
   */
  page: number;
  /**
   * Total number of pages
   */
  pages: number;
  /**
   * Number of items per page
   */
  page_size: number;
  /**
   * Whether there is a next page
   */
  has_next: boolean;
  /**
   * Whether there is a previous page
   */
  has_previous: boolean;
  /**
   * Next page number (null if no next page)
   */
  next_page?: number | null;
  /**
   * Previous page number (null if no previous page)
   */
  previous_page?: number | null;
  /**
   * Array of items for current page
   */
  results: Array<CategoryReadable>;
};

export type PaginatedCategoryListWritable = {
  /**
   * Total number of items across all pages
   */
  count: number;
  /**
   * Current page number (1-based)
   */
  page: number;
  /**
   * Total number of pages
   */
  pages: number;
  /**
   * Number of items per page
   */
  page_size: number;
  /**
   * Whether there is a next page
   */
  has_next: boolean;
  /**
   * Whether there is a previous page
   */
  has_previous: boolean;
  /**
   * Next page number (null if no next page)
   */
  next_page?: number | null;
  /**
   * Previous page number (null if no previous page)
   */
  previous_page?: number | null;
  /**
   * Array of items for current page
   */
  results: Array<CategoryWritable>;
};

export type PaginatedOrderListListReadable = {
  /**
   * Total number of items across all pages
   */
  count: number;
  /**
   * Current page number (1-based)
   */
  page: number;
  /**
   * Total number of pages
   */
  pages: number;
  /**
   * Number of items per page
   */
  page_size: number;
  /**
   * Whether there is a next page
   */
  has_next: boolean;
  /**
   * Whether there is a previous page
   */
  has_previous: boolean;
  /**
   * Next page number (null if no next page)
   */
  next_page?: number | null;
  /**
   * Previous page number (null if no previous page)
   */
  previous_page?: number | null;
  /**
   * Array of items for current page
   */
  results: Array<OrderListReadable>;
};

export type PaginatedOrderListListWritable = {
  /**
   * Total number of items across all pages
   */
  count: number;
  /**
   * Current page number (1-based)
   */
  page: number;
  /**
   * Total number of pages
   */
  pages: number;
  /**
   * Number of items per page
   */
  page_size: number;
  /**
   * Whether there is a next page
   */
  has_next: boolean;
  /**
   * Whether there is a previous page
   */
  has_previous: boolean;
  /**
   * Next page number (null if no next page)
   */
  next_page?: number | null;
  /**
   * Previous page number (null if no previous page)
   */
  previous_page?: number | null;
  /**
   * Array of items for current page
   */
  results: Array<OrderListWritable>;
};

export type PaginatedProductListListReadable = {
  /**
   * Total number of items across all pages
   */
  count: number;
  /**
   * Current page number (1-based)
   */
  page: number;
  /**
   * Total number of pages
   */
  pages: number;
  /**
   * Number of items per page
   */
  page_size: number;
  /**
   * Whether there is a next page
   */
  has_next: boolean;
  /**
   * Whether there is a previous page
   */
  has_previous: boolean;
  /**
   * Next page number (null if no next page)
   */
  next_page?: number | null;
  /**
   * Previous page number (null if no previous page)
   */
  previous_page?: number | null;
  /**
   * Array of items for current page
   */
  results: Array<ProductListReadable>;
};

export type PaginatedProductListListWritable = {
  /**
   * Total number of items across all pages
   */
  count: number;
  /**
   * Current page number (1-based)
   */
  page: number;
  /**
   * Total number of pages
   */
  pages: number;
  /**
   * Number of items per page
   */
  page_size: number;
  /**
   * Whether there is a next page
   */
  has_next: boolean;
  /**
   * Whether there is a previous page
   */
  has_previous: boolean;
  /**
   * Next page number (null if no next page)
   */
  next_page?: number | null;
  /**
   * Previous page number (null if no previous page)
   */
  previous_page?: number | null;
  /**
   * Array of items for current page
   */
  results: Array<ProductListWritable>;
};

/**
 * Serializer for product detail view.
 */
export type ProductDetailReadable = {
  readonly id: number;
  name: string;
  slug?: string;
  description: string;
  short_description?: string;
  price: string;
  sale_price?: string | null;
  readonly current_price: string;
  readonly is_on_sale: boolean;
  readonly discount_percentage: number;
  sku: string;
  stock_quantity?: number;
  manage_stock?: boolean;
  readonly is_in_stock: boolean;
  category: CategoryReadable;
  image?: string | null;
  /**
   * * `active` - Active
   * * `inactive` - Inactive
   * * `out_of_stock` - Out of Stock
   */
  status?: "active" | "inactive" | "out_of_stock";
  is_featured?: boolean;
  is_digital?: boolean;
  meta_title?: string;
  meta_description?: string;
  views_count?: number;
  sales_count?: number;
  /**
   * Weight in kg
   */
  weight?: string | null;
  /**
   * Length in cm
   */
  length?: string | null;
  /**
   * Width in cm
   */
  width?: string | null;
  /**
   * Height in cm
   */
  height?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
};

/**
 * Serializer for product detail view.
 */
export type ProductDetailWritable = {
  name: string;
  slug?: string;
  description: string;
  short_description?: string;
  price: string;
  sale_price?: string | null;
  sku: string;
  stock_quantity?: number;
  manage_stock?: boolean;
  category: CategoryWritable;
  image?: string | null;
  /**
   * * `active` - Active
   * * `inactive` - Inactive
   * * `out_of_stock` - Out of Stock
   */
  status?: "active" | "inactive" | "out_of_stock";
  is_featured?: boolean;
  is_digital?: boolean;
  meta_title?: string;
  meta_description?: string;
  views_count?: number;
  sales_count?: number;
  /**
   * Weight in kg
   */
  weight?: string | null;
  /**
   * Length in cm
   */
  length?: string | null;
  /**
   * Width in cm
   */
  width?: string | null;
  /**
   * Height in cm
   */
  height?: string | null;
};

/**
 * Serializer for product list view.
 */
export type ProductListReadable = {
  readonly id: number;
  name: string;
  slug?: string;
  short_description?: string;
  price: string;
  sale_price?: string | null;
  readonly current_price: string;
  readonly is_on_sale: boolean;
  readonly discount_percentage: number;
  category: CategoryReadable;
  image?: string | null;
  /**
   * * `active` - Active
   * * `inactive` - Inactive
   * * `out_of_stock` - Out of Stock
   */
  status?: "active" | "inactive" | "out_of_stock";
  is_featured?: boolean;
  is_digital?: boolean;
  stock_quantity?: number;
  readonly is_in_stock: boolean;
  views_count?: number;
  sales_count?: number;
  readonly created_at: string;
};

/**
 * Serializer for product list view.
 */
export type ProductListWritable = {
  name: string;
  slug?: string;
  short_description?: string;
  price: string;
  sale_price?: string | null;
  category: CategoryWritable;
  image?: string | null;
  /**
   * * `active` - Active
   * * `inactive` - Inactive
   * * `out_of_stock` - Out of Stock
   */
  status?: "active" | "inactive" | "out_of_stock";
  is_featured?: boolean;
  is_digital?: boolean;
  stock_quantity?: number;
  views_count?: number;
  sales_count?: number;
};

/**
 * Serializer for shop statistics.
 */
export type ShopStatsReadable = {
  total_products: number;
  active_products: number;
  out_of_stock_products: number;
  total_orders: number;
  pending_orders: number;
  total_revenue: string;
  popular_products: Array<ProductListReadable>;
  recent_orders: Array<OrderListReadable>;
};

/**
 * Serializer for shop statistics.
 */
export type ShopStatsWritable = {
  total_products: number;
  active_products: number;
  out_of_stock_products: number;
  total_orders: number;
  pending_orders: number;
  total_revenue: string;
  popular_products: Array<ProductListWritable>;
  recent_orders: Array<OrderListWritable>;
};

export type ShopCategoriesListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * Number of results to return per page.
     */
    page_size?: number;
    /**
     * A search term.
     */
    search?: string;
  };
  url: "/api/shop/categories/";
};

export type ShopCategoriesListResponses = {
  200: PaginatedCategoryListReadable;
};

export type ShopCategoriesListResponse =
  ShopCategoriesListResponses[keyof ShopCategoriesListResponses];

export type ShopCategoriesRetrieveData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: "/api/shop/categories/{slug}/";
};

export type ShopCategoriesRetrieveResponses = {
  200: CategoryReadable;
};

export type ShopCategoriesRetrieveResponse =
  ShopCategoriesRetrieveResponses[keyof ShopCategoriesRetrieveResponses];

export type ShopOrdersListData = {
  body?: never;
  path?: never;
  query?: {
    customer?: number;
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * Number of results to return per page.
     */
    page_size?: number;
    /**
     * A search term.
     */
    search?: string;
    /**
     * * `pending` - Pending
     * * `processing` - Processing
     * * `shipped` - Shipped
     * * `delivered` - Delivered
     * * `cancelled` - Cancelled
     * * `refunded` - Refunded
     */
    status?:
      | "cancelled"
      | "delivered"
      | "pending"
      | "processing"
      | "refunded"
      | "shipped";
  };
  url: "/api/shop/orders/";
};

export type ShopOrdersListResponses = {
  200: PaginatedOrderListListReadable;
};

export type ShopOrdersListResponse =
  ShopOrdersListResponses[keyof ShopOrdersListResponses];

export type ShopOrdersRetrieveData = {
  body?: never;
  path: {
    /**
     * A unique integer value identifying this Order.
     */
    id: number;
  };
  query?: never;
  url: "/api/shop/orders/{id}/";
};

export type ShopOrdersRetrieveResponses = {
  200: OrderDetailReadable;
};

export type ShopOrdersRetrieveResponse =
  ShopOrdersRetrieveResponses[keyof ShopOrdersRetrieveResponses];

export type ShopProductsListData = {
  body?: never;
  path?: never;
  query?: {
    category?: number;
    is_digital?: boolean;
    is_featured?: boolean;
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * Number of results to return per page.
     */
    page_size?: number;
    /**
     * A search term.
     */
    search?: string;
    /**
     * * `active` - Active
     * * `inactive` - Inactive
     * * `out_of_stock` - Out of Stock
     */
    status?: "active" | "inactive" | "out_of_stock";
  };
  url: "/api/shop/products/";
};

export type ShopProductsListResponses = {
  200: PaginatedProductListListReadable;
};

export type ShopProductsListResponse =
  ShopProductsListResponses[keyof ShopProductsListResponses];

export type ShopProductsRetrieveData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: "/api/shop/products/{slug}/";
};

export type ShopProductsRetrieveResponses = {
  200: ProductDetailReadable;
};

export type ShopProductsRetrieveResponse =
  ShopProductsRetrieveResponses[keyof ShopProductsRetrieveResponses];

export type ShopProductsFeaturedRetrieveData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/shop/products/featured/";
};

export type ShopProductsFeaturedRetrieveResponses = {
  200: ProductDetailReadable;
};

export type ShopProductsFeaturedRetrieveResponse =
  ShopProductsFeaturedRetrieveResponses[keyof ShopProductsFeaturedRetrieveResponses];

export type ShopProductsStatsRetrieveData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/shop/products/stats/";
};

export type ShopProductsStatsRetrieveResponses = {
  200: ShopStatsReadable;
};

export type ShopProductsStatsRetrieveResponse =
  ShopProductsStatsRetrieveResponses[keyof ShopProductsStatsRetrieveResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
