# Test Environment Configuration
# This file is for running tests

# === Core Django Settings ===
secret_key: "django-cfg-test-key-for-testing-only-this-is-long-enough-now-with-more-characters"
debug: true

# === Database ===
database:
  url: "sqlite:///:memory:"
  url_blog: "sqlite:///:memory:"
  url_shop: "sqlite:///:memory:"

# === Application URLs ===
app:
  name: "Django CFG Test"
  logo_url: "https://djangocfg.com/img/logo.png"
  domain: "testserver"
  api_url: "http://testserver"
  site_url: "http://testserver"

# === Security Domains ===
security_domains:
  - "localhost"
  - "127.0.0.1"
  - "djangocfg.com"

# === Email ===
email:
  backend: "locmem"
  host: "localhost"
  port: 587
  username: ""
  password: ""
  use_tls: false
  use_ssl: false
  default_from: "Test <test@example.com>"

# === Telegram Bot ===
telegram:
  bot_token: ""
  chat_id: 0

# === API Keys ===
api_keys:
  ngrok: ""
  cloudflare: ""
  openrouter: ""  # Set via OPENROUTER_API_KEY env var
  openai: ""      # Set via OPENAI_API_KEY env var
  sendgrid: ""    # Set via SENDGRID_API_KEY env var for email OTP

# === Payments API Keys ===
# For testing - use mock/test keys or empty for unit tests
payments_api_keys:
  nowpayments_api_key: "test-api-key"  # Mock key for testing
  nowpayments_ipn_secret: "test-ipn-secret"  # Mock secret for testing
  nowpayments_sandbox_mode: true  # Always sandbox for tests

# === Admin Configuration ===
admin_emails:
  - "test@example.com"

twilio:
  account_sid: ""  # Main Account SID
  auth_token: ""   # Main Auth Token
  whatsapp_from: ""  # WhatsApp sandbox number
  sms_from: ""       # Your SMS number
  sendgrid_api_key: ""    # SendGrid API key for email OTP
  verify_service_sid: ""  # Verify Service for OTP
  otp_template_id: "d-******"
  otp_from_email: ""  # SendGrid verified sender email

# === Cache ===
# redis_url: ""

# === Security ===
ssl_redirect: false
