// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  ApiNewsletterBulkCreateData,
  ApiNewsletterBulkCreateResponses,
  ApiNewsletterBulkCreateErrors,
  ApiNewsletterCampaignsListData,
  ApiNewsletterCampaignsListResponses,
  ApiNewsletterCampaignsCreateData,
  ApiNewsletterCampaignsCreateResponses,
  ApiNewsletterCampaignsDestroyData,
  ApiNewsletterCampaignsDestroyResponses,
  ApiNewsletterCampaignsRetrieveData,
  ApiNewsletterCampaignsRetrieveResponses,
  ApiNewsletterCampaignsPartialUpdateData,
  ApiNewsletterCampaignsPartialUpdateResponses,
  ApiNewsletterCampaignsUpdateData,
  ApiNewsletterCampaignsUpdateResponses,
  ApiNewsletterCampaignsSendCreateData,
  ApiNewsletterCampaignsSendCreateResponses,
  ApiNewsletterCampaignsSendCreateErrors,
  ApiNewsletterLogsListData,
  ApiNewsletterLogsListResponses,
  ApiNewsletterNewslettersListData,
  ApiNewsletterNewslettersListResponses,
  ApiNewsletterNewslettersRetrieveData,
  ApiNewsletterNewslettersRetrieveResponses,
  ApiNewsletterSubscribeCreateData,
  ApiNewsletterSubscribeCreateResponses,
  ApiNewsletterSubscribeCreateErrors,
  ApiNewsletterSubscriptionsListData,
  ApiNewsletterSubscriptionsListResponses,
  ApiNewsletterTestCreateData,
  ApiNewsletterTestCreateResponses,
  ApiNewsletterTestCreateErrors,
  ApiNewsletterUnsubscribePartialUpdateData,
  ApiNewsletterUnsubscribePartialUpdateResponses,
  ApiNewsletterUnsubscribeCreateData,
  ApiNewsletterUnsubscribeCreateResponses,
  ApiNewsletterUnsubscribeCreateErrors,
  ApiNewsletterUnsubscribeUpdateData,
  ApiNewsletterUnsubscribeUpdateResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Send Bulk Email
 * Send bulk emails to multiple recipients using base email template.
 */
export const apiNewsletterBulkCreate = <ThrowOnError extends boolean = false>(
  options: Options<ApiNewsletterBulkCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiNewsletterBulkCreateResponses,
    ApiNewsletterBulkCreateErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/bulk/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Newsletter Campaigns
 * Get a list of all newsletter campaigns.
 */
export const apiNewsletterCampaignsList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiNewsletterCampaignsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ApiNewsletterCampaignsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/campaigns/",
    ...options,
  });
};

/**
 * Create Newsletter Campaign
 * Create a new newsletter campaign.
 */
export const apiNewsletterCampaignsCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterCampaignsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiNewsletterCampaignsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/campaigns/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Campaign
 * Delete a newsletter campaign.
 */
export const apiNewsletterCampaignsDestroy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterCampaignsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    ApiNewsletterCampaignsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/campaigns/{id}/",
    ...options,
  });
};

/**
 * Get Campaign Details
 * Retrieve details of a specific newsletter campaign.
 */
export const apiNewsletterCampaignsRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterCampaignsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ApiNewsletterCampaignsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/campaigns/{id}/",
    ...options,
  });
};

/**
 * Retrieve, update, or delete a newsletter campaign.
 */
export const apiNewsletterCampaignsPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterCampaignsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    ApiNewsletterCampaignsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/campaigns/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Update Campaign
 * Update a newsletter campaign.
 */
export const apiNewsletterCampaignsUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterCampaignsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    ApiNewsletterCampaignsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/campaigns/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Send Newsletter Campaign
 * Send a newsletter campaign to all subscribers.
 */
export const apiNewsletterCampaignsSendCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterCampaignsSendCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiNewsletterCampaignsSendCreateResponses,
    ApiNewsletterCampaignsSendCreateErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/campaigns/send/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Email Logs
 * Get a list of email sending logs.
 */
export const apiNewsletterLogsList = <ThrowOnError extends boolean = false>(
  options?: Options<ApiNewsletterLogsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ApiNewsletterLogsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/logs/",
    ...options,
  });
};

/**
 * List Active Newsletters
 * Get a list of all active newsletters available for subscription.
 */
export const apiNewsletterNewslettersList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiNewsletterNewslettersListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ApiNewsletterNewslettersListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/newsletters/",
    ...options,
  });
};

/**
 * Get Newsletter Details
 * Retrieve details of a specific newsletter.
 */
export const apiNewsletterNewslettersRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterNewslettersRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ApiNewsletterNewslettersRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/newsletters/{id}/",
    ...options,
  });
};

/**
 * Subscribe to Newsletter
 * Subscribe an email address to a newsletter.
 */
export const apiNewsletterSubscribeCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterSubscribeCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiNewsletterSubscribeCreateResponses,
    ApiNewsletterSubscribeCreateErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/subscribe/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List User Subscriptions
 * Get a list of current user's active newsletter subscriptions.
 */
export const apiNewsletterSubscriptionsList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiNewsletterSubscriptionsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ApiNewsletterSubscriptionsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/subscriptions/",
    ...options,
  });
};

/**
 * Test Email Sending
 * Send a test email to verify mailer configuration.
 */
export const apiNewsletterTestCreate = <ThrowOnError extends boolean = false>(
  options: Options<ApiNewsletterTestCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiNewsletterTestCreateResponses,
    ApiNewsletterTestCreateErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/test/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Handle newsletter unsubscriptions.
 */
export const apiNewsletterUnsubscribePartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiNewsletterUnsubscribePartialUpdateData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).patch<
    ApiNewsletterUnsubscribePartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/unsubscribe/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Unsubscribe from Newsletter
 * Unsubscribe from a newsletter using subscription ID.
 */
export const apiNewsletterUnsubscribeCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterUnsubscribeCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiNewsletterUnsubscribeCreateResponses,
    ApiNewsletterUnsubscribeCreateErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/unsubscribe/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Handle newsletter unsubscriptions.
 */
export const apiNewsletterUnsubscribeUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiNewsletterUnsubscribeUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    ApiNewsletterUnsubscribeUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/newsletter/unsubscribe/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
