// This file is auto-generated by @hey-api/openapi-ts

/**
 * Simple serializer for bulk email.
 */
export type BulkEmailRequest = {
  recipients: Array<string>;
  subject: string;
  email_title: string;
  main_text: string;
  main_html_content?: string;
  button_text?: string;
  button_url?: string;
  secondary_text?: string;
};

/**
 * Serializer for EmailLog model.
 */
export type EmailLog = {
  readonly id: number;
  /**
   * User Account
   */
  readonly user: number | null;
  readonly user_email: string;
  /**
   * Related Newsletter
   */
  readonly newsletter: number | null;
  readonly newsletter_title: string;
  /**
   * Recipient(s)
   * Comma-separated email addresses
   */
  readonly recipient: string;
  readonly subject: string;
  /**
   * Body (HTML)
   */
  readonly body: string;
  status: EmailLogStatusEnum;
  readonly created_at: string;
  readonly sent_at: string | null;
  readonly error_message: string | null;
};

/**
 * * `pending` - Pending
 * * `sent` - Sent
 * * `failed` - Failed
 */
export type EmailLogStatusEnum = "pending" | "sent" | "failed";

/**
 * Serializer for Newsletter model.
 */
export type Newsletter = {
  readonly id: number;
  /**
   * Newsletter Title
   */
  title: string;
  description?: string;
  /**
   * Active
   */
  is_active?: boolean;
  /**
   * Auto Subscribe New Users
   * Automatically subscribe new users to this newsletter
   */
  auto_subscribe?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  readonly subscribers_count: string;
};

/**
 * Serializer for NewsletterCampaign model.
 */
export type NewsletterCampaign = {
  readonly id: number;
  newsletter: number;
  readonly newsletter_title: string;
  subject: string;
  email_title: string;
  main_text: string;
  /**
   * HTML Content
   */
  main_html_content?: string;
  button_text?: string;
  button_url?: string;
  secondary_text?: string;
  status: NewsletterCampaignStatusEnum;
  readonly created_at: string;
  readonly sent_at: string | null;
  readonly recipient_count: number;
};

/**
 * Serializer for NewsletterCampaign model.
 */
export type NewsletterCampaignRequest = {
  newsletter: number;
  subject: string;
  email_title: string;
  main_text: string;
  /**
   * HTML Content
   */
  main_html_content?: string;
  button_text?: string;
  button_url?: string;
  secondary_text?: string;
};

/**
 * * `draft` - Draft
 * * `sending` - Sending
 * * `sent` - Sent
 * * `failed` - Failed
 */
export type NewsletterCampaignStatusEnum =
  | "draft"
  | "sending"
  | "sent"
  | "failed";

/**
 * Serializer for NewsletterSubscription model.
 */
export type NewsletterSubscription = {
  readonly id: number;
  newsletter: number;
  readonly newsletter_title: string;
  user?: number | null;
  readonly user_email: string;
  /**
   * Email Address
   */
  email: string;
  /**
   * Active
   */
  is_active?: boolean;
  readonly subscribed_at: string;
  readonly unsubscribed_at: string | null;
};

export type PaginatedEmailLogList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<EmailLog>;
};

export type PaginatedNewsletterCampaignList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<NewsletterCampaign>;
};

export type PaginatedNewsletterList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Newsletter>;
};

export type PaginatedNewsletterSubscriptionList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<NewsletterSubscription>;
};

/**
 * Serializer for NewsletterCampaign model.
 */
export type PatchedNewsletterCampaignRequest = {
  newsletter?: number;
  subject?: string;
  email_title?: string;
  main_text?: string;
  /**
   * HTML Content
   */
  main_html_content?: string;
  button_text?: string;
  button_url?: string;
  secondary_text?: string;
};

/**
 * Simple serializer for unsubscribe.
 */
export type PatchedUnsubscribeRequest = {
  subscription_id?: number;
};

/**
 * Simple serializer for sending campaign.
 */
export type SendCampaignRequest = {
  campaign_id: number;
};

/**
 * Simple serializer for newsletter subscription.
 */
export type SubscribeRequest = {
  newsletter_id: number;
  email: string;
};

/**
 * Simple serializer for test email.
 */
export type TestEmailRequest = {
  email: string;
  subject?: string;
  message?: string;
};

/**
 * Simple serializer for unsubscribe.
 */
export type Unsubscribe = {
  subscription_id: number;
};

/**
 * Simple serializer for unsubscribe.
 */
export type UnsubscribeRequest = {
  subscription_id: number;
};

export type ApiNewsletterBulkCreateData = {
  body: BulkEmailRequest;
  path?: never;
  query?: never;
  url: "/api/newsletter/bulk/";
};

export type ApiNewsletterBulkCreateErrors = {
  /**
   * Unspecified response body
   */
  400: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterBulkCreateError =
  ApiNewsletterBulkCreateErrors[keyof ApiNewsletterBulkCreateErrors];

export type ApiNewsletterBulkCreateResponses = {
  /**
   * Unspecified response body
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterBulkCreateResponse =
  ApiNewsletterBulkCreateResponses[keyof ApiNewsletterBulkCreateResponses];

export type ApiNewsletterCampaignsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * A search term.
     */
    search?: string;
  };
  url: "/api/newsletter/campaigns/";
};

export type ApiNewsletterCampaignsListResponses = {
  200: PaginatedNewsletterCampaignList;
};

export type ApiNewsletterCampaignsListResponse =
  ApiNewsletterCampaignsListResponses[keyof ApiNewsletterCampaignsListResponses];

export type ApiNewsletterCampaignsCreateData = {
  body: NewsletterCampaignRequest;
  path?: never;
  query?: never;
  url: "/api/newsletter/campaigns/";
};

export type ApiNewsletterCampaignsCreateResponses = {
  201: NewsletterCampaign;
};

export type ApiNewsletterCampaignsCreateResponse =
  ApiNewsletterCampaignsCreateResponses[keyof ApiNewsletterCampaignsCreateResponses];

export type ApiNewsletterCampaignsDestroyData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/newsletter/campaigns/{id}/";
};

export type ApiNewsletterCampaignsDestroyResponses = {
  /**
   * Unspecified response body
   */
  204: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterCampaignsDestroyResponse =
  ApiNewsletterCampaignsDestroyResponses[keyof ApiNewsletterCampaignsDestroyResponses];

export type ApiNewsletterCampaignsRetrieveData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/newsletter/campaigns/{id}/";
};

export type ApiNewsletterCampaignsRetrieveResponses = {
  200: NewsletterCampaign;
};

export type ApiNewsletterCampaignsRetrieveResponse =
  ApiNewsletterCampaignsRetrieveResponses[keyof ApiNewsletterCampaignsRetrieveResponses];

export type ApiNewsletterCampaignsPartialUpdateData = {
  body?: PatchedNewsletterCampaignRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/newsletter/campaigns/{id}/";
};

export type ApiNewsletterCampaignsPartialUpdateResponses = {
  200: NewsletterCampaign;
};

export type ApiNewsletterCampaignsPartialUpdateResponse =
  ApiNewsletterCampaignsPartialUpdateResponses[keyof ApiNewsletterCampaignsPartialUpdateResponses];

export type ApiNewsletterCampaignsUpdateData = {
  body: NewsletterCampaignRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/newsletter/campaigns/{id}/";
};

export type ApiNewsletterCampaignsUpdateResponses = {
  200: NewsletterCampaign;
};

export type ApiNewsletterCampaignsUpdateResponse =
  ApiNewsletterCampaignsUpdateResponses[keyof ApiNewsletterCampaignsUpdateResponses];

export type ApiNewsletterCampaignsSendCreateData = {
  body: SendCampaignRequest;
  path?: never;
  query?: never;
  url: "/api/newsletter/campaigns/send/";
};

export type ApiNewsletterCampaignsSendCreateErrors = {
  /**
   * Unspecified response body
   */
  400: {
    [key: string]: unknown;
  };
  /**
   * Unspecified response body
   */
  404: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterCampaignsSendCreateError =
  ApiNewsletterCampaignsSendCreateErrors[keyof ApiNewsletterCampaignsSendCreateErrors];

export type ApiNewsletterCampaignsSendCreateResponses = {
  /**
   * Unspecified response body
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterCampaignsSendCreateResponse =
  ApiNewsletterCampaignsSendCreateResponses[keyof ApiNewsletterCampaignsSendCreateResponses];

export type ApiNewsletterLogsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * A search term.
     */
    search?: string;
  };
  url: "/api/newsletter/logs/";
};

export type ApiNewsletterLogsListResponses = {
  200: PaginatedEmailLogList;
};

export type ApiNewsletterLogsListResponse =
  ApiNewsletterLogsListResponses[keyof ApiNewsletterLogsListResponses];

export type ApiNewsletterNewslettersListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * A search term.
     */
    search?: string;
  };
  url: "/api/newsletter/newsletters/";
};

export type ApiNewsletterNewslettersListResponses = {
  200: PaginatedNewsletterList;
};

export type ApiNewsletterNewslettersListResponse =
  ApiNewsletterNewslettersListResponses[keyof ApiNewsletterNewslettersListResponses];

export type ApiNewsletterNewslettersRetrieveData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/newsletter/newsletters/{id}/";
};

export type ApiNewsletterNewslettersRetrieveResponses = {
  200: Newsletter;
};

export type ApiNewsletterNewslettersRetrieveResponse =
  ApiNewsletterNewslettersRetrieveResponses[keyof ApiNewsletterNewslettersRetrieveResponses];

export type ApiNewsletterSubscribeCreateData = {
  body: SubscribeRequest;
  path?: never;
  query?: never;
  url: "/api/newsletter/subscribe/";
};

export type ApiNewsletterSubscribeCreateErrors = {
  /**
   * Unspecified response body
   */
  400: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterSubscribeCreateError =
  ApiNewsletterSubscribeCreateErrors[keyof ApiNewsletterSubscribeCreateErrors];

export type ApiNewsletterSubscribeCreateResponses = {
  /**
   * Unspecified response body
   */
  201: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterSubscribeCreateResponse =
  ApiNewsletterSubscribeCreateResponses[keyof ApiNewsletterSubscribeCreateResponses];

export type ApiNewsletterSubscriptionsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * A search term.
     */
    search?: string;
  };
  url: "/api/newsletter/subscriptions/";
};

export type ApiNewsletterSubscriptionsListResponses = {
  200: PaginatedNewsletterSubscriptionList;
};

export type ApiNewsletterSubscriptionsListResponse =
  ApiNewsletterSubscriptionsListResponses[keyof ApiNewsletterSubscriptionsListResponses];

export type ApiNewsletterTestCreateData = {
  body: TestEmailRequest;
  path?: never;
  query?: never;
  url: "/api/newsletter/test/";
};

export type ApiNewsletterTestCreateErrors = {
  /**
   * Unspecified response body
   */
  400: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterTestCreateError =
  ApiNewsletterTestCreateErrors[keyof ApiNewsletterTestCreateErrors];

export type ApiNewsletterTestCreateResponses = {
  /**
   * Unspecified response body
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterTestCreateResponse =
  ApiNewsletterTestCreateResponses[keyof ApiNewsletterTestCreateResponses];

export type ApiNewsletterUnsubscribePartialUpdateData = {
  body?: PatchedUnsubscribeRequest;
  path?: never;
  query?: never;
  url: "/api/newsletter/unsubscribe/";
};

export type ApiNewsletterUnsubscribePartialUpdateResponses = {
  200: Unsubscribe;
};

export type ApiNewsletterUnsubscribePartialUpdateResponse =
  ApiNewsletterUnsubscribePartialUpdateResponses[keyof ApiNewsletterUnsubscribePartialUpdateResponses];

export type ApiNewsletterUnsubscribeCreateData = {
  body: UnsubscribeRequest;
  path?: never;
  query?: never;
  url: "/api/newsletter/unsubscribe/";
};

export type ApiNewsletterUnsubscribeCreateErrors = {
  /**
   * Unspecified response body
   */
  404: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterUnsubscribeCreateError =
  ApiNewsletterUnsubscribeCreateErrors[keyof ApiNewsletterUnsubscribeCreateErrors];

export type ApiNewsletterUnsubscribeCreateResponses = {
  /**
   * Unspecified response body
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiNewsletterUnsubscribeCreateResponse =
  ApiNewsletterUnsubscribeCreateResponses[keyof ApiNewsletterUnsubscribeCreateResponses];

export type ApiNewsletterUnsubscribeUpdateData = {
  body: UnsubscribeRequest;
  path?: never;
  query?: never;
  url: "/api/newsletter/unsubscribe/";
};

export type ApiNewsletterUnsubscribeUpdateResponses = {
  200: Unsubscribe;
};

export type ApiNewsletterUnsubscribeUpdateResponse =
  ApiNewsletterUnsubscribeUpdateResponses[keyof ApiNewsletterUnsubscribeUpdateResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
