// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.011267

package crypto

import (
	"net/http"
	"crypto/crypto__api__crypto"
)

// Client is the main API client with sub-clients for each module.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	Token      string

	// CryptoAPICrypto provides access to CryptoAPICrypto operations
	CryptoAPICrypto *crypto__api__crypto.Client
}

// NewClient creates a new API client.
func NewClient(baseURL string, options ...Option) *Client {
	client := &Client{
		BaseURL:    baseURL,
		HTTPClient: &http.Client{},
	}

	// Apply options
	for _, opt := range options {
		opt(client)
	}

	// Initialize sub-clients
	client.CryptoAPICrypto = crypto__api__crypto.NewClient(baseURL, client.HTTPClient, client.Token)

	return client
}

// Option is a functional option for configuring the Client.
type Option func(*Client)

// WithHTTPClient sets a custom HTTP client.
func WithHTTPClient(httpClient *http.Client) Option {
	return func(c *Client) {
		c.HTTPClient = httpClient
	}
}

// WithToken sets the authentication token.
func WithToken(token string) Option {
	return func(c *Client) {
		c.Token = token
	}
}