# Generated by Django 5.2.9 on 2025-12-04 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Session display name", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Current session status",
                        max_length=20,
                    ),
                ),
                (
                    "electron_hostname",
                    models.CharField(
                        blank=True,
                        help_text="Connected Electron client hostname",
                        max_length=255,
                    ),
                ),
                (
                    "electron_version",
                    models.CharField(
                        blank=True, help_text="Electron client version", max_length=50
                    ),
                ),
                (
                    "working_directory",
                    models.CharField(
                        default="~",
                        help_text="Current working directory in terminal",
                        max_length=500,
                    ),
                ),
                (
                    "shell",
                    models.CharField(
                        default="/bin/zsh",
                        help_text="Shell to use (e.g., /bin/bash, /bin/zsh)",
                        max_length=100,
                    ),
                ),
                (
                    "environment",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Environment variables for the session",
                    ),
                ),
                (
                    "commands_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total commands executed in this session"
                    ),
                ),
                (
                    "bytes_sent",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Total bytes sent to terminal"
                    ),
                ),
                (
                    "bytes_received",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Total bytes received from terminal"
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When Electron client connected",
                        null=True,
                    ),
                ),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(
                        blank=True, help_text="Last heartbeat from Electron", null=True
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, help_text="When session was disconnected", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Session owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Terminal Session",
                "verbose_name_plural": "Terminal Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommandHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command", models.TextField(help_text="Executed command")),
                (
                    "working_directory",
                    models.CharField(
                        blank=True,
                        help_text="Working directory when command was executed",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        help_text="Command execution status",
                        max_length=20,
                    ),
                ),
                ("stdout", models.TextField(blank=True, help_text="Standard output")),
                ("stderr", models.TextField(blank=True, help_text="Standard error")),
                (
                    "exit_code",
                    models.IntegerField(
                        blank=True, help_text="Process exit code", null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When command started executing",
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="When command finished", null=True
                    ),
                ),
                (
                    "bytes_in",
                    models.PositiveIntegerField(
                        default=0, help_text="Bytes sent to process (stdin)"
                    ),
                ),
                (
                    "bytes_out",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Bytes received from process (stdout+stderr)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Terminal session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="terminal.terminalsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Command History",
                "verbose_name_plural": "Command History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="terminalsession",
            index=models.Index(
                fields=["user", "status"], name="terminal_te_user_id_74756b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="terminalsession",
            index=models.Index(fields=["status"], name="terminal_te_status_5fa5a8_idx"),
        ),
        migrations.AddIndex(
            model_name="terminalsession",
            index=models.Index(
                fields=["-created_at"], name="terminal_te_created_923cf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commandhistory",
            index=models.Index(
                fields=["session", "-created_at"], name="terminal_co_session_c8e61c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commandhistory",
            index=models.Index(fields=["status"], name="terminal_co_status_27e1b3_idx"),
        ),
    ]
