# Generated by Django 5.2.9 on 2025-12-04 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminalsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Session owner (null for auto-created sessions)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminal_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
