# Generated by Django 5.2.7 on 2025-10-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskLog",
        ),
    ]
