// This file is auto-generated by @hey-api/openapi-ts

/**
 * Error response for OTP operations.
 */
export type OtpErrorResponse = {
  /**
   * Error message
   */
  error: string;
};

/**
 * Serializer for OTP request.
 */
export type OtpRequestRequest = {
  email: string;
  /**
   * Source URL for tracking registration (e.g., https://dashboard.unrealon.com)
   */
  source_url?: string;
};

/**
 * OTP request response.
 */
export type OtpRequestResponse = {
  /**
   * Success message
   */
  message: string;
};

/**
 * Serializer for OTP verification.
 */
export type OtpVerifyRequest = {
  email: string;
  otp: string;
  /**
   * Source URL for tracking login (e.g., https://dashboard.unrealon.com)
   */
  source_url?: string;
};

/**
 * OTP verification response.
 */
export type OtpVerifyResponse = {
  /**
   * JWT refresh token
   */
  refresh: string;
  /**
   * JWT access token
   */
  access: string;
  /**
   * User information
   */
  user: User;
};

/**
 * Serializer for updating user profile.
 */
export type PatchedUserProfileUpdateRequest = {
  first_name?: string;
  last_name?: string;
  company?: string;
  phone?: string;
  position?: string;
};

export type TokenRefresh = {
  readonly access: string;
  refresh: string;
};

export type TokenRefreshRequest = {
  refresh: string;
};

/**
 * Serializer for user details.
 */
export type User = {
  readonly id: number;
  readonly email: string;
  first_name?: string;
  last_name?: string;
  /**
   * Get user's full name.
   */
  readonly full_name: string;
  /**
   * Get user's initials for avatar fallback.
   */
  readonly initials: string;
  /**
   * Get formatted username for display.
   */
  readonly display_username: string;
  company?: string;
  phone?: string;
  position?: string;
  avatar?: string | null;
  /**
   * Staff status
   * Designates whether the user can log into this admin site.
   */
  readonly is_staff: boolean;
  /**
   * Superuser status
   * Designates that this user has all permissions without explicitly assigning them.
   */
  readonly is_superuser: boolean;
  readonly date_joined: string;
  readonly last_login: string | null;
  /**
   * Get count of unanswered messages for the user.
   */
  readonly unanswered_messages_count: number;
};

/**
 * Serializer for updating user profile.
 */
export type UserProfileUpdateRequest = {
  first_name?: string;
  last_name?: string;
  company?: string;
  phone?: string;
  position?: string;
};

export type ApiAccountsOtpRequestCreateData = {
  body: OtpRequestRequest;
  path?: never;
  query?: never;
  url: "/api/accounts/otp/request/";
};

export type ApiAccountsOtpRequestCreateErrors = {
  400: OtpErrorResponse;
  500: OtpErrorResponse;
};

export type ApiAccountsOtpRequestCreateError =
  ApiAccountsOtpRequestCreateErrors[keyof ApiAccountsOtpRequestCreateErrors];

export type ApiAccountsOtpRequestCreateResponses = {
  200: OtpRequestResponse;
};

export type ApiAccountsOtpRequestCreateResponse =
  ApiAccountsOtpRequestCreateResponses[keyof ApiAccountsOtpRequestCreateResponses];

export type ApiAccountsOtpVerifyCreateData = {
  body: OtpVerifyRequest;
  path?: never;
  query?: never;
  url: "/api/accounts/otp/verify/";
};

export type ApiAccountsOtpVerifyCreateErrors = {
  400: OtpErrorResponse;
  410: OtpErrorResponse;
};

export type ApiAccountsOtpVerifyCreateError =
  ApiAccountsOtpVerifyCreateErrors[keyof ApiAccountsOtpVerifyCreateErrors];

export type ApiAccountsOtpVerifyCreateResponses = {
  200: OtpVerifyResponse;
};

export type ApiAccountsOtpVerifyCreateResponse =
  ApiAccountsOtpVerifyCreateResponses[keyof ApiAccountsOtpVerifyCreateResponses];

export type ApiAccountsProfileRetrieveData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/accounts/profile/";
};

export type ApiAccountsProfileRetrieveErrors = {
  /**
   * Authentication credentials were not provided.
   */
  401: unknown;
};

export type ApiAccountsProfileRetrieveResponses = {
  200: User;
};

export type ApiAccountsProfileRetrieveResponse =
  ApiAccountsProfileRetrieveResponses[keyof ApiAccountsProfileRetrieveResponses];

export type ApiAccountsProfileAvatarCreateData = {
  body?: {
    /**
     * Avatar image file (JPEG, PNG, GIF, WebP, max 5MB)
     */
    avatar: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/api/accounts/profile/avatar/";
};

export type ApiAccountsProfileAvatarCreateErrors = {
  /**
   * Invalid file or validation error.
   */
  400: unknown;
  /**
   * Authentication credentials were not provided.
   */
  401: unknown;
};

export type ApiAccountsProfileAvatarCreateResponses = {
  200: User;
};

export type ApiAccountsProfileAvatarCreateResponse =
  ApiAccountsProfileAvatarCreateResponses[keyof ApiAccountsProfileAvatarCreateResponses];

export type ApiAccountsProfilePartialPartialUpdateData = {
  body?: PatchedUserProfileUpdateRequest;
  path?: never;
  query?: never;
  url: "/api/accounts/profile/partial/";
};

export type ApiAccountsProfilePartialPartialUpdateErrors = {
  /**
   * Invalid data provided.
   */
  400: unknown;
  /**
   * Authentication credentials were not provided.
   */
  401: unknown;
};

export type ApiAccountsProfilePartialPartialUpdateResponses = {
  200: User;
};

export type ApiAccountsProfilePartialPartialUpdateResponse =
  ApiAccountsProfilePartialPartialUpdateResponses[keyof ApiAccountsProfilePartialPartialUpdateResponses];

export type ApiAccountsProfilePartialUpdateData = {
  body?: UserProfileUpdateRequest;
  path?: never;
  query?: never;
  url: "/api/accounts/profile/partial/";
};

export type ApiAccountsProfilePartialUpdateErrors = {
  /**
   * Invalid data provided.
   */
  400: unknown;
  /**
   * Authentication credentials were not provided.
   */
  401: unknown;
};

export type ApiAccountsProfilePartialUpdateResponses = {
  200: User;
};

export type ApiAccountsProfilePartialUpdateResponse =
  ApiAccountsProfilePartialUpdateResponses[keyof ApiAccountsProfilePartialUpdateResponses];

export type ApiAccountsProfileUpdatePartialUpdateData = {
  body?: PatchedUserProfileUpdateRequest;
  path?: never;
  query?: never;
  url: "/api/accounts/profile/update/";
};

export type ApiAccountsProfileUpdatePartialUpdateErrors = {
  /**
   * Invalid data provided.
   */
  400: unknown;
  /**
   * Authentication credentials were not provided.
   */
  401: unknown;
};

export type ApiAccountsProfileUpdatePartialUpdateResponses = {
  200: User;
};

export type ApiAccountsProfileUpdatePartialUpdateResponse =
  ApiAccountsProfileUpdatePartialUpdateResponses[keyof ApiAccountsProfileUpdatePartialUpdateResponses];

export type ApiAccountsProfileUpdateUpdateData = {
  body?: UserProfileUpdateRequest;
  path?: never;
  query?: never;
  url: "/api/accounts/profile/update/";
};

export type ApiAccountsProfileUpdateUpdateErrors = {
  /**
   * Invalid data provided.
   */
  400: unknown;
  /**
   * Authentication credentials were not provided.
   */
  401: unknown;
};

export type ApiAccountsProfileUpdateUpdateResponses = {
  200: User;
};

export type ApiAccountsProfileUpdateUpdateResponse =
  ApiAccountsProfileUpdateUpdateResponses[keyof ApiAccountsProfileUpdateUpdateResponses];

export type ApiAccountsTokenRefreshCreateData = {
  body: TokenRefreshRequest;
  path?: never;
  query?: never;
  url: "/api/accounts/token/refresh/";
};

export type ApiAccountsTokenRefreshCreateResponses = {
  200: TokenRefresh;
};

export type ApiAccountsTokenRefreshCreateResponse =
  ApiAccountsTokenRefreshCreateResponses[keyof ApiAccountsTokenRefreshCreateResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
