# Generated by Django 5.2.12 on 2026-03-13 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        help_text="UUID assigned by the browser client (stored in localStorage/cookie)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Client IP address at the time of first event"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", help_text="Browser User-Agent string"),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Optional browser fingerprint hash (computed client-side)",
                        max_length=64,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Last time an event was received from this session",
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this anonymous session was linked to a user",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user this session was matched to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anonymous_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Session",
                "verbose_name_plural": "Anonymous Sessions",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="FrontendEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ERROR", "Error"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                            ("PAGE_VIEW", "Page View"),
                            ("PERFORMANCE", "Performance"),
                            ("NETWORK_ERROR", "Network Error"),
                            ("JS_ERROR", "JS Error"),
                            ("CONSOLE", "Console"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warn", "Warning"),
                            ("info", "Info"),
                            ("debug", "Debug"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "stack_trace",
                    models.TextField(
                        blank=True, default="", help_text="Full stack trace for JS errors"
                    ),
                ),
                (
                    "url",
                    models.TextField(
                        blank=True, default="", help_text="Page URL where the event occurred"
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="HTTP status code of the failed request", null=True
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTTP method of the failed request",
                        max_length=10,
                    ),
                ),
                (
                    "http_url",
                    models.TextField(
                        blank=True, default="", help_text="URL of the failed API call"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "device_type",
                    models.CharField(
                        blank=True, default="", help_text="mobile / tablet / desktop", max_length=10
                    ),
                ),
                ("os", models.CharField(blank=True, default="", max_length=50)),
                ("browser", models.CharField(blank=True, default="", max_length=50)),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client-generated hash for deduplication (e.g. sha256 of message+stack+url)",
                        max_length=64,
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True, default=dict, help_text="Arbitrary extra data from the client"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Frontend project name (useful when multiple frontends share one backend)",
                        max_length=100,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="production / staging / development",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "anonymous_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="django_cfg_frontend_monitor.anonymoussession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user (null for anonymous visitors)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frontend_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Frontend Event",
                "verbose_name_plural": "Frontend Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="anonymoussession",
            index=models.Index(
                fields=["ip_address", "last_seen"], name="django_cfg__ip_addr_d1ef53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frontendevent",
            index=models.Index(
                fields=["fingerprint", "url", "created_at"], name="django_cfg__fingerp_9b8f8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frontendevent",
            index=models.Index(
                fields=["ip_address", "event_type", "created_at"],
                name="django_cfg__ip_addr_3dca5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="frontendevent",
            index=models.Index(
                fields=["anonymous_session", "created_at"], name="django_cfg__anonymo_f8e5cd_idx"
            ),
        ),
    ]
