client_class_name: Cfg_PaymentsClient
follow_redirects: true
generate_aliases: true
http_timeout: 30
literal_enums: true
package_name_override: django_revolution_cfg_payments
post_hooks: []
project_name_override: django_revolution_cfg_payments
use_pydantic_v2: true
use_string_enums: false
