# Generated by Django 5.2.7 on 2025-10-13 05:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total portfolio value in USD', max_digits=20)),
                ('available_balance_usd', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Available balance for trading', max_digits=20)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Trading pair (e.g., BTC/USDT)', max_length=20)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop_loss', 'Stop Loss')], default='market', max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.portfolio')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
