// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.685527

package cfg__dashboard__dashboard_commands


// Django management command serializer.
type Command struct {
	Name string `json:"name"`
	App string `json:"app"`
	Help string `json:"help"`
	IsCore bool `json:"is_core"`
	IsCustom bool `json:"is_custom"`
}

// Commands summary serializer.
type CommandsSummary struct {
	TotalCommands int64 `json:"total_commands"`
	CoreCommands int64 `json:"core_commands"`
	CustomCommands int64 `json:"custom_commands"`
	Categories []string `json:"categories"`
	Commands []Command `json:"commands"`
	Categorized map[string]interface{} `json:"categorized"`
}

