// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.509430

package cfg__dashboard__dashboard_commands


// Django management command serializer.
type Command struct {
	Name string `json:"name"`
	App string `json:"app"`
	Help string `json:"help"`
	IsCore bool `json:"is_core"`
	IsCustom bool `json:"is_custom"`
	IsAllowed *bool `json:"is_allowed,omitempty"`
	RiskLevel *string `json:"risk_level,omitempty"`
}

// Request serializer for command execution.
type CommandExecuteRequestRequest struct {
	// Name of the Django management command
	Command string `json:"command"`
	// Positional arguments for the command
	Args []string `json:"args,omitempty"`
	// Named options for the command (e.g., {'verbosity': '2'})
	Options map[string]interface{} `json:"options,omitempty"`
}

// Response serializer for command help.
type CommandHelpResponse struct {
	Status string `json:"status"`
	Command string `json:"command"`
	App *string `json:"app,omitempty"`
	HelpText *string `json:"help_text,omitempty"`
	IsAllowed *bool `json:"is_allowed,omitempty"`
	RiskLevel *string `json:"risk_level,omitempty"`
	Error *string `json:"error,omitempty"`
}

// Commands summary serializer.
type CommandsSummary struct {
	TotalCommands int64 `json:"total_commands"`
	CoreCommands int64 `json:"core_commands"`
	CustomCommands int64 `json:"custom_commands"`
	Categories []string `json:"categories"`
	Commands []Command `json:"commands"`
	Categorized map[string]interface{} `json:"categorized"`
}

