"""Zod validation-events TS template (static)."""

VALIDATION_EVENTS_TS = '''\
// AUTO-GENERATED by django_generator / ts_extras.wrapper
// Browser CustomEvent integration for Zod validation errors.
// DO NOT EDIT — re-run `make gen`.

import type { ZodError } from "zod";

export interface ValidationErrorDetail {
  operation: string;
  path: string;
  method: string;
  error: ZodError;
  response: any;
  timestamp: Date;
}

export type ValidationErrorEvent = CustomEvent<ValidationErrorDetail>;

export function dispatchValidationError(detail: ValidationErrorDetail): void {
  if (typeof window === "undefined") return;
  try {
    const event = new CustomEvent<ValidationErrorDetail>("zod-validation-error", {
      detail,
      bubbles: true,
      cancelable: false,
    });
    window.dispatchEvent(event);
  } catch (error) {
    console.warn("Failed to dispatch validation error event:", error);
  }
}

export function onValidationError(
  callback: (detail: ValidationErrorDetail) => void,
): () => void {
  if (typeof window === "undefined") return () => {};
  const handler = (event: Event) => {
    if (event instanceof CustomEvent) callback(event.detail);
  };
  window.addEventListener("zod-validation-error", handler);
  return () => window.removeEventListener("zod-validation-error", handler);
}

export function formatZodError(error: ZodError): string {
  const issues = error.issues.map((issue, index) => {
    const path = issue.path.join(".") || "root";
    const parts = [`${index + 1}. ${path}: ${issue.message}`];
    if ("expected" in issue && issue.expected) parts.push(`   Expected: ${issue.expected}`);
    if ("received" in issue && issue.received) parts.push(`   Received: ${issue.received}`);
    return parts.join("\\n");
  });
  return issues.join("\\n");
}
'''
