# Generated by Django 5.2.13 on 2026-04-17 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MCPAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("tool_name", models.CharField(db_index=True, max_length=50)),
                ("sql_preview", models.TextField(blank=True, help_text="First 500 chars of SQL")),
                ("params_preview", models.JSONField(blank=True, default=dict)),
                ("cost", models.FloatField(default=0, help_text="EXPLAIN total cost")),
                ("rows_returned", models.IntegerField(default=0)),
                ("execution_ms", models.FloatField(default=0)),
                (
                    "scan_type",
                    models.CharField(
                        blank=True, help_text="sequential, index, bitmap", max_length=20
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-created_at"], name="django_cfg__session_7b45e2_idx"
                    ),
                    models.Index(
                        fields=["tool_name", "-created_at"], name="django_cfg__tool_na_ea27e0_idx"
                    ),
                    models.Index(fields=["-created_at"], name="django_cfg__created_ef4a34_idx"),
                ],
            },
        ),
    ]
