// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.549230

package cfg__payments

import (
	"cfg/types"
	"time"
)

// User balance serializer.
type Balance struct {
	// Current balance in USD
	BalanceUsd string `json:"balance_usd"`
	BalanceDisplay string `json:"balance_display"`
	// Total amount deposited (lifetime)
	TotalDeposited string `json:"total_deposited"`
	// Total amount withdrawn (lifetime)
	TotalWithdrawn string `json:"total_withdrawn"`
	// When the last transaction occurred
	LastTransactionAt time.Time `json:"last_transaction_at"`
}

// PaginatedPaymentListList model.
type PaginatedPaymentListList struct {
	// Total number of items across all pages
	Count int64 `json:"count"`
	// Current page number (1-based)
	Page int64 `json:"page"`
	// Total number of pages
	Pages int64 `json:"pages"`
	// Number of items per page
	PageSize int64 `json:"page_size"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool `json:"has_previous"`
	// Next page number (null if no next page)
	NextPage *int64 `json:"next_page,omitempty"`
	// Previous page number (null if no previous page)
	PreviousPage *int64 `json:"previous_page,omitempty"`
	// Array of items for current page
	Results []PaymentList `json:"results"`
}

// Detailed payment information.
type PaymentDetail struct {
	// Unique identifier for this record
	ID string `json:"id"`
	// Internal payment identifier (PAY_YYYYMMDDHHMMSS_UUID)
	InternalPaymentID string `json:"internal_payment_id"`
	// Payment amount in USD
	AmountUsd string `json:"amount_usd"`
	CurrencyCode string `json:"currency_code"`
	CurrencyName string `json:"currency_name"`
	CurrencyToken string `json:"currency_token"`
	CurrencyNetwork string `json:"currency_network"`
	// Amount to pay in cryptocurrency
	PayAmount string `json:"pay_amount"`
	// Actual amount received in cryptocurrency
	ActualAmount string `json:"actual_amount"`
	// Actual amount received in USD
	ActualAmountUsd string `json:"actual_amount_usd"`
	// Current payment status
	// 
	// * `pending` - Pending
	// * `confirming` - Confirming
	// * `confirmed` - Confirmed
	// * `completed` - Completed
	// * `partially_paid` - Partially Paid
	// * `failed` - Failed
	// * `expired` - Expired
	// * `cancelled` - Cancelled
	Status types.PaymentdetailStatus `json:"status"`
	StatusDisplay string `json:"status_display"`
	// Cryptocurrency payment address
	PayAddress string `json:"pay_address"`
	// Get QR code URL.
	QrCodeURL string `json:"qr_code_url"`
	// Payment page URL (if provided by provider)
	PaymentURL string `json:"payment_url"`
	// Blockchain transaction hash
	TransactionHash string `json:"transaction_hash"`
	// Get blockchain explorer link.
	ExplorerLink string `json:"explorer_link"`
	// Number of blockchain confirmations
	ConfirmationsCount int64 `json:"confirmations_count"`
	// When this payment expires (typically 30 minutes)
	ExpiresAt time.Time `json:"expires_at"`
	// When this payment was completed
	CompletedAt time.Time `json:"completed_at"`
	// When this record was created
	CreatedAt time.Time `json:"created_at"`
	IsCompleted bool `json:"is_completed"`
	IsFailed bool `json:"is_failed"`
	IsExpired bool `json:"is_expired"`
	// Payment description
	Description string `json:"description"`
}

// Payment list item (lighter than detail).
type PaymentList struct {
	// Unique identifier for this record
	ID string `json:"id"`
	// Internal payment identifier (PAY_YYYYMMDDHHMMSS_UUID)
	InternalPaymentID string `json:"internal_payment_id"`
	// Payment amount in USD
	AmountUsd string `json:"amount_usd"`
	CurrencyCode string `json:"currency_code"`
	CurrencyToken string `json:"currency_token"`
	// Current payment status
	// 
	// * `pending` - Pending
	// * `confirming` - Confirming
	// * `confirmed` - Confirmed
	// * `completed` - Completed
	// * `partially_paid` - Partially Paid
	// * `failed` - Failed
	// * `expired` - Expired
	// * `cancelled` - Cancelled
	Status types.PaymentlistStatus `json:"status"`
	StatusDisplay string `json:"status_display"`
	// When this record was created
	CreatedAt time.Time `json:"created_at"`
	// When this payment was completed
	CompletedAt time.Time `json:"completed_at"`
}

