// Code generated by django-cfg centrifugo codegen. DO NOT EDIT.

package centrifugo_client

import (
	"context"
	"time"
)

// APIClient is a thin wrapper over CentrifugoRPCClient with typed methods.
type APIClient struct {
	rpc *CentrifugoRPCClient
}

// NewAPIClient creates a new typed API client.
//
// Args:
//   - url: Centrifugo WebSocket URL
//   - token: JWT token for authentication
//   - userID: User ID for reply channel
//
// Example:
//
//	client := NewAPIClient("ws://localhost:8000/connection/websocket", token, "user123")
//	if err := client.Connect(ctx); err != nil {
//	    log.Fatal(err)
//	}
//	defer client.Disconnect()
func NewAPIClient(url, token, userID string) *APIClient {
	return &APIClient{
		rpc: NewCentrifugoRPCClient(url, token, userID, 30*time.Second),
	}
}

// Connect establishes connection to Centrifugo.
func (api *APIClient) Connect(ctx context.Context) error {
	return api.rpc.Connect(ctx)
}

// Disconnect closes the connection.
func (api *APIClient) Disconnect() error {
	return api.rpc.Disconnect()
}

