// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.511119

package cfg__leads__lead_submission

import (
	"cfg/types"
)

// Response serializer for lead submission errors.
type LeadSubmissionError struct {
	Success bool `json:"success"`
	Error string `json:"error"`
	Details map[string]interface{} `json:"details,omitempty"`
}

// Serializer for lead form submission from frontend.
type LeadSubmissionRequest struct {
	Name string `json:"name"`
	Email string `json:"email"`
	Company *string `json:"company,omitempty"`
	CompanySite *string `json:"company_site,omitempty"`
	// * `email` - Email
	// * `whatsapp` - WhatsApp
	// * `telegram` - Telegram
	// * `phone` - Phone
	// * `other` - Other
	ContactType *types.LeadsubmissionrequestContactType `json:"contact_type,omitempty"`
	ContactValue *string `json:"contact_value,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Message string `json:"message"`
	Extra *string `json:"extra,omitempty"`
	// Frontend URL where form was submitted
	SiteURL string `json:"site_url"`
}

// Response serializer for successful lead submission.
type LeadSubmissionResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	LeadID int64 `json:"lead_id"`
}

