// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.684842

package cfg__dashboard__dashboard_api_zones


// OpenAPI zone/group serializer.
type APIZone struct {
	Name string `json:"name"`
	Title string `json:"title"`
	Description string `json:"description"`
	AppCount int64 `json:"app_count"`
	EndpointCount int64 `json:"endpoint_count"`
	Status string `json:"status"`
	SchemaURL string `json:"schema_url"`
	APIURL string `json:"api_url"`
	Apps []string `json:"apps"`
}

// API zones summary serializer.
type APIZonesSummary struct {
	Zones []APIZone `json:"zones"`
	Summary map[string]interface{} `json:"summary"`
}

