"""Django admin (Unfold) — theme, sidebar and the navigation tree.

Split out of ``api/settings/config.py``. It is pure declaration: a menu, some
colours, and the dropdown. Nothing here decides behaviour, so nothing here
needs reading to understand how the project runs — which is exactly what made
it worth moving out of the way.

It imports ``env`` only for the site title.
"""

from __future__ import annotations

from django_cfg import (
    Icons,
    NavigationItem,
    NavigationSection,
    SiteDropdownItem,
    UnfoldColors,
    UnfoldConfig,
    UnfoldSidebar,
)

from api.environment import env


def build_unfold_config() -> UnfoldConfig:
    """The admin interface configuration."""
    return UnfoldConfig(
        # Development autofill (auto-enabled in DEBUG mode)
        dev_autofill_email="admin@example.com",
        dev_autofill_password="admin123",
        dev_autofill_force=True,
        # Branding
        site_title=f"{env.app.name} Admin",
        site_header=env.app.name,
        site_subheader="Demo Project",
        site_url="/",
        site_symbol=Icons.ROCKET_LAUNCH,
        # Theme
        theme="dark",
        colors=UnfoldColors(primary="#3b82f6"),
        # Sidebar
        sidebar=UnfoldSidebar(
            show_search=True,
            show_all_applications=True,
        ),
        # Site dropdown
        site_dropdown=[
            SiteDropdownItem(
                icon=Icons.DEVELOPER_BOARD,
                title="Developer",
                link="https://djangocfg.com",
            ),
        ],
        # Navigation (auto-generated by django-cfg)
        navigation=[
            NavigationSection(
                title="Profiles",
                separator=True,
                collapsible=True,
                items=[
                    NavigationItem(title="User Profiles", icon=Icons.PERSON, link="admin:profiles_userprofile_changelist"),
                ],
            ),
            NavigationSection(
                title="Crypto Exchange",
                separator=True,
                collapsible=True,
                items=[
                    NavigationItem(title="Portfolios", icon=Icons.ACCOUNT_BALANCE_WALLET, link="admin:trading_portfolio_changelist"),
                    NavigationItem(title="Orders", icon=Icons.SHOPPING_CART, link="admin:trading_order_changelist"),
                    NavigationItem(title="Coins", icon=Icons.CURRENCY_BITCOIN, link="admin:crypto_coin_changelist"),
                    NavigationItem(title="Exchanges", icon=Icons.STOREFRONT, link="admin:crypto_exchange_changelist"),
                    NavigationItem(title="Wallets", icon=Icons.ACCOUNT_BALANCE_WALLET, link="admin:crypto_wallet_changelist"),
                    NavigationItem(title="User Profiles", icon=Icons.PERSON, link="admin:profiles_userprofile_changelist"),
                ],
            ),
        ],
    )
