# Test Environment Configuration
# Only test-specific overrides (all defaults in loader.py)

# === Core Django Settings ===
secret_key: "django-cfg-test-key-for-testing-only-this-is-long-enough-now-with-more-characters"
debug: true

# === Database ===
database:
  url: "sqlite:///:memory:"

# === Application URLs ===
app:
  domain: "testserver"
  api_url: "http://testserver"
  site_url: "http://testserver"

# === Security ===
ssl_redirect: false

# === Security Domains ===
security_domains:
  - "localhost"
  - "127.0.0.1"
  - "testserver"

# === Email ===
email:
  backend: "locmem"
  default_from: "Test <test@example.com>"

# === Admin Configuration ===
admin_emails:
  - "test@example.com"

# === RPC Configuration ===
rpc:
  enabled: false
  redis_url: "redis://localhost:6379/2"
  redis_max_connections: 10
  rpc_timeout: 5
  request_stream: stream:rpc_requests_test
  consumer_group: django_rpc_group_test
  stream_maxlen: 1000
  response_key_prefix: "list:response:test:"
  response_key_ttl: 30
  log_level: DEBUG
