# Development Environment Configuration
# Only environment-specific overrides (all defaults in loader.py)

# === Core Django Settings ===
secret_key: "django-cfg-sample-dev-key-change-in-production-this-is-long-enough-now"
debug: true

# === Database ===
database:
  url: "postgresql://postgres:postgres@localhost:5432/djangocfg"

# === Application URLs ===
app:
  domain: "djangocfg.com"
  api_url: "http://localhost:7301"
  site_url: "http://localhost:7310"

# === Admin Configuration ===
admin_emails:
  - "admin@localhost.dev"

# === Cache ===
redis_url: "redis://redis:6379/0"

# === Payments API Keys ===
# PRIVATE: Add your real API keys here for development
payments_api_keys:
  nowpayments_api_key: ""
  nowpayments_ipn_secret: ""
  nowpayments_sandbox_mode: false
