// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.548595

package cfg__newsletter

import (
	"cfg/types"
	"time"
)

// Serializer for NewsletterCampaign model.
type NewsletterCampaign struct {
	ID int64 `json:"id"`
	Newsletter int64 `json:"newsletter"`
	NewsletterTitle string `json:"newsletter_title"`
	Subject string `json:"subject"`
	EmailTitle string `json:"email_title"`
	MainText string `json:"main_text"`
	MainHTMLContent *string `json:"main_html_content,omitempty"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURL *string `json:"button_url,omitempty"`
	SecondaryText *string `json:"secondary_text,omitempty"`
	// * `draft` - Draft
	// * `sending` - Sending
	// * `sent` - Sent
	// * `failed` - Failed
	Status types.NewslettercampaignStatus `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	SentAt time.Time `json:"sent_at"`
	RecipientCount int64 `json:"recipient_count"`
}

// Serializer for NewsletterCampaign model.
type PatchedNewsletterCampaignRequest struct {
	Newsletter *int64 `json:"newsletter,omitempty"`
	Subject *string `json:"subject,omitempty"`
	EmailTitle *string `json:"email_title,omitempty"`
	MainText *string `json:"main_text,omitempty"`
	MainHTMLContent *string `json:"main_html_content,omitempty"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURL *string `json:"button_url,omitempty"`
	SecondaryText *string `json:"secondary_text,omitempty"`
}

// Simple serializer for unsubscribe.
type PatchedUnsubscribeRequest struct {
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
}

// Simple serializer for unsubscribe.
type Unsubscribe struct {
	SubscriptionID int64 `json:"subscription_id"`
}

// Simple serializer for unsubscribe.
type UnsubscribeRequest struct {
	SubscriptionID int64 `json:"subscription_id"`
}

