// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.688097

package cfg__newsletter__testing


// Response for bulk email sending.
type BulkEmailResponse struct {
	Success bool `json:"success"`
	SentCount int64 `json:"sent_count"`
	FailedCount int64 `json:"failed_count"`
	TotalRecipients int64 `json:"total_recipients"`
	Error *string `json:"error,omitempty"`
}

// Simple serializer for test email.
type TestEmailRequest struct {
	Email string `json:"email"`
	Subject *string `json:"subject,omitempty"`
	Message *string `json:"message,omitempty"`
}

