/**
 * Auto-generated image catalog
 * Generated: 2025-11-26T13:03:21.869Z
 * Total images: 2
 *
 * DO NOT EDIT - This file is auto-generated by @djangocfg/imgai
 * Run `imgai sync` to regenerate
 */

// ============================================================================
// TYPES
// ============================================================================

export interface ImageData {
  id: string;
  filename: string;
  url: string;
  path: string;
  extension: string;
  width?: number;
  height?: number;
  size: number;
}

export type ImageId = 'a-sleek-dashboard-interface-mo' | 'test-hero';
export type ImageCategory = 'general' | 'heroes';

// ============================================================================
// IMAGE CATALOG
// ============================================================================

export const IMAGES: Record<ImageId, ImageData> = {
  'a-sleek-dashboard-interface-mo': {
      "id": "a-sleek-dashboard-interface-mo",
      "filename": "a-sleek-dashboard-interface-mo.png",
      "url": "/static/images/general/a-sleek-dashboard-interface-mo.png",
      "path": "static/images/general/a-sleek-dashboard-interface-mo.png",
      "extension": "png",
      "size": 3830596,
      "width": 1792,
      "height": 1024
    },
  'test-hero': {
      "id": "test-hero",
      "filename": "test-hero.png",
      "url": "/static/images/heroes/test-hero.png",
      "path": "static/images/heroes/test-hero.png",
      "extension": "png",
      "size": 2480810,
      "width": 1792,
      "height": 1024
    }
} as const;

// ============================================================================
// BY CATEGORY
// ============================================================================

export const IMAGES_BY_CATEGORY: Record<ImageCategory, readonly ImageData[]> = {
  'general': [IMAGES['a-sleek-dashboard-interface-mo']],
  'heroes': [IMAGES['test-hero']]
} as const;

// ============================================================================
// HELPERS
// ============================================================================

/** Get image by ID */
export function getImage(id: ImageId): ImageData | undefined {
  return IMAGES[id];
}

/** Get image URL by ID */
export function getImageUrl(id: ImageId): string | undefined {
  return IMAGES[id]?.url;
}

/** Get all images in category */
export function getImagesByCategory(category: ImageCategory): readonly ImageData[] {
  return IMAGES_BY_CATEGORY[category] || [];
}

/** Get all image IDs */
export function getAllImageIds(): ImageId[] {
  return Object.keys(IMAGES) as ImageId[];
}

/** Get all categories */
export function getAllCategories(): ImageCategory[] {
  return Object.keys(IMAGES_BY_CATEGORY) as ImageCategory[];
}

/** Check if image exists */
export function hasImage(id: string): id is ImageId {
  return id in IMAGES;
}

// ============================================================================
// METADATA
// ============================================================================

export const IMAGE_CATALOG_META = {
  version: '1.0.0',
  generatedAt: '2025-11-26T13:03:21.869Z',
  totalImages: 2,
  categories: ["general","heroes"],
} as const;
