"""Global auth store + Hey API interceptor installer.

Single source of truth for Bearer token, X-API-Key, Accept-Language,
baseUrl. Exposes `installAuthOnClient(client)` — called by `client.gen.ts`
synchronously right after `createClient()` (post-processed). No circular
import: `auth.ts` does NOT import `client.gen`.

Storage modes:
  • 'localStorage' (default) — JS-readable, simple, survives reload.
  • 'cookie'                 — JS-readable cookie (NOT HttpOnly).
                               Useful when you need SSR to see the
                               token via `cookies()` in Next.js, or
                               share auth across subdomains.

Switch via `auth.setStorageMode('cookie')` early in app bootstrap.
"""

from __future__ import annotations


def render_auth_ts(
    *,
    access_key: str = "cfg.access_token",
    refresh_key: str = "cfg.refresh_token",
    api_key_storage_key: str = "cfg.api_key",
) -> str:
    """Render `helpers/auth.ts` — the global auth store + interceptor installer."""

    return f'''\
// AUTO-GENERATED by django_generator / ts_extras.wrapper
// Global auth store. Wired into the shared `client` from `client.gen.ts`
// via `installAuthOnClient(client)` — called synchronously by the
// post-processed bottom of client.gen.ts. No circular import here.
// DO NOT EDIT — re-run `make gen`.

const ACCESS_KEY = '{access_key}';
const REFRESH_KEY = '{refresh_key}';
const API_KEY_KEY = '{api_key_storage_key}';

const isBrowser = typeof window !== 'undefined';

export type StorageMode = 'localStorage' | 'cookie';

// ── Storage backends (browser-only; server-side reads return null) ─────────

interface KVStore {{
  get(key: string): string | null;
  set(key: string, value: string | null): void;
}}

const localStorageBackend: KVStore = {{
  get(key) {{
    if (!isBrowser) return null;
    try {{ return window.localStorage.getItem(key); }} catch {{ return null; }}
  }},
  set(key, value) {{
    if (!isBrowser) return;
    try {{
      if (value === null) window.localStorage.removeItem(key);
      else window.localStorage.setItem(key, value);
    }} catch {{}}
  }},
}};

/** 30 days, matches typical refresh-token lifetime. */
const COOKIE_MAX_AGE = 60 * 60 * 24 * 30;

const cookieBackend: KVStore = {{
  get(key) {{
    if (!isBrowser) return null;
    try {{
      const re = new RegExp(`(?:^|;\\\\s*)${{encodeURIComponent(key)}}=([^;]*)`);
      const m = document.cookie.match(re);
      return m ? decodeURIComponent(m[1]) : null;
    }} catch {{ return null; }}
  }},
  set(key, value) {{
    if (!isBrowser) return;
    try {{
      const k = encodeURIComponent(key);
      const secure = window.location.protocol === 'https:' ? '; Secure' : '';
      if (value === null) {{
        document.cookie = `${{k}}=; Path=/; Max-Age=0; SameSite=Lax${{secure}}`;
      }} else {{
        const v = encodeURIComponent(value);
        document.cookie = `${{k}}=${{v}}; Path=/; Max-Age=${{COOKIE_MAX_AGE}}; SameSite=Lax${{secure}}`;
      }}
    }} catch {{}}
  }},
}};

let _storage: KVStore = localStorageBackend;
let _storageMode: StorageMode = 'localStorage';

/** Detect locale from `NEXT_LOCALE` cookie or `navigator.language`. */
function detectLocale(): string | null {{
  try {{
    if (typeof document !== 'undefined') {{
      const m = document.cookie.match(/(?:^|;\\s*)NEXT_LOCALE=([^;]*)/);
      if (m) return decodeURIComponent(m[1]);
    }}
    if (typeof navigator !== 'undefined' && navigator.language) {{
      return navigator.language;
    }}
  }} catch {{}}
  return null;
}}

/** Default baseUrl from `NEXT_PUBLIC_API_URL` (empty for static builds). */
function defaultBaseUrl(): string {{
  try {{
    if (typeof process !== 'undefined' && process.env) {{
      if (process.env.NEXT_PUBLIC_STATIC_BUILD === 'true') return '';
      return process.env.NEXT_PUBLIC_API_URL || '';
    }}
  }} catch {{}}
  return '';
}}

/** Default API key fallback from `NEXT_PUBLIC_API_KEY`. */
function defaultApiKey(): string | null {{
  try {{
    if (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_API_KEY) {{
      return process.env.NEXT_PUBLIC_API_KEY;
    }}
  }} catch {{}}
  return null;
}}

// ── In-memory overrides (win over storage / env) ───────────────────────────
let _localeOverride: string | null = null;
let _apiKeyOverride: string | null = null;
let _baseUrlOverride: string | null = null;
let _withCredentials = true;
let _onUnauthorized: ((response: Response) => void) | null = null;

/**
 * User-supplied refresh handler. Receives the current refresh token,
 * must return a fresh access (and optional refresh) pair or null on failure.
 * Set once at app bootstrap via `auth.setRefreshHandler(...)`.
 */
type RefreshResult = {{ access: string; refresh?: string }} | null;
type RefreshHandler = (refreshToken: string) => Promise<RefreshResult>;
let _refreshHandler: RefreshHandler | null = null;

/** Single-flight: every concurrent 401 awaits the same refresh. */
let _refreshInflight: Promise<string | null> | null = null;

/** Marker header — set on retried requests so we never loop on 401. */
const RETRY_MARKER = 'X-Auth-Retry';

/**
 * Captured reference to the shared Hey API client. Set exactly once by
 * `installAuthOnClient(client)` (called from client.gen.ts). All `auth.set*`
 * methods that mutate transport config (baseUrl / credentials) push through
 * this reference. Until installed, those mutations are silently buffered as
 * in-memory state — the next request after install will pick them up.
 */
type HeyClient = {{
  setConfig(opts: Record<string, unknown>): void;
  interceptors: {{
    request: {{ use(fn: (req: Request) => Request | Promise<Request>): void }};
    response: {{ use(fn: (res: Response, req: Request) => Response | Promise<Response>): void }};
  }};
}};
let _client: HeyClient | null = null;

function pushClientConfig(): void {{
  if (!_client) return;
  _client.setConfig({{
    baseUrl: auth.getBaseUrl(),
    credentials: _withCredentials ? 'include' : 'same-origin',
  }});
}}

/**
 * Global auth/config store. All getters read live state every call —
 * the interceptor below uses these to attach headers per-request.
 *
 * Default storage backend is `localStorage`. Switch to cookies (e.g.
 * for Next.js SSR cookie access) via `auth.setStorageMode('cookie')`
 * early in the app bootstrap.
 *
 * @example
 *   import {{ auth }} from '@your/api';
 *   auth.setToken(jwt);
 *   auth.clearTokens();
 *   auth.setStorageMode('cookie');
 */
export const auth = {{
  // ── Storage mode ──────────────────────────────────────────────────
  getStorageMode(): StorageMode {{ return _storageMode; }},
  setStorageMode(mode: StorageMode): void {{
    _storageMode = mode;
    _storage = mode === 'cookie' ? cookieBackend : localStorageBackend;
  }},

  // ── Bearer token ──────────────────────────────────────────────────
  getToken(): string | null {{ return _storage.get(ACCESS_KEY); }},
  setToken(token: string | null): void {{ _storage.set(ACCESS_KEY, token); }},
  getRefreshToken(): string | null {{ return _storage.get(REFRESH_KEY); }},
  setRefreshToken(token: string | null): void {{ _storage.set(REFRESH_KEY, token); }},
  clearTokens(): void {{ _storage.set(ACCESS_KEY, null); _storage.set(REFRESH_KEY, null); }},
  isAuthenticated(): boolean {{ return _storage.get(ACCESS_KEY) !== null; }},

  // ── API key ───────────────────────────────────────────────────────
  getApiKey(): string | null {{
    return _apiKeyOverride ?? _storage.get(API_KEY_KEY) ?? defaultApiKey();
  }},
  setApiKey(key: string | null): void {{ _apiKeyOverride = key; }},
  setApiKeyPersist(key: string | null): void {{
    _apiKeyOverride = key;
    _storage.set(API_KEY_KEY, key);
  }},
  clearApiKey(): void {{ _apiKeyOverride = null; _storage.set(API_KEY_KEY, null); }},

  // ── Locale ────────────────────────────────────────────────────────
  getLocale(): string | null {{ return _localeOverride ?? detectLocale(); }},
  setLocale(locale: string | null): void {{ _localeOverride = locale; }},

  // ── Base URL ──────────────────────────────────────────────────────
  getBaseUrl(): string {{
    const url = (_baseUrlOverride ?? defaultBaseUrl());
    return url.replace(/\\/$/, '');
  }},
  setBaseUrl(url: string | null): void {{
    _baseUrlOverride = url ? url.replace(/\\/$/, '') : null;
    pushClientConfig();
  }},

  // ── Credentials toggle ────────────────────────────────────────────
  getWithCredentials(): boolean {{ return _withCredentials; }},
  setWithCredentials(value: boolean): void {{
    _withCredentials = value;
    pushClientConfig();
  }},

  // ── 401 handler ───────────────────────────────────────────────────
  /**
   * Fired when the server returns 401 AND no refresh path recovers it
   * (no refresh token, no refresh handler, refresh failed, or retry
   * still 401). The app should clear local state and redirect to login.
   *
   * NOT fired for 401 that gets transparently recovered by the refresh
   * handler — those are invisible to callers.
   */
  onUnauthorized(cb: ((response: Response) => void) | null): void {{
    _onUnauthorized = cb;
  }},

  /**
   * Register the refresh strategy. The handler receives the current
   * refresh token and must call your refresh endpoint, returning
   * `{{ access, refresh? }}` on success or `null` on failure.
   *
   * @example
   *   auth.setRefreshHandler(async (refresh) => {{
   *     const {{ data }} = await Auth.tokenRefreshCreate({{ body: {{ refresh }} }});
   *     return data ? {{ access: data.access, refresh: data.refresh }} : null;
   *   }});
   */
  setRefreshHandler(fn: RefreshHandler | null): void {{
    _refreshHandler = fn;
  }},
}};

/**
 * Run the user-supplied refresh handler under single-flight, persist
 * the new tokens, and return the fresh access token (or null on any
 * failure path). All concurrent 401s share the same in-flight promise.
 */
async function tryRefresh(): Promise<string | null> {{
  if (_refreshInflight) return _refreshInflight;
  if (!_refreshHandler) return null;
  const refresh = auth.getRefreshToken();
  if (!refresh) return null;

  _refreshInflight = (async () => {{
    try {{
      const result = await _refreshHandler!(refresh);
      if (!result?.access) return null;
      auth.setToken(result.access);
      if (result.refresh) auth.setRefreshToken(result.refresh);
      return result.access;
    }} catch {{
      return null;
    }} finally {{
      _refreshInflight = null;
    }}
  }})();

  return _refreshInflight;
}}

/**
 * Wire the shared client to the global auth store. Called exactly
 * once from `client.gen.ts` (post-processed) right after
 * `createClient()`. Synchronous — no microtask, no TDZ races.
 *
 * Safe to call from server / SSR: storage backends short-circuit on
 * non-browser environments, so headers populated by the interceptor
 * are simply absent server-side (which is the correct behaviour
 * unless the caller explicitly sets a server-side token).
 */
export function installAuthOnClient(client: HeyClient): void {{
  if (_client) return; // idempotent
  _client = client;

  client.setConfig({{
    baseUrl: auth.getBaseUrl(),
    credentials: _withCredentials ? 'include' : 'same-origin',
  }});

  client.interceptors.request.use((request) => {{
    const token = auth.getToken();
    if (token) request.headers.set('Authorization', `Bearer ${{token}}`);

    const locale = auth.getLocale();
    if (locale) request.headers.set('Accept-Language', locale);

    const apiKey = auth.getApiKey();
    if (apiKey) request.headers.set('X-API-Key', apiKey);

    try {{
      const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
      if (tz) request.headers.set('X-Timezone', tz);
    }} catch {{}}
    request.headers.set('X-Client-Time', new Date().toISOString());

    return request;
  }});

  client.interceptors.response.use(async (response, request) => {{
    if (response.status !== 401) return response;

    // Already retried once — give up to avoid loops.
    if (request.headers.get(RETRY_MARKER)) {{
      if (_onUnauthorized) {{
        try {{ _onUnauthorized(response); }} catch {{}}
      }}
      return response;
    }}

    const newToken = await tryRefresh();
    if (!newToken) {{
      if (_onUnauthorized) {{
        try {{ _onUnauthorized(response); }} catch {{}}
      }}
      return response;
    }}

    // Retry the original request once with the new token. We mutate a
    // clone so the original Request body (already consumed by the
    // failed call) doesn't trip "body already used".
    const retry = request.clone();
    retry.headers.set('Authorization', `Bearer ${{newToken}}`);
    retry.headers.set(RETRY_MARKER, '1');
    try {{
      const retried = await fetch(retry);
      if (retried.status === 401 && _onUnauthorized) {{
        try {{ _onUnauthorized(retried); }} catch {{}}
      }}
      return retried;
    }} catch {{
      // Network error on retry — surface the original 401.
      if (_onUnauthorized) {{
        try {{ _onUnauthorized(response); }} catch {{}}
      }}
      return response;
    }}
  }});
}}

export type Auth = typeof auth;
'''


__all__ = ["render_auth_ts"]
