// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  SupportTicketsListData,
  SupportTicketsListResponses,
  SupportTicketsCreateData,
  SupportTicketsCreateResponses,
  SupportTicketsMessagesListData,
  SupportTicketsMessagesListResponses,
  SupportTicketsMessagesCreateData,
  SupportTicketsMessagesCreateResponses,
  SupportTicketsMessagesDestroyData,
  SupportTicketsMessagesDestroyResponses,
  SupportTicketsMessagesRetrieveData,
  SupportTicketsMessagesRetrieveResponses,
  SupportTicketsMessagesPartialUpdateData,
  SupportTicketsMessagesPartialUpdateResponses,
  SupportTicketsMessagesUpdateData,
  SupportTicketsMessagesUpdateResponses,
  SupportTicketsDestroyData,
  SupportTicketsDestroyResponses,
  SupportTicketsRetrieveData,
  SupportTicketsRetrieveResponses,
  SupportTicketsPartialUpdateData,
  SupportTicketsPartialUpdateResponses,
  SupportTicketsUpdateData,
  SupportTicketsUpdateResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * ViewSet for managing support tickets.
 */
export const supportTicketsList = <ThrowOnError extends boolean = false>(
  options?: Options<SupportTicketsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    SupportTicketsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/",
    ...options,
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const supportTicketsCreate = <ThrowOnError extends boolean = false>(
  options: Options<SupportTicketsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    SupportTicketsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support messages.
 */
export const supportTicketsMessagesList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SupportTicketsMessagesListData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SupportTicketsMessagesListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/",
    ...options,
  });
};

/**
 * ViewSet for managing support messages.
 */
export const supportTicketsMessagesCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SupportTicketsMessagesCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    SupportTicketsMessagesCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support messages.
 */
export const supportTicketsMessagesDestroy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SupportTicketsMessagesDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    SupportTicketsMessagesDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/",
    ...options,
  });
};

/**
 * ViewSet for managing support messages.
 */
export const supportTicketsMessagesRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SupportTicketsMessagesRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SupportTicketsMessagesRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/",
    ...options,
  });
};

/**
 * ViewSet for managing support messages.
 */
export const supportTicketsMessagesPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SupportTicketsMessagesPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    SupportTicketsMessagesPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support messages.
 */
export const supportTicketsMessagesUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SupportTicketsMessagesUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    SupportTicketsMessagesUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const supportTicketsDestroy = <ThrowOnError extends boolean = false>(
  options: Options<SupportTicketsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    SupportTicketsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{uuid}/",
    ...options,
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const supportTicketsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<SupportTicketsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SupportTicketsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{uuid}/",
    ...options,
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const supportTicketsPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SupportTicketsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    SupportTicketsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const supportTicketsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<SupportTicketsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    SupportTicketsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
