// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  BlogCategoriesListData,
  BlogCategoriesListResponses,
  BlogCategoriesCreateData,
  BlogCategoriesCreateResponses,
  BlogCategoriesDestroyData,
  BlogCategoriesDestroyResponses,
  BlogCategoriesRetrieveData,
  BlogCategoriesRetrieveResponses,
  BlogCategoriesPartialUpdateData,
  BlogCategoriesPartialUpdateResponses,
  BlogCategoriesUpdateData,
  BlogCategoriesUpdateResponses,
  BlogCommentsListData,
  BlogCommentsListResponses,
  BlogCommentsCreateData,
  BlogCommentsCreateResponses,
  BlogCommentsDestroyData,
  BlogCommentsDestroyResponses,
  BlogCommentsRetrieveData,
  BlogCommentsRetrieveResponses,
  BlogCommentsPartialUpdateData,
  BlogCommentsPartialUpdateResponses,
  BlogCommentsUpdateData,
  BlogCommentsUpdateResponses,
  BlogPostsListData,
  BlogPostsListResponses,
  BlogPostsCreateData,
  BlogPostsCreateResponses,
  BlogPostsCommentsListData,
  BlogPostsCommentsListResponses,
  BlogPostsCommentsCreateData,
  BlogPostsCommentsCreateResponses,
  BlogPostsCommentsDestroyData,
  BlogPostsCommentsDestroyResponses,
  BlogPostsCommentsRetrieveData,
  BlogPostsCommentsRetrieveResponses,
  BlogPostsCommentsPartialUpdateData,
  BlogPostsCommentsPartialUpdateResponses,
  BlogPostsCommentsUpdateData,
  BlogPostsCommentsUpdateResponses,
  BlogPostsDestroyData,
  BlogPostsDestroyResponses,
  BlogPostsRetrieveData,
  BlogPostsRetrieveResponses,
  BlogPostsPartialUpdateData,
  BlogPostsPartialUpdateResponses,
  BlogPostsUpdateData,
  BlogPostsUpdateResponses,
  BlogPostsLikeCreateData,
  BlogPostsLikeCreateResponses,
  BlogPostsLikesListData,
  BlogPostsLikesListResponses,
  BlogPostsFeaturedRetrieveData,
  BlogPostsFeaturedRetrieveResponses,
  BlogPostsStatsRetrieveData,
  BlogPostsStatsRetrieveResponses,
  BlogTagsListData,
  BlogTagsListResponses,
  BlogTagsCreateData,
  BlogTagsCreateResponses,
  BlogTagsDestroyData,
  BlogTagsDestroyResponses,
  BlogTagsRetrieveData,
  BlogTagsRetrieveResponses,
  BlogTagsPartialUpdateData,
  BlogTagsPartialUpdateResponses,
  BlogTagsUpdateData,
  BlogTagsUpdateResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List categories
 * Get a list of all blog categories
 */
export const blogCategoriesList = <ThrowOnError extends boolean = false>(
  options?: Options<BlogCategoriesListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    BlogCategoriesListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/categories/",
    ...options,
  });
};

/**
 * Create category
 * Create a new blog category
 */
export const blogCategoriesCreate = <ThrowOnError extends boolean = false>(
  options: Options<BlogCategoriesCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    BlogCategoriesCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/categories/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete category
 * Delete a category
 */
export const blogCategoriesDestroy = <ThrowOnError extends boolean = false>(
  options: Options<BlogCategoriesDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    BlogCategoriesDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/categories/{slug}/",
    ...options,
  });
};

/**
 * Get category
 * Get details of a specific category
 */
export const blogCategoriesRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<BlogCategoriesRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    BlogCategoriesRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/categories/{slug}/",
    ...options,
  });
};

/**
 * ViewSet for blog categories.
 */
export const blogCategoriesPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<BlogCategoriesPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    BlogCategoriesPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/categories/{slug}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Update category
 * Update category information
 */
export const blogCategoriesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlogCategoriesUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    BlogCategoriesUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/categories/{slug}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List comments
 * Get a list of comments
 */
export const blogCommentsList = <ThrowOnError extends boolean = false>(
  options?: Options<BlogCommentsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    BlogCommentsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/comments/",
    ...options,
  });
};

/**
 * Create comment
 * Create a new comment
 */
export const blogCommentsCreate = <ThrowOnError extends boolean = false>(
  options: Options<BlogCommentsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    BlogCommentsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/comments/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete comment
 * Delete a comment
 */
export const blogCommentsDestroy = <ThrowOnError extends boolean = false>(
  options: Options<BlogCommentsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    BlogCommentsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/comments/{id}/",
    ...options,
  });
};

/**
 * Get comment
 * Get details of a specific comment
 */
export const blogCommentsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<BlogCommentsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    BlogCommentsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/comments/{id}/",
    ...options,
  });
};

/**
 * ViewSet for blog comments.
 */
export const blogCommentsPartialUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlogCommentsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    BlogCommentsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/comments/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Update comment
 * Update comment content
 */
export const blogCommentsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlogCommentsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    BlogCommentsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/comments/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List posts
 * Get a paginated list of blog posts
 */
export const blogPostsList = <ThrowOnError extends boolean = false>(
  options?: Options<BlogPostsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    BlogPostsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/",
    ...options,
  });
};

/**
 * Create post
 * Create a new blog post
 */
export const blogPostsCreate = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    BlogPostsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List comments
 * Get a list of comments
 */
export const blogPostsCommentsList = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsCommentsListData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    BlogPostsCommentsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{post_slug}/comments/",
    ...options,
  });
};

/**
 * Create comment
 * Create a new comment
 */
export const blogPostsCommentsCreate = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsCommentsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    BlogPostsCommentsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{post_slug}/comments/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete comment
 * Delete a comment
 */
export const blogPostsCommentsDestroy = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsCommentsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    BlogPostsCommentsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{post_slug}/comments/{id}/",
    ...options,
  });
};

/**
 * Get comment
 * Get details of a specific comment
 */
export const blogPostsCommentsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsCommentsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    BlogPostsCommentsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{post_slug}/comments/{id}/",
    ...options,
  });
};

/**
 * ViewSet for blog comments.
 */
export const blogPostsCommentsPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<BlogPostsCommentsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    BlogPostsCommentsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{post_slug}/comments/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Update comment
 * Update comment content
 */
export const blogPostsCommentsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsCommentsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    BlogPostsCommentsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{post_slug}/comments/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete post
 * Delete a blog post
 */
export const blogPostsDestroy = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    BlogPostsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{slug}/",
    ...options,
  });
};

/**
 * Get post
 * Get detailed information about a specific post
 */
export const blogPostsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    BlogPostsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{slug}/",
    ...options,
  });
};

/**
 * ViewSet for blog posts.
 */
export const blogPostsPartialUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    BlogPostsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{slug}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Update post
 * Update post information
 */
export const blogPostsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    BlogPostsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{slug}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Like/unlike post
 * Toggle like status for a post
 */
export const blogPostsLikeCreate = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsLikeCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    BlogPostsLikeCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{slug}/like/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get post likes
 * Get all likes for a post
 */
export const blogPostsLikesList = <ThrowOnError extends boolean = false>(
  options: Options<BlogPostsLikesListData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    BlogPostsLikesListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/{slug}/likes/",
    ...options,
  });
};

/**
 * Get featured posts
 * Get featured blog posts
 */
export const blogPostsFeaturedRetrieve = <ThrowOnError extends boolean = false>(
  options?: Options<BlogPostsFeaturedRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    BlogPostsFeaturedRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/featured/",
    ...options,
  });
};

/**
 * Get blog statistics
 * Get comprehensive blog statistics
 */
export const blogPostsStatsRetrieve = <ThrowOnError extends boolean = false>(
  options?: Options<BlogPostsStatsRetrieveData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    BlogPostsStatsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/posts/stats/",
    ...options,
  });
};

/**
 * List tags
 * Get a list of all blog tags
 */
export const blogTagsList = <ThrowOnError extends boolean = false>(
  options?: Options<BlogTagsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    BlogTagsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/tags/",
    ...options,
  });
};

/**
 * Create tag
 * Create a new blog tag
 */
export const blogTagsCreate = <ThrowOnError extends boolean = false>(
  options: Options<BlogTagsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    BlogTagsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/tags/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for blog tags.
 */
export const blogTagsDestroy = <ThrowOnError extends boolean = false>(
  options: Options<BlogTagsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    BlogTagsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/tags/{slug}/",
    ...options,
  });
};

/**
 * ViewSet for blog tags.
 */
export const blogTagsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<BlogTagsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    BlogTagsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/tags/{slug}/",
    ...options,
  });
};

/**
 * ViewSet for blog tags.
 */
export const blogTagsPartialUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlogTagsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    BlogTagsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/tags/{slug}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for blog tags.
 */
export const blogTagsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlogTagsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    BlogTagsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/blog/tags/{slug}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
