// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.507178

package cfg__centrifugo__centrifugo_monitoring


// List of channel statistics.
type ChannelList struct {
	// Channel statistics
	Channels []ChannelStatsSerializer `json:"channels"`
	// Total number of channels
	TotalChannels int64 `json:"total_channels"`
}

// Statistics per channel.
type ChannelStatsSerializer struct {
	// Channel name
	Channel string `json:"channel"`
	// Total publishes to this channel
	Total int64 `json:"total"`
	// Successful publishes
	Successful int64 `json:"successful"`
	// Failed publishes
	Failed int64 `json:"failed"`
	// Average duration
	AvgDurationMs float64 `json:"avg_duration_ms"`
	// Average ACKs received
	AvgAcks float64 `json:"avg_acks"`
	// Last activity timestamp (ISO format)
	LastActivityAt *string `json:"last_activity_at,omitempty"`
}

// Health check response.
type HealthCheck struct {
	// Health status: healthy or unhealthy
	Status string `json:"status"`
	// Configured wrapper URL
	WrapperURL string `json:"wrapper_url"`
	// Whether API key is configured
	HasAPIKey bool `json:"has_api_key"`
	// Current timestamp
	Timestamp string `json:"timestamp"`
}

// Overview statistics for Centrifugo publishes.
type OverviewStats struct {
	// Total publishes in period
	Total int64 `json:"total"`
	// Successful publishes
	Successful int64 `json:"successful"`
	// Failed publishes
	Failed int64 `json:"failed"`
	// Timeout publishes
	Timeout int64 `json:"timeout"`
	// Success rate percentage
	SuccessRate float64 `json:"success_rate"`
	// Average duration in milliseconds
	AvgDurationMs float64 `json:"avg_duration_ms"`
	// Average ACKs received
	AvgAcksReceived float64 `json:"avg_acks_received"`
	// Statistics period in hours
	PeriodHours int64 `json:"period_hours"`
}

// Recent publishes list.
type RecentPublishes struct {
	// List of recent publishes
	Publishes []map[string]interface{} `json:"publishes"`
	// Number of publishes returned
	Count int64 `json:"count"`
	// Total publishes available
	TotalAvailable int64 `json:"total_available"`
	// Current offset for pagination
	Offset *int64 `json:"offset,omitempty"`
	// Whether more results are available
	HasMore *bool `json:"has_more,omitempty"`
}

