// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.690420

package cfg__health

import (
	"time"
)

// Health check response.
type HealthCheck struct {
	// Health status: healthy or unhealthy
	Status string `json:"status"`
	// Configured wrapper URL
	WrapperURL string `json:"wrapper_url"`
	// Whether API key is configured
	HasAPIKey bool `json:"has_api_key"`
	// Current timestamp
	Timestamp string `json:"timestamp"`
}

// Serializer for quick health check response.
type QuickHealth struct {
	// Quick health status: ok or error
	Status string `json:"status"`
	// Timestamp of the health check
	Timestamp time.Time `json:"timestamp"`
	// Error message if health check failed
	Error *string `json:"error,omitempty"`
}

