# Generated by Django 5.2.15 on 2026-07-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Analytics Site",
                "verbose_name_plural": "Analytics Sites",
                "db_table": "cfg_analytics_site",
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSession",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("visitor_id", models.UUIDField()),
                ("started_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("entry_pathname", models.CharField(blank=True, max_length=1024)),
                ("exit_pathname", models.CharField(blank=True, max_length=1024)),
                ("pageviews", models.PositiveIntegerField(default=0)),
                ("events", models.PositiveIntegerField(default=0)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("is_bounce", models.BooleanField(default=True)),
                ("channel", models.CharField(blank=True, max_length=32)),
                ("referrer_domain", models.CharField(blank=True, max_length=255)),
                ("utm_source", models.CharField(blank=True, max_length=255)),
                ("utm_medium", models.CharField(blank=True, max_length=255)),
                ("utm_campaign", models.CharField(blank=True, max_length=255)),
                ("browser", models.CharField(blank=True, max_length=32)),
                ("os", models.CharField(blank=True, max_length=32)),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=35)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="cfg_analytics.analyticssite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Session",
                "verbose_name_plural": "Analytics Sessions",
                "db_table": "cfg_analytics_session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ts", models.DateTimeField()),
                ("visitor_id", models.UUIDField()),
                (
                    "event_name",
                    models.CharField(
                        choices=[("pageview", "Pageview"), ("custom", "Custom")],
                        default="pageview",
                        max_length=64,
                    ),
                ),
                ("pathname", models.CharField(max_length=1024)),
                ("route", models.CharField(blank=True, max_length=1024)),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("page_title", models.CharField(blank=True, max_length=512)),
                ("referrer_domain", models.CharField(blank=True, max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("organic_search", "Organic Search"),
                            ("organic_social", "Organic Social"),
                            ("organic_video", "Organic Video"),
                            ("ai", "AI Assistant"),
                            ("referral", "Referral"),
                            ("paid_search", "Paid Search"),
                            ("paid_social", "Paid Social"),
                            ("email", "Email"),
                            ("affiliate", "Affiliate"),
                            ("unknown", "Unknown"),
                        ],
                        default="direct",
                        max_length=32,
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=255)),
                ("utm_medium", models.CharField(blank=True, max_length=255)),
                ("utm_campaign", models.CharField(blank=True, max_length=255)),
                ("utm_content", models.CharField(blank=True, max_length=255)),
                ("utm_term", models.CharField(blank=True, max_length=255)),
                ("click_id", models.CharField(blank=True, max_length=255)),
                ("click_id_param", models.CharField(blank=True, max_length=32)),
                ("props", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="cfg_analytics.analyticssession",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cfg_analytics.analyticssite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Event",
                "verbose_name_plural": "Analytics Events",
                "db_table": "cfg_analytics_event",
                "ordering": ["-ts"],
            },
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(fields=["site", "started_at"], name="cfg_an_sess_site_start"),
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(fields=["site", "visitor_id"], name="cfg_an_sess_visitor"),
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(
                condition=models.Q(("user__isnull", False)),
                fields=["user", "started_at"],
                name="cfg_an_sess_user",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["site", "ts"], name="cfg_an_ev_site_ts"),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["site", "ts", "pathname"], name="cfg_an_ev_path"),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["site", "ts", "referrer_domain"], name="cfg_an_ev_ref"),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["site", "ts", "channel"], name="cfg_an_ev_chan"),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["site", "session", "ts"], name="cfg_an_ev_sess"),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                condition=models.Q(("user__isnull", False)),
                fields=["user", "ts"],
                name="cfg_an_ev_user",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["ts"], name="cfg_an_ev_ts"),
        ),
    ]
