# Generated by Django 5.2.16 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cfg_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="is_measurement",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="analyticssession",
            name="is_measurement",
            field=models.BooleanField(default=True),
        ),
    ]
