# Generated by Django 5.2.16 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cfg_analytics", "0002_server_auth_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsProperty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Analytics property",
                "verbose_name_plural": "Analytics properties",
                "db_table": "cfg_analytics_property",
                "ordering": ["domain"],
            },
        ),
        migrations.AddField(
            model_name="analyticssite",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="cfg_analytics.analyticsproperty",
            ),
        ),
    ]
