# Generated by Django 5.2.16 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [("cfg_analytics", "0003_analytics_property")]

    operations = [
        migrations.CreateModel(
            name="AnalyticsGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_name", models.CharField(max_length=64)),
                ("property", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="analyticsgoal_definitions", to="cfg_analytics.analyticsproperty")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="analyticsgoal_definitions", to="cfg_analytics.analyticssite")),
            ],
            options={"verbose_name": "Analytics goal", "verbose_name_plural": "Analytics goals", "db_table": "cfg_analytics_goal", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="AnalyticsFunnel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("property", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="analyticsfunnel_definitions", to="cfg_analytics.analyticsproperty")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="analyticsfunnel_definitions", to="cfg_analytics.analyticssite")),
            ],
            options={"verbose_name": "Analytics funnel", "verbose_name_plural": "Analytics funnels", "db_table": "cfg_analytics_funnel", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="AnalyticsFunnelStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=128)),
                ("event_name", models.CharField(max_length=64)),
                ("funnel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="cfg_analytics.analyticsfunnel")),
            ],
            options={"verbose_name": "Analytics funnel step", "verbose_name_plural": "Analytics funnel steps", "db_table": "cfg_analytics_funnel_step", "ordering": ["funnel", "position"]},
        ),
        migrations.AddConstraint(model_name="analyticsgoal", constraint=models.CheckConstraint(condition=Q(("property__isnull", False), ("site__isnull", True)) | Q(("property__isnull", True), ("site__isnull", False)), name="cfg_an_goal_one_source")),
        migrations.AddConstraint(model_name="analyticsfunnel", constraint=models.CheckConstraint(condition=Q(("property__isnull", False), ("site__isnull", True)) | Q(("property__isnull", True), ("site__isnull", False)), name="cfg_an_funnel_one_source")),
        migrations.AddConstraint(model_name="analyticsfunnelstep", constraint=models.UniqueConstraint(fields=("funnel", "position"), name="cfg_an_funnel_step_position")),
        migrations.AddConstraint(model_name="analyticsfunnelstep", constraint=models.UniqueConstraint(fields=("funnel", "event_name"), name="cfg_an_funnel_step_event")),
    ]
