# Generated by Django 5.2.16 on 2026-07-28 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfg_analytics", "0004_goals_and_funnels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="analyticsfunnel",
            name="cfg_an_funnel_one_source",
        ),
        migrations.RemoveConstraint(
            model_name="analyticsgoal",
            name="cfg_an_goal_one_source",
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="source_id_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="analyticsfunnel",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_definitions",
                to="cfg_analytics.analyticsproperty",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsfunnel",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_definitions",
                to="cfg_analytics.analyticssite",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsgoal",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_definitions",
                to="cfg_analytics.analyticsproperty",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsgoal",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_definitions",
                to="cfg_analytics.analyticssite",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["site", "source_id_hash"], name="cfg_an_ev_source"),
        ),
        migrations.AddConstraint(
            model_name="analyticsfunnel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("property__isnull", True), ("site__isnull", False)),
                    models.Q(("property__isnull", False), ("site__isnull", True)),
                    _connector="OR",
                ),
                name="cfg_an_funnel_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="analyticsgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("property__isnull", True), ("site__isnull", False)),
                    models.Q(("property__isnull", False), ("site__isnull", True)),
                    _connector="OR",
                ),
                name="cfg_an_goal_one_source",
            ),
        ),
    ]
