// This file is auto-generated by @hey-api/openapi-ts

/**
 * * `email` - Email
 * * `whatsapp` - WhatsApp
 * * `telegram` - Telegram
 * * `phone` - Phone
 * * `other` - Other
 */
export type ContactTypeEnum =
  | "email"
  | "whatsapp"
  | "telegram"
  | "phone"
  | "other";

/**
 * Serializer for lead form submission from frontend.
 */
export type LeadSubmission = {
  /**
   * Full Name
   */
  name: string;
  email: string;
  company?: string | null;
  company_site?: string | null;
  contact_type?: ContactTypeEnum;
  contact_value?: string | null;
  subject?: string | null;
  message: string;
  /**
   * Extra Data
   */
  extra?: unknown;
  /**
   * Frontend URL where form was submitted
   */
  site_url: string;
};

/**
 * Response serializer for lead submission errors.
 */
export type LeadSubmissionError = {
  success: boolean;
  error: string;
  details?: {
    [key: string]: unknown;
  };
};

/**
 * Serializer for lead form submission from frontend.
 */
export type LeadSubmissionRequest = {
  /**
   * Full Name
   */
  name: string;
  email: string;
  company?: string | null;
  company_site?: string | null;
  contact_type?: ContactTypeEnum;
  contact_value?: string | null;
  subject?: string | null;
  message: string;
  /**
   * Extra Data
   */
  extra?: unknown;
  /**
   * Frontend URL where form was submitted
   */
  site_url: string;
};

/**
 * Response serializer for successful lead submission.
 */
export type LeadSubmissionResponse = {
  success: boolean;
  message: string;
  lead_id: number;
};

export type PaginatedLeadSubmissionList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<LeadSubmission>;
};

/**
 * Serializer for lead form submission from frontend.
 */
export type PatchedLeadSubmissionRequest = {
  /**
   * Full Name
   */
  name?: string;
  email?: string;
  company?: string | null;
  company_site?: string | null;
  contact_type?: ContactTypeEnum;
  contact_value?: string | null;
  subject?: string | null;
  message?: string;
  /**
   * Extra Data
   */
  extra?: unknown;
  /**
   * Frontend URL where form was submitted
   */
  site_url?: string;
};

export type ApiLeadsLeadsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * A search term.
     */
    search?: string;
  };
  url: "/api/leads/leads/";
};

export type ApiLeadsLeadsListResponses = {
  200: PaginatedLeadSubmissionList;
};

export type ApiLeadsLeadsListResponse =
  ApiLeadsLeadsListResponses[keyof ApiLeadsLeadsListResponses];

export type ApiLeadsLeadsCreateData = {
  body: LeadSubmissionRequest;
  path?: never;
  query?: never;
  url: "/api/leads/leads/";
};

export type ApiLeadsLeadsCreateResponses = {
  201: LeadSubmission;
};

export type ApiLeadsLeadsCreateResponse =
  ApiLeadsLeadsCreateResponses[keyof ApiLeadsLeadsCreateResponses];

export type ApiLeadsLeadsDestroyData = {
  body?: never;
  path: {
    /**
     * A unique integer value identifying this Lead.
     */
    id: number;
  };
  query?: never;
  url: "/api/leads/leads/{id}/";
};

export type ApiLeadsLeadsDestroyResponses = {
  /**
   * No response body
   */
  204: void;
};

export type ApiLeadsLeadsDestroyResponse =
  ApiLeadsLeadsDestroyResponses[keyof ApiLeadsLeadsDestroyResponses];

export type ApiLeadsLeadsRetrieveData = {
  body?: never;
  path: {
    /**
     * A unique integer value identifying this Lead.
     */
    id: number;
  };
  query?: never;
  url: "/api/leads/leads/{id}/";
};

export type ApiLeadsLeadsRetrieveResponses = {
  200: LeadSubmission;
};

export type ApiLeadsLeadsRetrieveResponse =
  ApiLeadsLeadsRetrieveResponses[keyof ApiLeadsLeadsRetrieveResponses];

export type ApiLeadsLeadsPartialUpdateData = {
  body?: PatchedLeadSubmissionRequest;
  path: {
    /**
     * A unique integer value identifying this Lead.
     */
    id: number;
  };
  query?: never;
  url: "/api/leads/leads/{id}/";
};

export type ApiLeadsLeadsPartialUpdateResponses = {
  200: LeadSubmission;
};

export type ApiLeadsLeadsPartialUpdateResponse =
  ApiLeadsLeadsPartialUpdateResponses[keyof ApiLeadsLeadsPartialUpdateResponses];

export type ApiLeadsLeadsUpdateData = {
  body: LeadSubmissionRequest;
  path: {
    /**
     * A unique integer value identifying this Lead.
     */
    id: number;
  };
  query?: never;
  url: "/api/leads/leads/{id}/";
};

export type ApiLeadsLeadsUpdateResponses = {
  200: LeadSubmission;
};

export type ApiLeadsLeadsUpdateResponse =
  ApiLeadsLeadsUpdateResponses[keyof ApiLeadsLeadsUpdateResponses];

export type ApiLeadsLeadsSubmitCreateData = {
  body: LeadSubmissionRequest;
  path?: never;
  query?: never;
  url: "/api/leads/leads/submit/";
};

export type ApiLeadsLeadsSubmitCreateErrors = {
  400: LeadSubmissionError;
};

export type ApiLeadsLeadsSubmitCreateError =
  ApiLeadsLeadsSubmitCreateErrors[keyof ApiLeadsLeadsSubmitCreateErrors];

export type ApiLeadsLeadsSubmitCreateResponses = {
  201: LeadSubmissionResponse;
};

export type ApiLeadsLeadsSubmitCreateResponse =
  ApiLeadsLeadsSubmitCreateResponses[keyof ApiLeadsLeadsSubmitCreateResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
