// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.680857

package cfg__newsletter__bulk_email


// Simple serializer for bulk email.
type BulkEmailRequest struct {
	Recipients []string `json:"recipients"`
	Subject string `json:"subject"`
	EmailTitle string `json:"email_title"`
	MainText string `json:"main_text"`
	MainHTMLContent *string `json:"main_html_content,omitempty"`
	ButtonText *string `json:"button_text,omitempty"`
	ButtonURL *string `json:"button_url,omitempty"`
	SecondaryText *string `json:"secondary_text,omitempty"`
}

// Response for bulk email sending.
type BulkEmailResponse struct {
	Success bool `json:"success"`
	SentCount int64 `json:"sent_count"`
	FailedCount int64 `json:"failed_count"`
	TotalRecipients int64 `json:"total_recipients"`
	Error *string `json:"error,omitempty"`
}

