"""
django_grpc.services.h3 — HTTP/3 (QUIC) reverse proxy for the gRPC server.

This module provides an opt-in HTTP/3 frontend for the django_grpc module. It
runs a Hypercorn[h3] ASGI server on a separate port that transparently forwards
every HTTP request (including the HTTP/2 frames that carry gRPC traffic) to the
existing `grpc.aio.server()` running on a loopback HTTP/2 origin.

Why a reverse proxy and not native gRPC-over-QUIC?
    grpcio's C-core does not (yet) support HTTP/3. Building a thin Hypercorn
    proxy lets us serve HTTP/3 to clients that want it without modifying the
    server, the interceptor chain (auth, error handling, observability), the
    proto definitions, or the Django app — all of those continue to run on the
    upstream HTTP/2 gRPC server.

The H3 listener is a sibling asyncio task to `grpc.aio.server()`. It is started
from `rungrpc` only when `enable_h3=True` (config field) or `--http3` (CLI flag)
is set. Cancelling the task triggers a clean Hypercorn shutdown.

Dependencies (optional extras group `grpc-h3`):
    - hypercorn[h3]>=0.14.0
    - aioquic>=0.9.21

Install with:
    pip install 'django-cfg[grpc-h3]'
"""

from __future__ import annotations

import asyncio
import logging
from typing import TYPE_CHECKING, Any, Awaitable, Callable, Optional

if TYPE_CHECKING:
    from django_cfg.modules.django_grpc.config.server import GrpcServerConfig

logger = logging.getLogger(__name__)

# ASGI scope/message types — kept loose to avoid a hard runtime dep on a
# specific ASGI typing package.
Scope = dict
Message = dict
Receive = Callable[[], Awaitable[Message]]
Send = Callable[[Message], Awaitable[None]]


# ---------------------------------------------------------------------------
# Internal: hop-by-hop headers we must NOT forward (RFC 7230 §6.1)
# ---------------------------------------------------------------------------

_HOP_BY_HOP_HEADERS = frozenset(
    h.lower()
    for h in (
        "connection",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "te",
        "trailer",
        "transfer-encoding",
        "upgrade",
        # gRPC-specific: must be regenerated by the upstream HTTP/2 server.
        "host",
    )
)


def _filter_request_headers(headers: list[tuple[bytes, bytes]]) -> list[tuple[str, str]]:
    """Strip hop-by-hop headers, decode to str/str for httpx."""
    out: list[tuple[str, str]] = []
    for k, v in headers:
        name = k.decode("latin-1")
        if name.lower() in _HOP_BY_HOP_HEADERS:
            continue
        out.append((name, v.decode("latin-1")))
    return out


def _filter_response_headers(headers: Any) -> list[tuple[bytes, bytes]]:
    """Strip hop-by-hop headers, encode for ASGI send()."""
    out: list[tuple[bytes, bytes]] = []
    for k, v in headers.raw:  # httpx exposes raw bytes via .raw
        if k.decode("latin-1").lower() in _HOP_BY_HOP_HEADERS:
            continue
        out.append((k, v))
    return out


# ---------------------------------------------------------------------------
# H3Proxy
# ---------------------------------------------------------------------------


class H3Proxy:
    """
    HTTP/3 reverse proxy that forwards traffic to an upstream HTTP/2 origin.

    Public surface:
        proxy = H3Proxy(
            upstream_host="127.0.0.1",
            upstream_port=50051,
            listen_host="0.0.0.0",
            listen_port=50052,
            tls_certfile="/etc/ssl/server.crt",   # optional, recommended
            tls_keyfile="/etc/ssl/server.key",    # optional, recommended
        )
        await proxy.serve()       # blocks until cancelled
        # Cancelling the wrapping task triggers Hypercorn shutdown.

    Notes:
        - HTTP/3 mandates TLS. If `tls_certfile`/`tls_keyfile` are not given,
          Hypercorn falls back to HTTP/2 cleartext for development convenience —
          a warning is logged and clients won't actually negotiate H3 in that
          mode. For real H3, pass certs.
        - The proxy keeps a single shared httpx.AsyncClient with HTTP/2 enabled
          to the upstream, so connections are pooled.
    """

    DEFAULT_UPSTREAM_HOST = "127.0.0.1"

    def __init__(
        self,
        *,
        upstream_host: str,
        upstream_port: int,
        listen_host: str = "0.0.0.0",
        listen_port: int = 50052,
        tls_certfile: Optional[str] = None,
        tls_keyfile: Optional[str] = None,
        upstream_scheme: str = "http",
    ) -> None:
        if not (1 <= upstream_port <= 65535):
            raise ValueError(f"upstream_port out of range: {upstream_port}")
        if not (1 <= listen_port <= 65535):
            raise ValueError(f"listen_port out of range: {listen_port}")
        if upstream_scheme not in ("http", "https"):
            raise ValueError(f"upstream_scheme must be 'http' or 'https', got {upstream_scheme}")

        # Normalize wildcards to a routable upstream address: a wildcard
        # ([::], 0.0.0.0) is a bind address, not a connect address.
        if upstream_host in ("[::]", "::", "0.0.0.0", ""):
            self.upstream_host = self.DEFAULT_UPSTREAM_HOST
        else:
            self.upstream_host = upstream_host

        self.upstream_port = upstream_port
        self.listen_host = listen_host
        self.listen_port = listen_port
        self.tls_certfile = tls_certfile
        self.tls_keyfile = tls_keyfile
        self.upstream_scheme = upstream_scheme

        self._shutdown_event: Optional[asyncio.Event] = None

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def upstream_url_base(self) -> str:
        return f"{self.upstream_scheme}://{self.upstream_host}:{self.upstream_port}"

    @property
    def listen_address(self) -> str:
        return f"{self.listen_host}:{self.listen_port}"

    # ------------------------------------------------------------------
    # ASGI app
    # ------------------------------------------------------------------

    def build_app(self) -> Callable[[Scope, Receive, Send], Awaitable[None]]:
        """
        Build the ASGI application that forwards every request to the upstream.

        Imports `httpx` lazily inside `serve()` to keep the import surface clean
        (httpx is a core django-cfg dep but the proxy logic shouldn't run if H3
        is disabled).
        """
        try:
            import httpx
        except ImportError as exc:  # pragma: no cover — httpx is a core dep
            raise RuntimeError(
                "H3Proxy requires httpx (it ships with django-cfg core deps)."
            ) from exc

        # Single shared client with HTTP/2 to upstream + generous timeouts so
        # bidirectional streaming RPCs (e.g., gRPC streams) aren't aborted.
        client = httpx.AsyncClient(
            base_url=self.upstream_url_base,
            http2=True,
            timeout=httpx.Timeout(None),
        )

        upstream_url_base = self.upstream_url_base

        async def app(scope: Scope, receive: Receive, send: Send) -> None:
            if scope["type"] == "lifespan":
                # Drain lifespan events and clean up the httpx client on shutdown.
                while True:
                    msg = await receive()
                    if msg["type"] == "lifespan.startup":
                        await send({"type": "lifespan.startup.complete"})
                    elif msg["type"] == "lifespan.shutdown":
                        try:
                            await client.aclose()
                        except Exception:
                            pass
                        await send({"type": "lifespan.shutdown.complete"})
                        return
                    else:
                        return

            if scope["type"] != "http":
                # We don't support websockets here — gRPC doesn't use them.
                return

            method: str = scope["method"]
            path: str = scope["path"]
            query: bytes = scope.get("query_string", b"")
            url = path + (("?" + query.decode("latin-1")) if query else "")
            headers = _filter_request_headers(scope.get("headers") or [])

            # Stream the request body without buffering the full payload so
            # gRPC streaming (which can be unbounded) keeps flowing.
            async def request_body_stream():
                while True:
                    message = await receive()
                    if message["type"] != "http.request":
                        # Disconnects, etc. End the upstream body.
                        return
                    body = message.get("body", b"")
                    if body:
                        yield body
                    if not message.get("more_body", False):
                        return

            try:
                req = client.build_request(
                    method=method,
                    url=url,
                    headers=headers,
                    content=request_body_stream(),
                )
                response = await client.send(req, stream=True)
            except Exception as e:
                logger.warning(
                    "[H3Proxy] upstream %s %s%s failed: %s",
                    method, upstream_url_base, url, e,
                )
                await send({
                    "type": "http.response.start",
                    "status": 502,
                    "headers": [(b"content-type", b"text/plain; charset=utf-8")],
                })
                await send({
                    "type": "http.response.body",
                    "body": f"H3 proxy upstream error: {e}".encode("utf-8"),
                })
                return

            try:
                await send({
                    "type": "http.response.start",
                    "status": response.status_code,
                    "headers": _filter_response_headers(response.headers),
                })
                async for chunk in response.aiter_raw():
                    await send({
                        "type": "http.response.body",
                        "body": chunk,
                        "more_body": True,
                    })
                await send({"type": "http.response.body", "body": b"", "more_body": False})
            finally:
                try:
                    await response.aclose()
                except Exception:
                    pass

        return app

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def _build_hypercorn_config(self):
        """Construct a HypercornConfig with H3 enabled when TLS certs are present."""
        try:
            from hypercorn.config import Config as HypercornConfig
        except ImportError as exc:
            raise RuntimeError(
                "H3Proxy requires hypercorn[h3]. Install with: "
                "pip install 'django-cfg[grpc-h3]'"
            ) from exc

        cfg = HypercornConfig()
        cfg.bind = [self.listen_address]
        # Hypercorn auto-enables HTTP/3 when both QUIC binding and TLS certs are provided.
        if self.tls_certfile and self.tls_keyfile:
            cfg.quic_bind = [self.listen_address]
            cfg.certfile = self.tls_certfile
            cfg.keyfile = self.tls_keyfile
            cfg.alpn_protocols = ["h3", "h2", "http/1.1"]
        else:
            logger.warning(
                "[H3Proxy] No TLS certs supplied — Hypercorn will serve HTTP/1.1+HTTP/2 "
                "cleartext on %s and clients will NOT negotiate HTTP/3. "
                "Provide tls_certfile/tls_keyfile to enable real QUIC.",
                self.listen_address,
            )
        cfg.loglevel = "info"
        cfg.accesslog = "-"
        cfg.errorlog = "-"
        return cfg

    async def serve(self) -> None:
        """
        Run the Hypercorn[h3] server until cancelled.

        Cancellation (e.g., the wrapping task being cancelled at shutdown)
        triggers Hypercorn's graceful shutdown via the shutdown_trigger.
        """
        try:
            from hypercorn.asyncio import serve as hypercorn_serve
        except ImportError as exc:
            raise RuntimeError(
                "H3Proxy requires hypercorn[h3]. Install with: "
                "pip install 'django-cfg[grpc-h3]'"
            ) from exc

        cfg = self._build_hypercorn_config()
        app = self.build_app()
        self._shutdown_event = asyncio.Event()

        async def shutdown_trigger() -> None:
            await self._shutdown_event.wait()  # type: ignore[union-attr]

        logger.info(
            "[H3Proxy] Starting Hypercorn on %s -> upstream %s (h3=%s)",
            self.listen_address,
            self.upstream_url_base,
            bool(self.tls_certfile and self.tls_keyfile),
        )

        try:
            await hypercorn_serve(app, cfg, shutdown_trigger=shutdown_trigger)  # type: ignore[arg-type]
        except asyncio.CancelledError:
            # Caller cancelled us — signal Hypercorn and re-raise so the parent
            # task tree completes the cancellation chain.
            self.trigger_shutdown()
            raise

    def trigger_shutdown(self) -> None:
        """Signal a clean Hypercorn shutdown (idempotent)."""
        ev = self._shutdown_event
        if ev is not None and not ev.is_set():
            ev.set()


# ---------------------------------------------------------------------------
# Builder helper used by rungrpc
# ---------------------------------------------------------------------------


def build_h3_proxy_from_server_config(
    server_cfg: "GrpcServerConfig",
) -> H3Proxy:
    """
    Build an H3Proxy from a GrpcServerConfig.

    The upstream is always the gRPC server's host:port — when the gRPC server
    binds a wildcard address ([::], 0.0.0.0) we connect to loopback, since the
    H3 process and the gRPC process are the same Python interpreter.

    TLS certs are pulled from `server_cfg.tls` when configured. Without certs,
    Hypercorn serves cleartext (no real H3) — see H3Proxy._build_hypercorn_config.
    """
    tls_certfile: Optional[str] = None
    tls_keyfile: Optional[str] = None
    tls_cfg = getattr(server_cfg, "tls", None)
    if tls_cfg is not None and getattr(tls_cfg, "enabled", False):
        tls_certfile = getattr(tls_cfg, "cert_path", None)
        tls_keyfile = getattr(tls_cfg, "key_path", None)

    return H3Proxy(
        upstream_host=server_cfg.host,
        upstream_port=server_cfg.port,
        listen_host=server_cfg.h3_host,
        listen_port=server_cfg.h3_port,
        tls_certfile=tls_certfile,
        tls_keyfile=tls_keyfile,
    )


__all__ = ["H3Proxy", "build_h3_proxy_from_server_config"]
