"""Render a SWR mutation hook for a non-GET operation."""

from __future__ import annotations

from .sdk_names import (
    sdk_class_name,
    sdk_method_name,
    sdk_type_names,
)
from ..ir import IROperation


def render_mutation(op: IROperation, hook: str) -> str:
    cls = sdk_class_name(op)
    method = sdk_method_name(op)
    data_t, resp_t = sdk_type_names(op)
    summary = op.summary or f"{op.method.upper()} {op.path}"
    return f"""// AUTO-GENERATED by django-cfg / django_generator.ts_extras
// {summary}
// DO NOT EDIT — re-run `make gen`.

import useSWRMutation from "swr/mutation";
import type {{ SWRMutationConfiguration }} from "swr/mutation";
import {{ {cls} }} from "../sdk.gen";
import type {{ {data_t}, {resp_t} }} from "../types.gen";

type Args = Omit<{data_t}, "url">;
type Result = {resp_t}[keyof {resp_t}];

export function {hook}(
  config?: SWRMutationConfiguration<Result, Error, readonly ["{op.operation_id}"], Args>,
) {{
  return useSWRMutation<Result, Error, readonly ["{op.operation_id}"], Args>(
    ["{op.operation_id}"] as const,
    async (_key, {{ arg }}: {{ arg: Args }}) => {{
      const res = await {cls}.{method}({{ ...arg, throwOnError: true }} as never);
      return res.data as Result;
    }},
    config,
  );
}}
"""
