"""Render a SWR query hook for a GET operation."""

from __future__ import annotations

from .sdk_names import (
    sdk_class_name,
    sdk_method_name,
    sdk_type_names,
)
from ..ir import IROperation


def render_query(op: IROperation, hook: str) -> str:
    cls = sdk_class_name(op)
    method = sdk_method_name(op)
    data_t, resp_t = sdk_type_names(op)
    summary = op.summary or f"{op.method.upper()} {op.path}"
    return f"""// AUTO-GENERATED by django-cfg / django_generator.ts_extras
// {summary}
// DO NOT EDIT — re-run `make gen`.

import useSWR from "swr";
import type {{ SWRConfiguration }} from "swr";
import {{ {cls} }} from "../sdk.gen";
import type {{ {data_t}, {resp_t} }} from "../types.gen";

type Args = Omit<{data_t}, "url"> | undefined;
type Result = {resp_t}[keyof {resp_t}];

export function {hook}(
  args: Args,
  config?: SWRConfiguration<Result>,
) {{
  const key = args ? ["{op.operation_id}", args] as const : null;
  return useSWR<Result>(
    key,
    async () => {{
      const res = await {cls}.{method}({{ ...(args ?? {{}}), throwOnError: true }} as never);
      return res.data as Result;
    }},
    config,
  );
}}
"""
