// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.510640

package cfg__dashboard__dashboard_system

import (
	"cfg/types"
)

// Serializer for overall system health status.
type SystemHealth struct {
	// Overall system health status
	// 
	// * `healthy` - healthy
	// * `warning` - warning
	// * `error` - error
	// * `unknown` - unknown
	OverallStatus types.SystemhealthOverallStatus `json:"overall_status"`
	// Overall health percentage
	OverallHealthPercentage int64 `json:"overall_health_percentage"`
	// Health status of individual components
	Components []SystemHealthItem `json:"components"`
	// Check timestamp (ISO format)
	Timestamp string `json:"timestamp"`
}

// Serializer for system health status items.
// 
// Maps to SystemHealthItem Pydantic model.
type SystemHealthItem struct {
	// Component name
	Component string `json:"component"`
	// Health status
	// 
	// * `healthy` - healthy
	// * `warning` - warning
	// * `error` - error
	// * `unknown` - unknown
	Status types.SystemhealthitemStatus `json:"status"`
	// Status description
	Description string `json:"description"`
	// Last check time (ISO format)
	LastCheck string `json:"last_check"`
	// Health percentage (0-100)
	HealthPercentage *int64 `json:"health_percentage,omitempty"`
}

// Serializer for system performance metrics.
type SystemMetrics struct {
	// CPU usage percentage
	CpuUsage float64 `json:"cpu_usage"`
	// Memory usage percentage
	MemoryUsage float64 `json:"memory_usage"`
	// Disk usage percentage
	DiskUsage float64 `json:"disk_usage"`
	// Network incoming bandwidth
	NetworkIn string `json:"network_in"`
	// Network outgoing bandwidth
	NetworkOut string `json:"network_out"`
	// Average response time
	ResponseTime string `json:"response_time"`
	// System uptime
	Uptime string `json:"uptime"`
}

