// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.565441

package cfg

import (
	"net/http"
	"cfg/cfg__accounts__auth"
	"cfg/cfg__newsletter__bulk_email"
	"cfg/cfg__newsletter__campaigns"
	"cfg/cfg__centrifugo__centrifugo_admin_api"
	"cfg/cfg__centrifugo__centrifugo_monitoring"
	"cfg/cfg__centrifugo__centrifugo_testing"
	"cfg/cfg__dashboard__dashboard_api_zones"
	"cfg/cfg__dashboard__dashboard_activity"
	"cfg/cfg__dashboard__dashboard_charts"
	"cfg/cfg__dashboard__dashboard_commands"
	"cfg/cfg__dashboard__dashboard_overview"
	"cfg/cfg__dashboard__dashboard_statistics"
	"cfg/cfg__dashboard__dashboard_system"
	"cfg/cfg__leads__lead_submission"
	"cfg/cfg__newsletter__logs"
	"cfg/cfg__newsletter__newsletters"
	"cfg/cfg__newsletter__subscriptions"
	"cfg/cfg__newsletter__testing"
	"cfg/cfg__accounts__user_profile"
	"cfg/cfg__accounts"
	"cfg/cfg__centrifugo"
	"cfg/cfg__endpoints"
	"cfg/cfg__health"
	"cfg/cfg__knowbase"
	"cfg/cfg__leads"
	"cfg/cfg__newsletter"
	"cfg/cfg__payments"
	"cfg/cfg__support"
	"cfg/cfg__tasks"
)

// Client is the main API client with sub-clients for each module.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	Token      string

	// CfgAccountsAuth provides access to CfgAccountsAuth operations
	CfgAccountsAuth *cfg__accounts__auth.Client
	// CfgNewsletterBulkEmail provides access to CfgNewsletterBulkEmail operations
	CfgNewsletterBulkEmail *cfg__newsletter__bulk_email.Client
	// CfgNewsletterCampaigns provides access to CfgNewsletterCampaigns operations
	CfgNewsletterCampaigns *cfg__newsletter__campaigns.Client
	// CfgCentrifugoCentrifugoAdminAPI provides access to CfgCentrifugoCentrifugoAdminAPI operations
	CfgCentrifugoCentrifugoAdminAPI *cfg__centrifugo__centrifugo_admin_api.Client
	// CfgCentrifugoCentrifugoMonitoring provides access to CfgCentrifugoCentrifugoMonitoring operations
	CfgCentrifugoCentrifugoMonitoring *cfg__centrifugo__centrifugo_monitoring.Client
	// CfgCentrifugoCentrifugoTesting provides access to CfgCentrifugoCentrifugoTesting operations
	CfgCentrifugoCentrifugoTesting *cfg__centrifugo__centrifugo_testing.Client
	// CfgDashboardDashboardAPIZones provides access to CfgDashboardDashboardAPIZones operations
	CfgDashboardDashboardAPIZones *cfg__dashboard__dashboard_api_zones.Client
	// CfgDashboardDashboardActivity provides access to CfgDashboardDashboardActivity operations
	CfgDashboardDashboardActivity *cfg__dashboard__dashboard_activity.Client
	// CfgDashboardDashboardCharts provides access to CfgDashboardDashboardCharts operations
	CfgDashboardDashboardCharts *cfg__dashboard__dashboard_charts.Client
	// CfgDashboardDashboardCommands provides access to CfgDashboardDashboardCommands operations
	CfgDashboardDashboardCommands *cfg__dashboard__dashboard_commands.Client
	// CfgDashboardDashboardOverview provides access to CfgDashboardDashboardOverview operations
	CfgDashboardDashboardOverview *cfg__dashboard__dashboard_overview.Client
	// CfgDashboardDashboardStatistics provides access to CfgDashboardDashboardStatistics operations
	CfgDashboardDashboardStatistics *cfg__dashboard__dashboard_statistics.Client
	// CfgDashboardDashboardSystem provides access to CfgDashboardDashboardSystem operations
	CfgDashboardDashboardSystem *cfg__dashboard__dashboard_system.Client
	// CfgLeadsLeadSubmission provides access to CfgLeadsLeadSubmission operations
	CfgLeadsLeadSubmission *cfg__leads__lead_submission.Client
	// CfgNewsletterLogs provides access to CfgNewsletterLogs operations
	CfgNewsletterLogs *cfg__newsletter__logs.Client
	// CfgNewsletterNewsletters provides access to CfgNewsletterNewsletters operations
	CfgNewsletterNewsletters *cfg__newsletter__newsletters.Client
	// CfgNewsletterSubscriptions provides access to CfgNewsletterSubscriptions operations
	CfgNewsletterSubscriptions *cfg__newsletter__subscriptions.Client
	// CfgNewsletterTesting provides access to CfgNewsletterTesting operations
	CfgNewsletterTesting *cfg__newsletter__testing.Client
	// CfgAccountsUserProfile provides access to CfgAccountsUserProfile operations
	CfgAccountsUserProfile *cfg__accounts__user_profile.Client
	// CfgAccounts provides access to CfgAccounts operations
	CfgAccounts *cfg__accounts.Client
	// CfgCentrifugo provides access to CfgCentrifugo operations
	CfgCentrifugo *cfg__centrifugo.Client
	// CfgEndpoints provides access to CfgEndpoints operations
	CfgEndpoints *cfg__endpoints.Client
	// CfgHealth provides access to CfgHealth operations
	CfgHealth *cfg__health.Client
	// CfgKnowbase provides access to CfgKnowbase operations
	CfgKnowbase *cfg__knowbase.Client
	// CfgLeads provides access to CfgLeads operations
	CfgLeads *cfg__leads.Client
	// CfgNewsletter provides access to CfgNewsletter operations
	CfgNewsletter *cfg__newsletter.Client
	// CfgPayments provides access to CfgPayments operations
	CfgPayments *cfg__payments.Client
	// CfgSupport provides access to CfgSupport operations
	CfgSupport *cfg__support.Client
	// CfgTasks provides access to CfgTasks operations
	CfgTasks *cfg__tasks.Client
}

// NewClient creates a new API client.
func NewClient(baseURL string, options ...Option) *Client {
	client := &Client{
		BaseURL:    baseURL,
		HTTPClient: &http.Client{},
	}

	// Apply options
	for _, opt := range options {
		opt(client)
	}

	// Initialize sub-clients
	client.CfgAccountsAuth = cfg__accounts__auth.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgNewsletterBulkEmail = cfg__newsletter__bulk_email.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgNewsletterCampaigns = cfg__newsletter__campaigns.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgCentrifugoCentrifugoAdminAPI = cfg__centrifugo__centrifugo_admin_api.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgCentrifugoCentrifugoMonitoring = cfg__centrifugo__centrifugo_monitoring.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgCentrifugoCentrifugoTesting = cfg__centrifugo__centrifugo_testing.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgDashboardDashboardAPIZones = cfg__dashboard__dashboard_api_zones.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgDashboardDashboardActivity = cfg__dashboard__dashboard_activity.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgDashboardDashboardCharts = cfg__dashboard__dashboard_charts.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgDashboardDashboardCommands = cfg__dashboard__dashboard_commands.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgDashboardDashboardOverview = cfg__dashboard__dashboard_overview.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgDashboardDashboardStatistics = cfg__dashboard__dashboard_statistics.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgDashboardDashboardSystem = cfg__dashboard__dashboard_system.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgLeadsLeadSubmission = cfg__leads__lead_submission.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgNewsletterLogs = cfg__newsletter__logs.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgNewsletterNewsletters = cfg__newsletter__newsletters.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgNewsletterSubscriptions = cfg__newsletter__subscriptions.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgNewsletterTesting = cfg__newsletter__testing.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgAccountsUserProfile = cfg__accounts__user_profile.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgAccounts = cfg__accounts.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgCentrifugo = cfg__centrifugo.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgEndpoints = cfg__endpoints.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgHealth = cfg__health.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgKnowbase = cfg__knowbase.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgLeads = cfg__leads.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgNewsletter = cfg__newsletter.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgPayments = cfg__payments.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgSupport = cfg__support.NewClient(baseURL, client.HTTPClient, client.Token)
	client.CfgTasks = cfg__tasks.NewClient(baseURL, client.HTTPClient, client.Token)

	return client
}

// Option is a functional option for configuring the Client.
type Option func(*Client)

// WithHTTPClient sets a custom HTTP client.
func WithHTTPClient(httpClient *http.Client) Option {
	return func(c *Client) {
		c.HTTPClient = httpClient
	}
}

// WithToken sets the authentication token.
func WithToken(token string) Option {
	return func(c *Client) {
		c.Token = token
	}
}