// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.514502

package cfg__accounts

import (
	"cfg/types"
	"time"
)

// Error response for OTP operations.
type OTPErrorResponse struct {
	// Error message
	Error string `json:"error"`
}

// Serializer for OTP request.
type OTPRequestRequest struct {
	// Email address or phone number for OTP delivery
	Identifier string `json:"identifier"`
	// Delivery channel: 'email' or 'phone'. Auto-detected if not provided.
	// 
	// * `email` - Email
	// * `phone` - Phone
	Channel *types.OtprequestrequestChannel `json:"channel,omitempty"`
	// Source URL for tracking registration (e.g., https://dashboard.unrealon.com)
	SourceURL *string `json:"source_url,omitempty"`
}

// OTP request response.
type OTPRequestResponse struct {
	// Success message
	Message string `json:"message"`
}

// Serializer for OTP verification.
type OTPVerifyRequest struct {
	// Email address or phone number used for OTP request
	Identifier string `json:"identifier"`
	Otp string `json:"otp"`
	// Delivery channel: 'email' or 'phone'. Auto-detected if not provided.
	// 
	// * `email` - Email
	// * `phone` - Phone
	Channel *types.OtpverifyrequestChannel `json:"channel,omitempty"`
	// Source URL for tracking login (e.g., https://dashboard.unrealon.com)
	SourceURL *string `json:"source_url,omitempty"`
}

// OTP verification response.
type OTPVerifyResponse struct {
	// JWT refresh token
	Refresh string `json:"refresh"`
	// JWT access token
	Access string `json:"access"`
	User User `json:"user"`
}

// Serializer for user details.
type User struct {
	ID int64 `json:"id"`
	Email string `json:"email"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	// Get user's full name.
	FullName string `json:"full_name"`
	// Get user's initials for avatar fallback.
	Initials string `json:"initials"`
	// Get formatted username for display.
	DisplayUsername string `json:"display_username"`
	Company *string `json:"company,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Position *string `json:"position,omitempty"`
	Avatar string `json:"avatar"`
	// Designates whether the user can log into this admin site.
	IsStaff bool `json:"is_staff"`
	// Designates that this user has all permissions without explicitly assigning them.
	IsSuperuser bool `json:"is_superuser"`
	DateJoined time.Time `json:"date_joined"`
	LastLogin time.Time `json:"last_login"`
	// Get count of unanswered messages for the user.
	UnansweredMessagesCount int64 `json:"unanswered_messages_count"`
}

