"""Go wrapper generator — post-processes ogen output.

Walks ``out_dir`` for ``oas_security_gen.go``, introspects the
``SecuritySource`` interface (``JwtAuth`` / ``JwtAuthWithLastLogin``
and any future scheme), and emits ``wrapper.go`` with:

  * ``bearerSecuritySource`` — implements ``SecuritySource`` via a Bearer token.
  * ``DjangoClientOption`` / ``DjangoClientOptions`` — functional-option pattern.
  * ``WithToken``, ``WithAPIKey``, ``WithBaseURL``, ``WithEnv`` helpers.
  * ``DjangoClient`` — thin facade over ogen's ``*Client``.
  * ``NewDjangoClient`` — wires everything together; resolves base URL from
    ``<PKG_BASE_URL_ENV>`` env var when ``WithBaseURL`` is not passed.

Usage::

    from openapi_processor.go.tool import generate
    result = generate(out_dir=Path("..."), package="api")
    print(result.written)
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path


# ── Public result type ───────────────────────────────────────────────


@dataclass(slots=True)
class GoWrapperResult:
    out_dir: Path
    written: list[Path] = field(default_factory=list)
    skipped: bool = False


# ── Security introspection ───────────────────────────────────────────

# Matches: JwtAuth(ctx context.Context, operationName OperationName) (JwtAuth, error)
_METHOD_RE = re.compile(
    r"^\s{1,2}(\w+)\s*\(ctx\s+context\.Context",
    re.MULTILINE,
)

# Matches the interface block:  type SecuritySource interface { ... }
_SEC_IFACE_RE = re.compile(
    r"type\s+SecuritySource\s+interface\s*\{([^}]+)\}",
    re.DOTALL,
)


def _discover_security_methods(out_dir: Path) -> list[str]:
    """Return method names declared in ``SecuritySource`` interface.

    Falls back to ``["JwtAuth"]`` when the file is missing or the pattern
    doesn't match — keeps generation working even for minimal specs.
    """
    sec_file = out_dir / "oas_security_gen.go"
    if not sec_file.is_file():
        return ["JwtAuth"]

    text = sec_file.read_text(encoding="utf-8")
    m = _SEC_IFACE_RE.search(text)
    if not m:
        return ["JwtAuth"]

    body = m.group(1)
    methods = _METHOD_RE.findall(body)
    return methods if methods else ["JwtAuth"]


def _discover_package(out_dir: Path) -> str:
    """Return the Go package name from any ``*.go`` file in ``out_dir``."""
    for go_file in sorted(out_dir.glob("oas_*.go")):
        text = go_file.read_text(encoding="utf-8")
        m = re.search(r"^package\s+(\w+)", text, re.MULTILINE)
        if m:
            return m.group(1)
    return "api"


# ── Code rendering ───────────────────────────────────────────────────


def _env_const_name(package: str) -> str:
    """``api`` → ``APIBaseURLEnv``."""
    return package.upper() + "BaseURLEnv"


def _render_bearer_security_source(methods: list[str]) -> str:
    """Render ``bearerSecuritySource`` implementing ``SecuritySource``."""
    lines = [
        "// bearerSecuritySource satisfies the generated SecuritySource interface.",
        "// It injects an Authorization: Bearer header on every authenticated request.",
        "type bearerSecuritySource struct {",
        "\ttoken string",
        "}",
        "",
    ]
    for method in methods:
        # Each scheme uses the same token; ogen types have a Token field.
        lines += [
            f"func (s *bearerSecuritySource) {method}(_ context.Context, _ OperationName) ({method}, error) {{",
            f"\treturn {method}{{Token: s.token}}, nil",
            "}",
            "",
        ]
    return "\n".join(lines)


def _render_wrapper(package: str, methods: list[str]) -> str:
    """Render the full ``wrapper.go`` file content."""
    env_const = _env_const_name(package)
    bearer_block = _render_bearer_security_source(methods)

    return f'''// Code generated by openapi_processor.go — DO NOT EDIT.
// Regenerated on every `make gen`.

package {package}

import (
\t"context"
\t"fmt"
\t"net/http"
\t"os"
\t"sync"
)

// {env_const} is the environment variable consulted when no base URL is
// provided via WithBaseURL.  Set it to your Django backend URL, e.g.
//
//\texport {env_const}=https://api.example.com
const {env_const} = "{package.upper()}_BASE_URL"

// ── Security source ──────────────────────────────────────────────────────────

{bearer_block}
// ── Functional options ───────────────────────────────────────────────────────

// DjangoClientOption mutates DjangoClientOptions before client construction.
type DjangoClientOption func(*DjangoClientOptions)

// DjangoClientOptions holds resolved configuration for DjangoClient.
type DjangoClientOptions struct {{
\tBaseURL   string
\tToken     string
\tAPIKey    string    // sent as X-Api-Key header
\tEnv       string    // "dev" | "prod" | "" (no override)
\tDevURL    string    // URL used when Env == "dev"
\tProdURL   string    // URL used when Env == "prod"
\tHTTPClient *http.Client
}}

// WithToken sets the Bearer token used for authenticated endpoints.
func WithToken(token string) DjangoClientOption {{
\treturn func(o *DjangoClientOptions) {{ o.Token = token }}
}}

// WithAPIKey sets an API key forwarded via the X-Api-Key header.
// The ogen HTTP round-tripper intercepts this before requests.
func WithAPIKey(key string) DjangoClientOption {{
\treturn func(o *DjangoClientOptions) {{ o.APIKey = key }}
}}

// WithBaseURL overrides the backend base URL.
func WithBaseURL(url string) DjangoClientOption {{
\treturn func(o *DjangoClientOptions) {{ o.BaseURL = url }}
}}

// WithEnv selects a named environment ("dev" or "prod").
// DevURL and ProdURL must be set alongside this option.
func WithEnv(env, devURL, prodURL string) DjangoClientOption {{
\treturn func(o *DjangoClientOptions) {{
\t\to.Env = env
\t\to.DevURL = devURL
\t\to.ProdURL = prodURL
\t}}
}}

// WithHTTPClient replaces the default http.Client.
func WithHTTPClient(c *http.Client) DjangoClientOption {{
\treturn func(o *DjangoClientOptions) {{ o.HTTPClient = c }}
}}

// ── API-key round-tripper ────────────────────────────────────────────────────

type apiKeyTransport struct {{
\tkey  string
\twrap http.RoundTripper
}}

func (t *apiKeyTransport) RoundTrip(req *http.Request) (*http.Response, error) {{
\tr := req.Clone(req.Context())
\tr.Header.Set("X-Api-Key", t.key)
\treturn t.wrap.RoundTrip(r)
}}

// ── DjangoClient ─────────────────────────────────────────────────────────────

// DjangoClient wraps the ogen-generated *Client, adding token management and
// dev/prod environment switching.
//
// Usage:
//
//\tc, err := NewDjangoClient(WithToken("..."), WithEnv("prod", devURL, prodURL))
//\tif err != nil {{ ... }}
//\t// c.Client is the raw ogen client
//\tresult, err := c.Client.SkillsSkillsList(ctx, params)
type DjangoClient struct {{
\tClient *Client
\tmu     sync.RWMutex
\topts   DjangoClientOptions
}}

// NewDjangoClient constructs a DjangoClient from functional options.
//
// Base URL resolution order:
//  1. WithEnv → picks devURL or prodURL based on env string.
//  2. WithBaseURL → explicit URL.
//  3. {env_const} environment variable.
//  4. Error if none of the above resolves.
func NewDjangoClient(options ...DjangoClientOption) (*DjangoClient, error) {{
\topts := DjangoClientOptions{{}}
\tfor _, o := range options {{
\t\to(&opts)
\t}}

\t// Resolve base URL
\tbaseURL := opts.BaseURL
\tif opts.Env != "" {{
\t\tswitch opts.Env {{
\t\tcase "dev":
\t\t\tbaseURL = opts.DevURL
\t\tcase "prod":
\t\t\tbaseURL = opts.ProdURL
\t\tdefault:
\t\t\treturn nil, fmt.Errorf("django client: unknown env %q (want \\"dev\\" or \\"prod\\")", opts.Env)
\t\t}}
\t}}
\tif baseURL == "" {{
\t\tbaseURL = os.Getenv({env_const})
\t}}
\tif baseURL == "" {{
\t\treturn nil, fmt.Errorf(
\t\t\t"django client: base URL is required — use WithBaseURL, WithEnv, or set %s",
\t\t\t{env_const},
\t\t)
\t}}

\t// Security source
\tsec := &bearerSecuritySource{{token: opts.Token}}

\t// HTTP client
\thttpClient := opts.HTTPClient
\tif httpClient == nil {{
\t\thttpClient = &http.Client{{}}
\t}}
\tif opts.APIKey != "" {{
\t\thttpClient = &http.Client{{
\t\t\tTransport: &apiKeyTransport{{key: opts.APIKey, wrap: httpClient.Transport}},
\t\t\tCheckRedirect: httpClient.CheckRedirect,
\t\t\tJar:           httpClient.Jar,
\t\t\tTimeout:       httpClient.Timeout,
\t\t}}
\t}}

\tclient, err := NewClient(baseURL, sec, WithClient(httpClient))
\tif err != nil {{
\t\treturn nil, fmt.Errorf("django client: %w", err)
\t}}

\treturn &DjangoClient{{Client: client, opts: opts}}, nil
}}

// SetToken replaces the Bearer token for subsequent requests.
// Safe for concurrent use.
func (d *DjangoClient) SetToken(token string) {{
\td.mu.Lock()
\tdefer d.mu.Unlock()
\t// Re-use existing opts but swap the token and rebuild.
\td.opts.Token = token
\tif src, ok := d.Client.sec.(*bearerSecuritySource); ok {{
\t\tsrc.token = token
\t}}
}}

// BaseURL returns the current backend URL.
func (d *DjangoClient) BaseURL() string {{
\treturn d.Client.serverURL.String()
}}

// Env returns the environment string passed via WithEnv (empty if not set).
func (d *DjangoClient) Env() string {{
\treturn d.opts.Env
}}

// ── Context helpers ──────────────────────────────────────────────────────────

// WithContext is a no-op helper that makes call sites self-documenting when
// the caller wants to pass a context to individual operations.
//
//\tc.Client.SkillsSkillsList(c.WithContext(ctx), params)
func (d *DjangoClient) WithContext(ctx context.Context) context.Context {{
\treturn ctx
}}
'''


# ── Entry point ──────────────────────────────────────────────────────


def generate(out_dir: Path, package: str | None = None) -> GoWrapperResult:
    """Emit ``wrapper.go`` alongside ogen output in ``out_dir``.

    ``package`` defaults to the name discovered from ``oas_*.go`` files.
    Skips generation when no ``oas_*.go`` files are present.

    Also runs ``_patch_opt_marshal_json`` on ``oas_json_gen.go`` to fix
    an upstream ogen bug — see that function's docstring. The patch
    runs unconditionally; the wrapper.go emission only fires when a
    JWT-style ``SecuritySource`` is present (the wrapper is a Bearer
    helper and useless on specs that don't use one).
    """
    out_dir = Path(out_dir)
    oas_files = list(out_dir.glob("oas_*.go"))
    if not oas_files:
        return GoWrapperResult(out_dir=out_dir, skipped=True)

    # Always run — fixes a runtime crash in stdjson Marshal of any
    # struct with an Opt*/OptNil* field.
    _patch_opt_marshal_json(out_dir)
    # Also fix the broken otel import prefix (see _patch_otel_imports).
    _patch_otel_imports(out_dir)

    # The Bearer wrapper only makes sense when ogen actually emitted a
    # JWT security source. Specs without it (e.g. FastAPI exposing a
    # cookie/session scheme) end up with an undefined-symbols compile
    # error if we still write wrapper.go.
    if not (out_dir / "oas_security_gen.go").is_file():
        return GoWrapperResult(out_dir=out_dir, skipped=True)

    pkg = package or _discover_package(out_dir)
    methods = _discover_security_methods(out_dir)
    text = _render_wrapper(pkg, methods)

    target = out_dir / "wrapper.go"
    target.write_text(text, encoding="utf-8")
    _gofmt(target)
    return GoWrapperResult(out_dir=out_dir, written=[target])


# ── Opt*.MarshalJSON fix ─────────────────────────────────────────────


# Match an Opt*/OptNil* MarshalJSON body that is missing the "not Set"
# guard. The unpatched template ogen emits is:
#
#     func (s OptFoo) MarshalJSON() ([]byte, error) {
#         e := jx.Encoder{}
#         s.Encode(&e)
#         return e.Bytes(), nil
#     }
#
# (OptNil* variants pass a `format` callback as the second arg.) When the
# value is unset, Encode early-returns and writes nothing — the empty
# byte slice then crashes encoding/json on the parent struct with
# "unexpected end of JSON input". The fix is to emit literal `null`,
# which is what stdjson expects from a Marshaler for an absent field.
#
# Conservative: only matches the exact 4-line shape ogen produces, so
# we don't accidentally rewrite anything else.
_MARSHAL_JSON_PATTERN = re.compile(
    r"(func \(s (Opt[A-Za-z0-9_]+)\) MarshalJSON\(\) \(\[\]byte, error\) \{\n"
    r")(\te := jx\.Encoder\{\}\n"
    r"\ts\.Encode\(&e(?:, [^)]+)?\)\n"
    r"\treturn e\.Bytes\(\), nil\n"
    r"\})",
)


def _patch_opt_marshal_json(out_dir: Path) -> None:
    """Inject ``if !s.Set { return []byte("null"), nil }`` into Opt*.MarshalJSON.

    Targets ``oas_json_gen.go`` only. The unpatched ogen template returns
    empty bytes when the optional value is unset, which breaks the
    parent struct's MarshalJSON. The fix mirrors what ogen *should*
    have generated — see https://github.com/ogen-go/ogen for the
    upstream bug context.

    Idempotent: re-running on already-patched files is a no-op.
    """
    target = out_dir / "oas_json_gen.go"
    if not target.is_file():
        return
    original = target.read_text(encoding="utf-8")

    def _inject(m: re.Match[str]) -> str:
        header, body = m.group(1), m.group(3)
        # If somebody already added the guard, leave it alone.
        if "if !s.Set" in body:
            return m.group(0)
        return (
            f"{header}"
            f"\tif !s.Set {{\n"
            f'\t\treturn []byte("null"), nil\n'
            f"\t}}\n"
            f"{body}"
        )

    patched = _MARSHAL_JSON_PATTERN.sub(_inject, original)
    if patched != original:
        target.write_text(patched, encoding="utf-8")


# Match `<go-module-path>/<pkg-path>/go.opentelemetry.io/otel...` —
# ogen sometimes emits the otel import path with the consuming module's
# Go path glued in front, which becomes an unresolvable import. The
# real path is always plain `go.opentelemetry.io/otel...`.
_OTEL_BAD_IMPORT = re.compile(
    r'"[^"]*?/go\.opentelemetry\.io(/otel[^"]*)"'
)


def _patch_otel_imports(out_dir: Path) -> None:
    """Strip module-path prefix from broken otel imports.

    ogen 1.x leaks the consumer's Go module path before
    ``go.opentelemetry.io/...`` in a handful of generated files
    (oas_cfg_gen.go, oas_client_gen.go, oas_handlers_gen.go,
    oas_labeler_gen.go, oas_response_encoders_gen.go). Replace with
    the canonical import path so ``go build`` resolves the package.

    Idempotent.
    """
    for path in out_dir.glob("oas_*.go"):
        original = path.read_text(encoding="utf-8")
        patched = _OTEL_BAD_IMPORT.sub(r'"go.opentelemetry.io\1"', original)
        if patched != original:
            path.write_text(patched, encoding="utf-8")


def _gofmt(path: Path) -> None:
    """Run ``gofmt -w`` on ``path`` if gofmt is available; silently skip otherwise."""
    gofmt = shutil.which("gofmt")
    if gofmt is None:
        return
    try:
        subprocess.run([gofmt, "-w", str(path)], check=True, capture_output=True)
    except subprocess.CalledProcessError:
        pass


__all__ = ["GoWrapperResult", "generate"]
