from .BulkEmailRequest import *
from .EmailLog import *
from .EmailLogStatusEnum import *
from .Newsletter import *
from .NewsletterCampaign import *
from .NewsletterCampaignRequest import *
from .NewsletterCampaignStatusEnum import *
from .NewsletterSubscription import *
from .PaginatedEmailLogList import *
from .PaginatedNewsletterCampaignList import *
from .PaginatedNewsletterList import *
from .PaginatedNewsletterSubscriptionList import *
from .PatchedNewsletterCampaignRequest import *
from .PatchedUnsubscribeRequest import *
from .SendCampaignRequest import *
from .SubscribeRequest import *
from .TestEmailRequest import *
from .Unsubscribe import *
from .UnsubscribeRequest import *
