// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.686844

package cfg__newsletter__logs

import (
	"cfg/types"
	"time"
)

// Serializer for EmailLog model.
type EmailLog struct {
	ID string `json:"id"`
	User int64 `json:"user"`
	UserEmail string `json:"user_email"`
	Newsletter int64 `json:"newsletter"`
	NewsletterTitle string `json:"newsletter_title"`
	// Comma-separated email addresses
	Recipient string `json:"recipient"`
	Subject string `json:"subject"`
	Body string `json:"body"`
	// * `pending` - Pending
	// * `sent` - Sent
	// * `failed` - Failed
	Status types.EmaillogStatus `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	SentAt time.Time `json:"sent_at"`
	ErrorMessage string `json:"error_message"`
}

// PaginatedEmailLogList model.
type PaginatedEmailLogList struct {
	// Total number of items across all pages
	Count int64 `json:"count"`
	// Current page number (1-based)
	Page int64 `json:"page"`
	// Total number of pages
	Pages int64 `json:"pages"`
	// Number of items per page
	PageSize int64 `json:"page_size"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool `json:"has_previous"`
	// Next page number (null if no next page)
	NextPage *int64 `json:"next_page,omitempty"`
	// Previous page number (null if no previous page)
	PreviousPage *int64 `json:"previous_page,omitempty"`
	// Array of items for current page
	Results []EmailLog `json:"results"`
}

