// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  ApiSupportTicketsListData,
  ApiSupportTicketsListResponses,
  ApiSupportTicketsCreateData,
  ApiSupportTicketsCreateResponses,
  ApiSupportTicketsMessagesListData,
  ApiSupportTicketsMessagesListResponses,
  ApiSupportTicketsMessagesCreateData,
  ApiSupportTicketsMessagesCreateResponses,
  ApiSupportTicketsMessagesDestroyData,
  ApiSupportTicketsMessagesDestroyResponses,
  ApiSupportTicketsMessagesRetrieveData,
  ApiSupportTicketsMessagesRetrieveResponses,
  ApiSupportTicketsMessagesPartialUpdateData,
  ApiSupportTicketsMessagesPartialUpdateResponses,
  ApiSupportTicketsMessagesUpdateData,
  ApiSupportTicketsMessagesUpdateResponses,
  ApiSupportTicketsDestroyData,
  ApiSupportTicketsDestroyResponses,
  ApiSupportTicketsRetrieveData,
  ApiSupportTicketsRetrieveResponses,
  ApiSupportTicketsPartialUpdateData,
  ApiSupportTicketsPartialUpdateResponses,
  ApiSupportTicketsUpdateData,
  ApiSupportTicketsUpdateResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * ViewSet for managing support tickets.
 */
export const apiSupportTicketsList = <ThrowOnError extends boolean = false>(
  options?: Options<ApiSupportTicketsListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ApiSupportTicketsListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/",
    ...options,
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const apiSupportTicketsCreate = <ThrowOnError extends boolean = false>(
  options: Options<ApiSupportTicketsCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiSupportTicketsCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support messages.
 */
export const apiSupportTicketsMessagesList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiSupportTicketsMessagesListData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ApiSupportTicketsMessagesListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/",
    ...options,
  });
};

/**
 * ViewSet for managing support messages.
 */
export const apiSupportTicketsMessagesCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiSupportTicketsMessagesCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiSupportTicketsMessagesCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support messages.
 */
export const apiSupportTicketsMessagesDestroy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiSupportTicketsMessagesDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    ApiSupportTicketsMessagesDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/",
    ...options,
  });
};

/**
 * ViewSet for managing support messages.
 */
export const apiSupportTicketsMessagesRetrieve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiSupportTicketsMessagesRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ApiSupportTicketsMessagesRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/",
    ...options,
  });
};

/**
 * ViewSet for managing support messages.
 */
export const apiSupportTicketsMessagesPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiSupportTicketsMessagesPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    ApiSupportTicketsMessagesPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support messages.
 */
export const apiSupportTicketsMessagesUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiSupportTicketsMessagesUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    ApiSupportTicketsMessagesUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const apiSupportTicketsDestroy = <ThrowOnError extends boolean = false>(
  options: Options<ApiSupportTicketsDestroyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    ApiSupportTicketsDestroyResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{uuid}/",
    ...options,
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const apiSupportTicketsRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<ApiSupportTicketsRetrieveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ApiSupportTicketsRetrieveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{uuid}/",
    ...options,
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const apiSupportTicketsPartialUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiSupportTicketsPartialUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    ApiSupportTicketsPartialUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * ViewSet for managing support tickets.
 */
export const apiSupportTicketsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ApiSupportTicketsUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    ApiSupportTicketsUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/support/tickets/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
