// This file is auto-generated by @hey-api/openapi-ts

export type Message = {
  readonly uuid: string;
  readonly ticket: string;
  sender: Sender;
  /**
   * Check if this message is from the ticket author.
   */
  readonly is_from_author: boolean;
  text: string;
  readonly created_at: string;
};

export type MessageCreate = {
  text: string;
};

export type MessageCreateRequest = {
  text: string;
};

export type MessageRequest = {
  text: string;
};

export type PatchedMessageRequest = {
  text?: string;
};

export type PatchedTicketRequest = {
  user?: number;
  subject?: string;
  status?: StatusEnum;
};

export type Sender = {
  readonly id: number;
  /**
   * Get formatted username for display.
   */
  readonly display_username: string;
  readonly email: string;
  readonly avatar: string | null;
  /**
   * Get user's initials for avatar fallback.
   */
  readonly initials: string;
  /**
   * Staff status
   * Designates whether the user can log into this admin site.
   */
  readonly is_staff: boolean;
  /**
   * Superuser status
   * Designates that this user has all permissions without explicitly assigning them.
   */
  readonly is_superuser: boolean;
};

/**
 * * `open` - Open
 * * `waiting_for_user` - Waiting for User
 * * `waiting_for_admin` - Waiting for Admin
 * * `resolved` - Resolved
 * * `closed` - Closed
 */
export type StatusEnum =
  | "open"
  | "waiting_for_user"
  | "waiting_for_admin"
  | "resolved"
  | "closed";

export type Ticket = {
  readonly uuid: string;
  user: number;
  subject: string;
  status?: StatusEnum;
  readonly created_at: string;
  /**
   * Get count of unanswered messages for this specific ticket.
   */
  readonly unanswered_messages_count: number;
};

export type TicketRequest = {
  user: number;
  subject: string;
  status?: StatusEnum;
};

export type ApiSupportTicketsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A search term.
     */
    search?: string;
  };
  url: "/api/support/tickets/";
};

export type ApiSupportTicketsListResponses = {
  200: Array<Ticket>;
};

export type ApiSupportTicketsListResponse =
  ApiSupportTicketsListResponses[keyof ApiSupportTicketsListResponses];

export type ApiSupportTicketsCreateData = {
  body: TicketRequest;
  path?: never;
  query?: never;
  url: "/api/support/tickets/";
};

export type ApiSupportTicketsCreateResponses = {
  201: Ticket;
};

export type ApiSupportTicketsCreateResponse =
  ApiSupportTicketsCreateResponses[keyof ApiSupportTicketsCreateResponses];

export type ApiSupportTicketsMessagesListData = {
  body?: never;
  path: {
    /**
     * UUID of the ticket
     */
    ticket_uuid: string;
  };
  query?: {
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * A search term.
     */
    search?: string;
  };
  url: "/api/support/tickets/{ticket_uuid}/messages/";
};

export type ApiSupportTicketsMessagesListResponses = {
  200: Array<Message>;
};

export type ApiSupportTicketsMessagesListResponse =
  ApiSupportTicketsMessagesListResponses[keyof ApiSupportTicketsMessagesListResponses];

export type ApiSupportTicketsMessagesCreateData = {
  body: MessageCreateRequest;
  path: {
    /**
     * UUID of the ticket
     */
    ticket_uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{ticket_uuid}/messages/";
};

export type ApiSupportTicketsMessagesCreateResponses = {
  201: MessageCreate;
};

export type ApiSupportTicketsMessagesCreateResponse =
  ApiSupportTicketsMessagesCreateResponses[keyof ApiSupportTicketsMessagesCreateResponses];

export type ApiSupportTicketsMessagesDestroyData = {
  body?: never;
  path: {
    /**
     * UUID of the ticket
     */
    ticket_uuid: string;
    /**
     * UUID of the message
     */
    uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/";
};

export type ApiSupportTicketsMessagesDestroyResponses = {
  /**
   * No response body
   */
  204: void;
};

export type ApiSupportTicketsMessagesDestroyResponse =
  ApiSupportTicketsMessagesDestroyResponses[keyof ApiSupportTicketsMessagesDestroyResponses];

export type ApiSupportTicketsMessagesRetrieveData = {
  body?: never;
  path: {
    /**
     * UUID of the ticket
     */
    ticket_uuid: string;
    /**
     * UUID of the message
     */
    uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/";
};

export type ApiSupportTicketsMessagesRetrieveResponses = {
  200: Message;
};

export type ApiSupportTicketsMessagesRetrieveResponse =
  ApiSupportTicketsMessagesRetrieveResponses[keyof ApiSupportTicketsMessagesRetrieveResponses];

export type ApiSupportTicketsMessagesPartialUpdateData = {
  body?: PatchedMessageRequest;
  path: {
    /**
     * UUID of the ticket
     */
    ticket_uuid: string;
    /**
     * UUID of the message
     */
    uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/";
};

export type ApiSupportTicketsMessagesPartialUpdateResponses = {
  200: Message;
};

export type ApiSupportTicketsMessagesPartialUpdateResponse =
  ApiSupportTicketsMessagesPartialUpdateResponses[keyof ApiSupportTicketsMessagesPartialUpdateResponses];

export type ApiSupportTicketsMessagesUpdateData = {
  body: MessageRequest;
  path: {
    /**
     * UUID of the ticket
     */
    ticket_uuid: string;
    /**
     * UUID of the message
     */
    uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{ticket_uuid}/messages/{uuid}/";
};

export type ApiSupportTicketsMessagesUpdateResponses = {
  200: Message;
};

export type ApiSupportTicketsMessagesUpdateResponse =
  ApiSupportTicketsMessagesUpdateResponses[keyof ApiSupportTicketsMessagesUpdateResponses];

export type ApiSupportTicketsDestroyData = {
  body?: never;
  path: {
    /**
     * A UUID string identifying this ticket.
     */
    uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{uuid}/";
};

export type ApiSupportTicketsDestroyResponses = {
  /**
   * No response body
   */
  204: void;
};

export type ApiSupportTicketsDestroyResponse =
  ApiSupportTicketsDestroyResponses[keyof ApiSupportTicketsDestroyResponses];

export type ApiSupportTicketsRetrieveData = {
  body?: never;
  path: {
    /**
     * A UUID string identifying this ticket.
     */
    uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{uuid}/";
};

export type ApiSupportTicketsRetrieveResponses = {
  200: Ticket;
};

export type ApiSupportTicketsRetrieveResponse =
  ApiSupportTicketsRetrieveResponses[keyof ApiSupportTicketsRetrieveResponses];

export type ApiSupportTicketsPartialUpdateData = {
  body?: PatchedTicketRequest;
  path: {
    /**
     * A UUID string identifying this ticket.
     */
    uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{uuid}/";
};

export type ApiSupportTicketsPartialUpdateResponses = {
  200: Ticket;
};

export type ApiSupportTicketsPartialUpdateResponse =
  ApiSupportTicketsPartialUpdateResponses[keyof ApiSupportTicketsPartialUpdateResponses];

export type ApiSupportTicketsUpdateData = {
  body: TicketRequest;
  path: {
    /**
     * A UUID string identifying this ticket.
     */
    uuid: string;
  };
  query?: never;
  url: "/api/support/tickets/{uuid}/";
};

export type ApiSupportTicketsUpdateResponses = {
  200: Ticket;
};

export type ApiSupportTicketsUpdateResponse =
  ApiSupportTicketsUpdateResponses[keyof ApiSupportTicketsUpdateResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
