// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.685900

package cfg__dashboard__dashboard_statistics


// Serializer for user statistics.
type UserStatistics struct {
	// Total number of users
	TotalUsers int64 `json:"total_users"`
	// Active users (last 30 days)
	ActiveUsers int64 `json:"active_users"`
	// New users (last 7 days)
	NewUsers int64 `json:"new_users"`
	// Number of superusers
	Superusers int64 `json:"superusers"`
}

