// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.687204

package cfg__newsletter__newsletters

import (
	"time"
)

// Serializer for Newsletter model.
type Newsletter struct {
	ID int64 `json:"id"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	// Automatically subscribe new users to this newsletter
	AutoSubscribe *bool `json:"auto_subscribe,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	SubscribersCount int64 `json:"subscribers_count"`
}

// PaginatedNewsletterList model.
type PaginatedNewsletterList struct {
	// Total number of items across all pages
	Count int64 `json:"count"`
	// Current page number (1-based)
	Page int64 `json:"page"`
	// Total number of pages
	Pages int64 `json:"pages"`
	// Number of items per page
	PageSize int64 `json:"page_size"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool `json:"has_previous"`
	// Next page number (null if no next page)
	NextPage *int64 `json:"next_page,omitempty"`
	// Previous page number (null if no previous page)
	PreviousPage *int64 `json:"previous_page,omitempty"`
	// Array of items for current page
	Results []Newsletter `json:"results"`
}

