client_class_name: Cfg_AgentsClient
follow_redirects: true
generate_aliases: true
http_timeout: 30
literal_enums: true
package_name_override: django_revolution_cfg_agents
post_hooks: []
project_name_override: django_revolution_cfg_agents
use_pydantic_v2: true
use_string_enums: false
