// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:33.430870

package trading

import (
	"net/http"
	"trading/trading__api__trading"
)

// Client is the main API client with sub-clients for each module.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	Token      string

	// TradingAPITrading provides access to TradingAPITrading operations
	TradingAPITrading *trading__api__trading.Client
}

// NewClient creates a new API client.
func NewClient(baseURL string, options ...Option) *Client {
	client := &Client{
		BaseURL:    baseURL,
		HTTPClient: &http.Client{},
	}

	// Apply options
	for _, opt := range options {
		opt(client)
	}

	// Initialize sub-clients
	client.TradingAPITrading = trading__api__trading.NewClient(baseURL, client.HTTPClient, client.Token)

	return client
}

// Option is a functional option for configuring the Client.
type Option func(*Client)

// WithHTTPClient sets a custom HTTP client.
func WithHTTPClient(httpClient *http.Client) Option {
	return func(c *Client) {
		c.HTTPClient = httpClient
	}
}

// WithToken sets the authentication token.
func WithToken(token string) Option {
	return func(c *Client) {
		c.Token = token
	}
}