// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-28T07:47:34.392030

package cfg__accounts__auth


// TokenRefresh model.
type TokenRefresh struct {
	Access string `json:"access"`
	Refresh string `json:"refresh"`
}

// TokenRefreshRequest model.
type TokenRefreshRequest struct {
	Refresh string `json:"refresh"`
}

