// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.685291

package cfg__dashboard__dashboard_charts


// Chart.js data structure serializer.
type ChartData struct {
	Labels []string `json:"labels"`
	Datasets []ChartDataset `json:"datasets"`
}

// Chart.js dataset serializer.
type ChartDataset struct {
	Label string `json:"label"`
	Data []int64 `json:"data"`
	Backgroundcolor string `json:"backgroundColor"`
	Bordercolor string `json:"borderColor"`
	Tension float64 `json:"tension"`
	Fill *bool `json:"fill,omitempty"`
}

