# Generated by Django 5.2.12 on 2026-05-10 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_cfg_accounts", "0020_userapikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="API key in plain text (UUIDv4).",
                unique=True,
            ),
        ),
    ]
