# Generated by Django 5.2.14 on 2026-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_cfg_accounts", "0021_alter_userapikey_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When the email was first OTP-verified.", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_email_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True once the user has successfully completed at least one OTP login.",
            ),
        ),
    ]
