# Generated by Django 5.2.16 on 2026-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_cfg_accounts", "0023_backfill_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpsecret",
            name="consent_disclosure_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="otpsecret",
            name="consent_jurisdiction_hint",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="otpsecret",
            name="marketing_consent",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
