# Generated by Django 5.2.16 on 2026-08-18 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_cfg_accounts", "0025_customuser_welcome_email_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="API key in plain text (UUIDv4). Stored unhashed on purpose so `/reveal` can return it to its owner for agent onboarding; rotate with regenerate() to revoke.",
                unique=True,
            ),
        ),
    ]
