# Generated by Django 5.2.16 on 2026-08-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Which letter this is, e.g. 'welcome'. Matches the template directory name.",
                        max_length=64,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        help_text="BCP-47 tag, e.g. 'ru' or 'pt-BR'. Region subtags are kept as-is.",
                        max_length=16,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Envelope Subject: header. Translated — an English subject over a translated letter is the most visible way to get this wrong.",
                        max_length=255,
                    ),
                ),
                ("greeting", models.CharField(blank=True, help_text="'Hi —'", max_length=128)),
                (
                    "lede",
                    models.TextField(blank=True, help_text="Opening paragraphs. One per line."),
                ),
                (
                    "run_intro",
                    models.CharField(
                        blank=True, help_text="Line introducing the command block.", max_length=255
                    ),
                ),
                (
                    "run_after",
                    models.TextField(
                        blank=True, help_text="Paragraphs after the command block. One per line."
                    ),
                ),
                (
                    "points",
                    models.TextField(blank=True, help_text="The middle paragraphs. One per line."),
                ),
                (
                    "outro",
                    models.TextField(blank=True, help_text="Closing paragraph(s). One per line."),
                ),
                (
                    "signoff",
                    models.TextField(
                        blank=True, help_text="The ask before the signature, e.g. inviting a reply."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="What follows the sender's name in the signature, e.g. 'founder of Cmdop'.",
                        max_length=128,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Unchecking falls this locale back to the default one, without deleting the text.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email content",
                "verbose_name_plural": "Email content",
                "ordering": ("key", "locale"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "locale"), name="emailcontent_unique_key_locale"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Which letter this was, e.g. 'welcome'. Blank for ad-hoc mail.",
                        max_length=64,
                    ),
                ),
                ("recipient", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        help_text="The locale it rendered in — the field that answers 'why was it in English'.",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Handed to the transport"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Transport error, when the attempt failed. Kept verbatim: a paraphrased provider message is not diagnosable.",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="The recipient's user id, if any.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Email log",
                "verbose_name_plural": "Email log",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["key", "-created_at"], name="django_cfg__key_d2f73d_idx")
                ],
            },
        ),
    ]
