# Generated by Django 5.2.17 on 2026-08-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_cfg_mailer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="dedup_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifies the letter, not the row: event + channel + recipient. Two rows sharing one is a double send, which is the thing a retry must be able to check for before sending again.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the transport accepted it. NULL on a `queued` row that was never resolved — the signature of a process that died mid-send, and the only way to find one.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                condition=models.Q(("status", "queued")),
                fields=["created_at"],
                name="mailer_log_stuck_queued_idx",
            ),
        ),
    ]
