"""Render zod schema TS files + barrel indexes."""

from __future__ import annotations

from ..naming import schema_constant


def render_schema_file(
    *,
    name: str,
    body: str,
    deps: list[tuple[str, str]],
) -> str:
    """Render one schema file.

    Args:
      name: schema name.
      body: zod expression body.
      deps: list of (dep_name, relative_module_path) — e.g.
        ("User", "../accounts/User") for cross-tag deps,
        ("Address", "./Address") for same-tag deps.
    """
    const = schema_constant(name)
    lines = [
        "// AUTO-GENERATED by django-cfg / django_generator.ts_extras",
        "// Source: OpenAPI 3.1 components.schemas",
        "// DO NOT EDIT — re-run `make gen`.",
        "",
        'import { z } from "zod";',
    ]
    for dep_name, dep_path in deps:
        lines.append(f'import {{ {schema_constant(dep_name)} }} from "{dep_path}";')
    lines.extend(
        [
            "",
            f"export const {const} = {body};",
            "",
            f"export type {name} = z.infer<typeof {const}>;",
            "",
        ]
    )
    return "\n".join(lines)


def render_tag_index(names: list[str]) -> str:
    """Per-tag (or _shared) barrel: re-exports from sibling schema files."""
    lines = [
        "// AUTO-GENERATED — barrel for zod schemas.",
        "// DO NOT EDIT.",
        "",
    ]
    lines.extend(f'export * from "./{n}";' for n in sorted(names))
    lines.append("")
    return "\n".join(lines)


def render_root_index(folders: list[str]) -> str:
    """Top-level `schemas/index.ts` re-exporting every tag folder."""
    lines = [
        "// AUTO-GENERATED — root barrel for grouped zod schemas.",
        "// DO NOT EDIT.",
        "",
    ]
    lines.extend(f'export * from "./{f}";' for f in sorted(folders))
    lines.append("")
    return "\n".join(lines)
