// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.688286

package cfg__accounts__user_profile

import (
	"time"
)

// Serializer for updating user profile.
type PatchedUserProfileUpdateRequest struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Company *string `json:"company,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Position *string `json:"position,omitempty"`
}

// Serializer for user details.
type User struct {
	ID int64 `json:"id"`
	Email string `json:"email"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	// Get user's full name.
	FullName string `json:"full_name"`
	// Get user's initials for avatar fallback.
	Initials string `json:"initials"`
	// Get formatted username for display.
	DisplayUsername string `json:"display_username"`
	Company *string `json:"company,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Position *string `json:"position,omitempty"`
	Avatar string `json:"avatar"`
	// Designates whether the user can log into this admin site.
	IsStaff bool `json:"is_staff"`
	// Designates that this user has all permissions without explicitly assigning them.
	IsSuperuser bool `json:"is_superuser"`
	DateJoined time.Time `json:"date_joined"`
	LastLogin time.Time `json:"last_login"`
	// Get count of unanswered messages for the user.
	UnansweredMessagesCount int64 `json:"unanswered_messages_count"`
}

// Serializer for updating user profile.
type UserProfileUpdateRequest struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Company *string `json:"company,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Position *string `json:"position,omitempty"`
}

