// Code generated by django-cfg/django_client - DO NOT EDIT.
// Generated at: 2025-10-27T19:13:24.685688

package cfg__dashboard__dashboard_overview


// Main serializer for dashboard overview endpoint.
// Uses DictField to avoid allOf generation in OpenAPI.
type DashboardOverview struct {
	// Dashboard statistics cards
	StatCards []map[string]interface{} `json:"stat_cards"`
	// System health status
	SystemHealth []map[string]interface{} `json:"system_health"`
	// Quick action buttons
	QuickActions []map[string]interface{} `json:"quick_actions"`
	// Recent activity entries
	RecentActivity []map[string]interface{} `json:"recent_activity"`
	// System performance metrics
	SystemMetrics map[string]interface{} `json:"system_metrics"`
	// User statistics
	UserStatistics map[string]interface{} `json:"user_statistics"`
	// Data timestamp (ISO format)
	Timestamp string `json:"timestamp"`
}

