"""Render zod schema TS files + barrel index."""

from __future__ import annotations

from ..naming import schema_constant


def render_schema_file(*, name: str, body: str, deps: list[str]) -> str:
    const = schema_constant(name)
    lines = [
        "// AUTO-GENERATED by cmdop_server / devtools.generator.ts_extras",
        "// Source: OpenAPI 3.1 components.schemas",
        "// DO NOT EDIT — re-run `make gen-clients`.",
        "",
        'import { z } from "zod";',
    ]
    for dep in deps:
        lines.append(f'import {{ {schema_constant(dep)} }} from "./{dep}";')
    lines.extend(
        [
            "",
            f"export const {const} = {body};",
            "",
            f"export type {name} = z.infer<typeof {const}>;",
            "",
        ]
    )
    return "\n".join(lines)


def render_index(names: list[str]) -> str:
    lines = [
        "// AUTO-GENERATED — barrel for zod schemas.",
        "// DO NOT EDIT.",
        "",
    ]
    lines.extend(f'export * from "./{n}";' for n in names)
    lines.append("")
    return "\n".join(lines)
